// ═══════════════════════════════════════════════════════════════
// Skill World — 20 Learning Categories
// ═══════════════════════════════════════════════════════════════

import type { SkillCategory } from './types';

const SKILL_CATEGORIES: SkillCategory[] = [
  {
    id: 'english-communication',
    name: 'English Buddy',
    emoji: '📘',
    gradient: 'from-blue-500 to-indigo-600',
    glowColor: 'shadow-blue-500/30',
    description: 'Master English speaking & writing with fun dialogues',
  },
  {
    id: 'tamil-learning',
    name: 'Tamil Learning',
    emoji: '🐯',
    gradient: 'from-red-500 to-rose-600',
    glowColor: 'shadow-red-500/30',
    description: 'Learn Tamil through culture and stories',
  },
  {
    id: 'life-skills',
    name: 'Real Life Skills',
    emoji: '🌍',
    gradient: 'from-emerald-500 to-green-600',
    glowColor: 'shadow-emerald-500/30',
    description: 'Practical skills for everyday situations',
  },
  {
    id: 'money-management',
    name: 'Money Management',
    emoji: '💰',
    gradient: 'from-amber-500 to-orange-600',
    glowColor: 'shadow-amber-500/30',
    description: 'Learn saving, spending, and smart money choices',
  },
  {
    id: 'kindness-empathy',
    name: 'Kindness & Empathy',
    emoji: '❤️',
    gradient: 'from-pink-500 to-rose-600',
    glowColor: 'shadow-pink-500/30',
    description: 'Understand feelings and spread kindness',
  },
  {
    id: 'learn-say-no',
    name: 'Learn to Say NO',
    emoji: '🛡️',
    gradient: 'from-violet-500 to-purple-600',
    glowColor: 'shadow-violet-500/30',
    description: 'Build boundaries and stand up for yourself',
  },
  {
    id: 'negotiation',
    name: 'Negotiation Skills',
    emoji: '🤝',
    gradient: 'from-teal-500 to-cyan-600',
    glowColor: 'shadow-teal-500/30',
    description: 'Find win-win solutions in every situation',
  },
  {
    id: 'communication',
    name: 'Communication Skills',
    emoji: '🗣️',
    gradient: 'from-sky-500 to-blue-600',
    glowColor: 'shadow-sky-500/30',
    description: 'Express yourself clearly and listen well',
  },
  {
    id: 'internet-tech',
    name: 'Internet & Technology',
    emoji: '🌐',
    gradient: 'from-cyan-500 to-blue-600',
    glowColor: 'shadow-cyan-500/30',
    description: 'Navigate the digital world safely',
  },
  {
    id: 'ai-chatbots',
    name: 'AI & Chatbots',
    emoji: '🤖',
    gradient: 'from-fuchsia-500 to-purple-600',
    glowColor: 'shadow-fuchsia-500/30',
    description: 'Understand AI, chatbots, and the future',
  },
  {
    id: 'creativity',
    name: 'Creativity & Imagination',
    emoji: '🎨',
    gradient: 'from-orange-500 to-red-500',
    glowColor: 'shadow-orange-500/30',
    description: 'Unlock your creative superpowers',
  },
  {
    id: 'confidence',
    name: 'Confidence Building',
    emoji: '💪',
    gradient: 'from-yellow-500 to-amber-600',
    glowColor: 'shadow-yellow-500/30',
    description: 'Believe in yourself and shine bright',
  },
  {
    id: 'leadership',
    name: 'Leadership Missions',
    emoji: '👑',
    gradient: 'from-indigo-500 to-violet-600',
    glowColor: 'shadow-indigo-500/30',
    description: 'Lead teams and inspire others',
  },
  {
    id: 'focus-discipline',
    name: 'Focus & Discipline',
    emoji: '🎯',
    gradient: 'from-slate-500 to-zinc-600',
    glowColor: 'shadow-slate-500/30',
    description: 'Build laser focus and strong habits',
  },
  {
    id: 'safety',
    name: 'Safety Awareness',
    emoji: '🔒',
    gradient: 'from-red-500 to-orange-600',
    glowColor: 'shadow-red-500/30',
    description: 'Stay safe at home, school, and online',
  },
  {
    id: 'social-skills',
    name: 'Social Skills',
    emoji: '👥',
    gradient: 'from-lime-500 to-green-600',
    glowColor: 'shadow-lime-500/30',
    description: 'Make friends and work with others',
  },
  {
    id: 'habit-building',
    name: 'Habit Building',
    emoji: '📅',
    gradient: 'from-emerald-500 to-teal-600',
    glowColor: 'shadow-emerald-500/30',
    description: 'Build good habits that last forever',
  },
  {
    id: 'emotional-control',
    name: 'Emotional Control',
    emoji: '🧘',
    gradient: 'from-purple-500 to-indigo-600',
    glowColor: 'shadow-purple-500/30',
    description: 'Manage big feelings with calm strength',
  },
  {
    id: 'problem-solving',
    name: 'Problem Solving',
    emoji: '🧩',
    gradient: 'from-blue-500 to-purple-600',
    glowColor: 'shadow-blue-500/30',
    description: 'Think smart and solve tricky challenges',
  },
  {
    id: 'public-speaking',
    name: 'Public Speaking',
    emoji: '🎤',
    gradient: 'from-rose-500 to-pink-600',
    glowColor: 'shadow-rose-500/30',
    description: 'Speak with power in front of any crowd',
  },
];

export default SKILL_CATEGORIES;
