export const SCIENCE_QUESTIONS: { 
  title: string; 
  title_ta: string; 
  question: string; 
  question_ta: string; 
  options: string[]; 
  options_ta: string[]; 
  answer: string; 
  answer_ta: string; 
  explanation: string; 
  explanation_ta: string; 
  classRange: [number, number];
}[] = [
  // Grade 1-2 (classRange: [1, 2])
  {
    title: "🦁 Animal Sound",
    title_ta: "🦁 விலங்கு ஒலி",
    question: "Which animal roars?",
    question_ta: "எந்த விலங்கு கர்ஜிக்கிறது?",
    options: ["Dog", "Cat", "Lion", "Rabbit"],
    options_ta: ["நாய்", "பூனை", "சிங்கம்", "முயல்"],
    answer: "Lion",
    answer_ta: "சிங்கம்",
    explanation: "Lions roar loudly to protect their pride and territory! 🦁",
    explanation_ta: "சிங்கங்கள் தங்கள் கூட்டத்தையும் எல்லையையும் பாதுகாக்க சத்தமாகக் கர்ஜிக்கின்றன! 🦁",
    classRange: [1, 2]
  },
  {
    title: "🐘 Animal Size",
    title_ta: "🐘 விலங்கு அளவு",
    question: "Which of these is the largest land animal?",
    question_ta: "நிலத்தில் வாழும் மிகப்பெரிய விலங்கு எது?",
    options: ["Elephant", "Cat", "Dog", "Mouse"],
    options_ta: ["யானை", "பூனை", "நாய்", "எலி"],
    answer: "Elephant",
    answer_ta: "யானை",
    explanation: "The African Elephant is the largest and heaviest land animal on Earth! 🐘",
    explanation_ta: "ஆப்பிரிக்க யானையே பூமியின் மிகப்பெரிய மற்றும் அதிக எடையுள்ள நில விலங்கு! 🐘",
    classRange: [1, 2]
  },
  {
    title: "🍎 Sweet Taste",
    title_ta: "🍎 சுவையான பழம்",
    question: "Which fruit is red and grows on trees?",
    question_ta: "மரத்தில் வளரும் சிவப்பு நிறப் பழம் எது?",
    options: ["Banana", "Grapes", "Apple", "Pineapple"],
    options_ta: ["வாழை", "திராட்சை", "ஆப்பிள்", "அன்னாசி"],
    answer: "Apple",
    answer_ta: "ஆப்பிள்",
    explanation: "Apples are healthy, crisp fruits that can be red, green, or yellow! 🍎",
    explanation_ta: "ஆப்பிள்கள் சிவப்பு, பச்சை அல்லது மஞ்சள் நிறத்தில் இருக்கும் ஒரு ஆரோக்கியமான பழம்! 🍎",
    classRange: [1, 2]
  },
  {
    title: "💧 Water Source",
    title_ta: "💧 நீரின் ஆதாரம்",
    question: "Where does rain water come from?",
    question_ta: "மழை நீர் எங்கிருந்து வருகிறது?",
    options: ["Rivers", "Clouds", "Ground", "Forest"],
    options_ta: ["ஆறுகள்", "மேகங்கள்", "தரை", "காடு"],
    answer: "Clouds",
    answer_ta: "மேகங்கள்",
    explanation: "Clouds store tiny droplets of water which fall to the ground as rain when they get heavy! 🌧️",
    explanation_ta: "மேகங்கள் சிறிய நீர் துளிகளைச் சேமித்து வைத்து, அவை கனமாகும்போது மழையாகப் பொழிகின்றன! 🌧️",
    classRange: [1, 2]
  },
  {
    title: "👃 Smelling Sense",
    title_ta: "👃 மோப்ப உணர்வு",
    question: "Which body part do we use to smell a flower?",
    question_ta: "பூவின் வாசனையை அறிய நாம் எந்த உடல் உறுப்பைப் பயன்படுத்துகிறோம்?",
    options: ["Eyes", "Ears", "Nose", "Mouth"],
    options_ta: ["கண்கள்", "காதுகள்", "மூக்கு", "வாய்"],
    answer: "Nose",
    answer_ta: "மூக்கு",
    explanation: "Our nose has special receptors that detect scents in the air! 👃",
    explanation_ta: "நமது மூக்கில் காற்றில் உள்ள வாசனைகளைக் கண்டறியும் சிறப்பு உணர்வுகள் உள்ளன! 👃",
    classRange: [1, 2]
  },
  {
    title: "❄️ Winter Clothes",
    title_ta: "❄️ குளிர் ஆடைகள்",
    question: "In which season do we wear warm woollen clothes?",
    question_ta: "எந்தக் காலத்தில் நாம் வெதுவெதுப்பான கம்பளி ஆடைகளை அணிகிறோம்?",
    options: ["Summer", "Winter", "Rainy", "Spring"],
    options_ta: ["கோடைகாலம்", "குளிர்காலம்", "மழைக்காலம்", "வசந்தகாலம்"],
    answer: "Winter",
    answer_ta: "குளிர்காலம்",
    explanation: "Woollen clothes trap our body heat to keep us warm during freezing winters! ❄️",
    explanation_ta: "கம்பளி ஆடைகள் நமது உடல் வெப்பத்தைத் தடுத்து வைத்துக் குளிர்ந்த குளிர்காலத்தில் நம்மை வெதுவெதுப்பாக வைத்திருக்கும்! ❄️",
    classRange: [1, 2]
  },
  {
    title: "☀️ Daytime Light",
    title_ta: "☀️ பகல் ஒளி",
    question: "What gives us light during the day?",
    question_ta: "பகலில் நமக்கு ஒளியைத் தருவது எது?",
    options: ["Moon", "Sun", "Stars", "Candle"],
    options_ta: ["நிலா", "சூரியன்", "நட்சத்திரங்கள்", "மெழுகுவர்த்தி"],
    answer: "Sun",
    answer_ta: "சூரியன்",
    explanation: "The Sun is a giant star that provides light and heat energy to our planet Earth! ☀️",
    explanation_ta: "சூரியன் ஒரு மாபெரும் நட்சத்திரமாகும், இது நமது பூமிக்கு ஒளியையும் வெப்பத்தையும் தருகிறது! ☀️",
    classRange: [1, 2]
  },
  {
    title: "🐸 Amphibian Life",
    title_ta: "🐸 இருவாழ்வி வாழ்க்கை",
    question: "Where does a frog live?",
    question_ta: "தவளை எங்கு வாழ்கிறது?",
    options: ["Only in desert", "Only in space", "Both land and water", "Only in trees"],
    options_ta: ["பாலைவனத்தில் மட்டும்", "விண்வெளியில் மட்டும்", "நிலம் மற்றும் நீர் இரண்டிலும்", "மரத்தில் மட்டும்"],
    answer: "Both land and water",
    answer_ta: "நிலம் மற்றும் நீர் இரண்டிலும்",
    explanation: "Frogs are amphibians, which means they can live comfortably on both land and in water! 🐸",
    explanation_ta: "தவளைகள் இருவாழ்விகள் ஆகும், அதாவது அவைகளால் நிலத்திலும் நீரிலும் எளிதாக வாழ முடியும்! 🐸",
    classRange: [1, 2]
  },
  {
    title: "🐟 Fish Breath",
    title_ta: "🐟 மீன் சுவாசம்",
    question: "How do fish breathe underwater?",
    question_ta: "மீன்கள் நீருக்கடியில் எவ்வாறு சுவாசிக்கின்றன?",
    options: ["Through nose", "Through gills", "Through skin", "Through mouth"],
    options_ta: ["மூக்கு வழியாக", "செவுள்கள் வழியாக", "தோல் வழியாக", "வாய் வழியாக"],
    answer: "Through gills",
    answer_ta: "செவுள்கள் வழியாக",
    explanation: "Fish use their gills to extract dissolved oxygen directly from the water! 🐟",
    explanation_ta: "மீன்கள் நீரில் கரைந்துள்ள ஆக்சிஜனைத் தங்கள் செவுள்கள் மூலமாக உறிஞ்சிச் சுவாசிக்கின்றன! 🐟",
    classRange: [1, 2]
  },
  {
    title: "🥛 Strong Bones",
    title_ta: "🥛 வலிமையான எலும்புகள்",
    question: "What mineral in milk makes our bones and teeth strong?",
    question_ta: "பாலில் உள்ள எந்தச் சத்து நமது எலும்புகள் மற்றும் பற்களை வலிமையாக்குகிறது?",
    options: ["Sugar", "Calcium", "Iron", "Salt"],
    options_ta: ["சர்க்கரை", "கால்சியம்", "இரும்பு", "உப்பு"],
    answer: "Calcium",
    answer_ta: "கால்சியம்",
    explanation: "Calcium is super important for building and maintaining strong, healthy bones and teeth! 🥛",
    explanation_ta: "வலிமையான, ஆரோக்கியமான எலும்புகள் மற்றும் பற்களை உருவாக்க கால்சியம் மிகவும் முக்கியமானது! 🥛",
    classRange: [1, 2]
  },
  {
    title: "🦆 Webbed Feet",
    title_ta: "🦆 சவ்வுப் பாதங்கள்",
    question: "What type of feet does a duck have to help it swim?",
    question_ta: "வாத்து நீரில் நீந்துவதற்கு எத்தகைய கால்களைக் கொண்டுள்ளது?",
    options: ["Sharp claws", "Webbed feet", "Long legs", "Hooves"],
    options_ta: ["கூர்மையான நகங்கள்", "சவ்வுப் பாதங்கள்", "நீளமான கால்கள்", "குளம்புகள்"],
    answer: "Webbed feet",
    answer_ta: "சவ்வுப் பாதங்கள்",
    explanation: "Ducks have webbed feet that act like paddles to push water and propel them forward! 🦆",
    explanation_ta: "வாத்துகளின் கால்களில் உள்ள சவ்வுகள் நீந்தும்போது தண்ணீரைத் தள்ளும் துடுப்புகள் போல் செயல்படுகின்றன! 🦆",
    classRange: [1, 2]
  },
  {
    title: "🌲 Leaf Pigment",
    title_ta: "🌲 இலை நிறமி",
    question: "What color are healthy leaves on most plants?",
    question_ta: "பெரும்பாலான தாவரங்களின் ஆரோக்கியமான இலைகள் என்ன நிறத்தில் இருக்கும்?",
    options: ["Red", "Blue", "Green", "Purple"],
    options_ta: ["சிவப்பு", "நீலம்", "பச்சை", "ஊதா"],
    answer: "Green",
    answer_ta: "பச்சை",
    explanation: "Leaves are green because of a pigment called chlorophyll, which helps plants trap sunlight! 🍃",
    explanation_ta: "இலைகளில் உள்ள பச்சையம் (குளோரோபில்) என்ற நிறமி தாவரங்கள் சூரிய ஒளியைப் பெற உதவுகிறது! 🍃",
    classRange: [1, 2]
  },
  {
    title: "🦋 Insect Traits",
    title_ta: "🦋 பூச்சி பண்புகள்",
    question: "How many legs do adult insects have?",
    question_ta: "முதிர்ந்த பூச்சிகளுக்கு எத்தனை கால்கள் இருக்கும்?",
    options: ["4", "6", "8", "2"],
    options_ta: ["4", "6", "8", "2"],
    answer: "6",
    answer_ta: "6",
    explanation: "All insects have exactly six legs, a body divided into three parts, and antennae! 🐜",
    explanation_ta: "அனைத்து பூச்சிகளுக்கும் ஆறு கால்களும், மூன்று உடல் பகுதிகளும், உணர் கொம்புகளும் இருக்கும்! 🐜",
    classRange: [1, 2]
  },
  {
    title: "🧊 Ice State",
    title_ta: "🧊 பனிக்கட்டி நிலை",
    question: "What does liquid water turn into when you freeze it?",
    question_ta: "திரவ நீர் உறையும் போது என்னவாக மாறுகிறது?",
    options: ["Steam", "Ice", "Stone", "Dust"],
    options_ta: ["நீராவி", "பனிக்கட்டி", "கல்", "தூசி"],
    answer: "Ice",
    answer_ta: "பனிக்கட்டி",
    explanation: "Freezing water cools it down below 0°C, turning it from a liquid to solid ice! 🧊",
    explanation_ta: "தண்ணீரை 0°C-க்கு கீழ் குளிர்விக்கும்போது அது திரவ நிலையிலிருந்து திடமான பனிக்கட்டியாக மாறுகிறது! 🧊",
    classRange: [1, 2]
  },
  {
    title: "🦘 Pouch Bearers",
    title_ta: "🦘 பைப்பாலூட்டிகள்",
    question: "Which animal carries its baby safely in a pouch?",
    question_ta: "தன் குட்டியைப் பையில் பாதுகாப்பாகச் சுமந்து செல்லும் விலங்கு எது?",
    options: ["Kangaroo", "Monkey", "Koala", "Panda"],
    options_ta: ["கங்காரு", "குரங்கு", "கோலா", "பாண்டா"],
    answer: "Kangaroo",
    answer_ta: "கங்காரு",
    explanation: "Female kangaroos have a special pouch on their bellies to protect and feed their tiny babies! 🦘",
    explanation_ta: "பெண் கங்காருகளின் வயிற்றில் உள்ள பையில் தங்களது சிறிய குட்டிகளைப் பாதுகாப்பாக வைத்துப் பாலூட்டுகின்றன! 🦘",
    classRange: [1, 2]
  },

  // Grade 3-4 (classRange: [3, 4])
  {
    title: "🪐 Solar System",
    title_ta: "🪐 சூரிய குடும்பம்",
    question: "Which planet is known as the Morning Star?",
    question_ta: "விடிவெள்ளி என்று அழைக்கப்படும் கிரகம் எது?",
    options: ["Mars", "Venus", "Jupiter", "Mercury"],
    options_ta: ["செவ்வாய்", "வெள்ளி", "வியாழன்", "புதன்"],
    answer: "Venus",
    answer_ta: "வெள்ளி",
    explanation: "Venus is the brightest planet in the night sky and can be seen in the early morning! 🪐",
    explanation_ta: "வெள்ளி கிரகம் இரவு வானில் மிகவும் பிரகாசமானதாகும், இதனை அதிகாலையிலும் வெறும் கண்ணால் பார்க்கலாம்! 🪐",
    classRange: [3, 4]
  },
  {
    title: "🧲 Magnetic Force",
    title_ta: "🧲 காந்த விசை",
    question: "What happens when two identical poles of magnets face each other?",
    question_ta: "ஒரே மாதிரியான காந்த துருவங்கள் ஒன்றை ஒன்று நோக்கும்போது என்ன நடக்கும்?",
    options: ["They attract", "They repel", "They heat up", "Nothing"],
    options_ta: ["அவை ஈர்க்கும்", "அவை விலக்கும்", "அவை சூடாகும்", "ஒன்றும் நடக்காது"],
    answer: "They repel",
    answer_ta: "அவை விலக்கும்",
    explanation: "Opposite poles attract, but similar poles (North-North or South-South) repel and push away! 🧲",
    explanation_ta: "எதிர் துருவங்கள் ஈர்க்கும், ஆனால் ஒரே மாதிரியான துருவங்கள் (வடக்கு-வடக்கு) ஒன்றை ஒன்று விலக்குகின்றன! 🧲",
    classRange: [3, 4]
  },
  {
    title: "💧 Cloud Rain",
    title_ta: "💧 மேக மழை",
    question: "What is it called when water falls from clouds as rain or snow?",
    question_ta: "மேகங்களில் இருந்து மழை அல்லது பனி பொழிவது எவ்வாறு அழைக்கப்படுகிறது?",
    options: ["Evaporation", "Condensation", "Precipitation", "Transpiration"],
    options_ta: ["ஆவியாதல்", "ஒடுக்கம்", "மழைப்பொழிவு", "நீராவிப்போக்கு"],
    answer: "Precipitation",
    answer_ta: "மழைப்பொழிவு",
    explanation: "Precipitation is any form of water (rain, snow, hail) that falls from the atmosphere to Earth! 🌧️",
    explanation_ta: "மழைப்பொழிவு என்பது மேகங்களிலிருந்து தரைக்கு விழும் மழை, பனி அல்லது ஆலங்கட்டி போன்ற நீர் வடிவங்கள் ஆகும்! 🌧️",
    classRange: [3, 4]
  },
  {
    title: "☀️ Food Chain Energy",
    title_ta: "☀️ உணவுச்சங்கிலி ஆற்றல்",
    question: "What is the primary source of energy in a food chain?",
    question_ta: "உணவுச் சங்கிலியில் ஆற்றலின் முதன்மை ஆதாரம் எது?",
    options: ["Water", "Plants", "The Sun", "Soil"],
    options_ta: ["தண்ணீர்", "தாவரங்கள்", "சூரியன்", "மண்"],
    answer: "The Sun",
    answer_ta: "சூரியன்",
    explanation: "The Sun provides light energy that producers (plants) use to make food for all living things! ☀️",
    explanation_ta: "சூரியன் வழங்கும் ஒளியாற்றலைக் கொண்டு தாவரங்கள் தங்களுக்குத் தேவையான உணவைத் தயாரித்துக் கொள்கின்றன! ☀️",
    classRange: [3, 4]
  },
  {
    title: "🪨 Lava Rock",
    title_ta: "🪨 எரிமலைப் பாறை",
    question: "What type of rock is formed from cooled magma or lava?",
    question_ta: "குளிர்ந்த எரிமலைக்குழம்பு (மாக்மா) உறைந்து உருவாகும் பாறை எது?",
    options: ["Sedimentary", "Metamorphic", "Igneous", "Sandstone"],
    options_ta: ["படிவுப் பாறை", "உருமாறிய பாறை", "தீப்பாறை", "மணற்பாறை"],
    answer: "Igneous",
    answer_ta: "தீப்பாறை",
    explanation: "Igneous rocks, like basalt and granite, form when hot molten rock cools and solidifies! 🌋",
    explanation_ta: "சூடான எரிமலைக்குழம்பு குளிர்ந்து இறுகும்போது தீப்பாறைகள் (உதாரணம்: கிரானைட்) உருவாகின்றன! 🌋",
    classRange: [3, 4]
  },
  {
    title: "⚙️ Ramp Magic",
    title_ta: "⚙️ சாய்வுதளம்",
    question: "Which simple machine is a flat surface tilted at an angle?",
    question_ta: "ஒரு குறிப்பிட்ட கோணத்தில் சாய்ந்த தட்டையான மேற்பரப்பு கொண்ட எளிய இயந்திரம் எது?",
    options: ["Pulley", "Lever", "Inclined plane", "Screw"],
    options_ta: ["கப்பி", "நெம்புகோல்", "சாய்வுதளம்", "திருகு"],
    answer: "Inclined plane",
    answer_ta: "சாய்வுதளம்",
    explanation: "An inclined plane (like a slide or ramp) makes lifting heavy objects much easier! 📐",
    explanation_ta: "சாய்வுதளம் என்பது கனமான பொருட்களை மேலே கொண்டு செல்வதை மிகவும் எளிதாக்கும் எளிய இயந்திரமாகும்! 📐",
    classRange: [3, 4]
  },
  {
    title: "🌱 Gas Release",
    title_ta: "🌱 வாயு வெளியீடு",
    question: "What gas do plants release during photosynthesis?",
    question_ta: "ஒளிச்சேர்க்கையின் போது தாவரங்கள் வெளியிடும் வாயு எது?",
    options: ["Carbon Dioxide", "Oxygen", "Nitrogen", "Hydrogen"],
    options_ta: ["கார்பன் டை ஆக்சைடு", "ஆக்சிஜன்", "நைட்ரஜன்", "ஹைட்ரஜன்"],
    answer: "Oxygen",
    answer_ta: "ஆக்சிஜன்",
    explanation: "Plants take in Carbon Dioxide and water, and use sunlight to make food and release Oxygen! 🍃",
    explanation_ta: "தாவரங்கள் கார்பன் டை ஆக்சைடை எடுத்துக்கொண்டு, ஒளிச்சேர்க்கை மூலம் உணவைத் தயாரித்து ஆக்சிஜனை வெளியிடுகின்றன! 🍃",
    classRange: [3, 4]
  },
  {
    title: "🌡️ States of Matter",
    title_ta: "🌡️ பருப்பொருள் நிலைகள்",
    question: "What state of matter has a fixed volume but takes the shape of its container?",
    question_ta: "குறிப்பிட்ட பருமனைப் பெற்றிருந்தாலும், கொள்கலனின் வடிவத்தைப் பெறும் பருப்பொருள் நிலை எது?",
    options: ["Solid", "Liquid", "Gas", "Plasma"],
    options_ta: ["திடப்பொருள்", "திரவப்பொருள்", "வாயுப்பொருள்", "பிளாஸ்மா"],
    answer: "Liquid",
    answer_ta: "திரவப்பொருள்",
    explanation: "Liquids can flow and take the shape of any glass or bowl they are poured in! 💧",
    explanation_ta: "திரவங்களுக்கு நிலையான வடிவம் கிடையாது, அவை ஊற்றப்படும் பாத்திரத்தின் வடிவத்தைப் பெறுகின்றன! 💧",
    classRange: [3, 4]
  },
  {
    title: "🐝 Flower Friends",
    title_ta: "🐝 மலர் நண்பர்கள்",
    question: "Which insect is a key pollinator of crops and wild flowers?",
    question_ta: "மலர்களின் மகரந்தச் சேர்க்கைக்கு உதவும் முக்கிய பூச்சி எது?",
    options: ["Honeybee", "Mosquito", "Ant", "Housefly"],
    options_ta: ["தேனீ", "கொசு", "எறும்பு", "ஈ"],
    answer: "Honeybee",
    answer_ta: "தேனீ",
    explanation: "Honeybees transfer pollen grains from one flower to another, helping plants make fruits and seeds! 🐝",
    explanation_ta: "தேனீக்கள் தேனைச் சேகரிக்கும் போது மகரந்தங்களை மலர்களுக்கு இடையே கடத்தி இனப்பெருக்கத்திற்கு உதவுகின்றன! 🐝",
    classRange: [3, 4]
  },
  {
    title: "🌱 Root Functions",
    title_ta: "🌱 வேரின் செயல்பாடுகள்",
    question: "What is the main function of plant roots in the soil?",
    question_ta: "மண்ணில் உள்ள தாவர வேர்களின் முக்கிய செயல்பாடு என்ன?",
    options: ["To make seeds", "To absorb water", "To perform photosynthesis", "To attract insects"],
    options_ta: ["விதைகளை உருவாக்க", "நீரை உறிஞ்ச", "ஒளிச்சேர்க்கை செய்ய", "பூச்சிகளை ஈர்க்க"],
    answer: "To absorb water",
    answer_ta: "நீரை உறிஞ்ச",
    explanation: "Roots anchor the plant firmly in the ground and absorb water and dissolved minerals! 🌾",
    explanation_ta: "வேர்கள் தாவரங்களை மண்ணில் நிலைநிறுத்துவதோடு, நீர் மற்றும் கனிமச் சத்துக்களை உறிஞ்சுகின்றன! 🌾",
    classRange: [3, 4]
  },
  {
    title: "🦅 Lightweight Bones",
    title_ta: "🦅 இலகுவான எலும்புகள்",
    question: "Why are bird bones light enough to help them fly?",
    question_ta: "பறவைகளின் எலும்புகள் ஏன் பறப்பதற்கு ஏற்றவாறு எடை குறைவாக உள்ளன?",
    options: ["They are hollow", "They are made of wood", "They have no calcium", "They are soft"],
    options_ta: ["அவை வெற்று எலும்புகள்", "அவை மரத்தால் ஆனவை", "அவற்றில் கால்சியம் இல்லை", "அவை மென்மையானவை"],
    answer: "They are hollow",
    answer_ta: "அவை வெற்று எலும்புகள்",
    explanation: "Bird bones are hollow with air pockets, which keeps them lightweight yet strong for flight! 🦅",
    explanation_ta: "பறவைகளின் எலும்புகள் உள்ளே காற்றறைகளுடன் வெற்று அமைப்பாக உள்ளதால் பறக்க எளிதாக அமைகிறது! 🦅",
    classRange: [3, 4]
  },
  {
    title: "☁️ Fluffy Clouds",
    title_ta: "☁️ திரள் மேகங்கள்",
    question: "Which clouds are puffy, white, and look like cotton candy?",
    question_ta: "வெண்மையாகப் பஞ்சுப் பொதிகள் போல் தோற்றமளிக்கும் மேகங்கள் எவை?",
    options: ["Cumulus", "Stratus", "Cirrus", "Nimbus"],
    options_ta: ["திரள் மேகங்கள்", "படை மேகங்கள்", "கீற்று மேகங்கள்", "கார் மேகங்கள்"],
    answer: "Cumulus",
    answer_ta: "திரள் மேகங்கள்",
    explanation: "Cumulus clouds are beautiful, fluffy clouds that indicate fine weather! ☁️",
    explanation_ta: "திரள் மேகங்கள் பஞ்சு போன்ற தோற்றத்தில் நல்ல வெயில் காலங்களில் காணப்படும் மேகங்கள் ஆகும்! ☁️",
    classRange: [3, 4]
  },
  {
    title: "🦷 Tooth Defender",
    title_ta: "🦷 பல் காப்பான்",
    question: "Which mineral is added to toothpaste to protect our teeth from decay?",
    question_ta: "பற்களை சொத்தையாவதிலிருந்து பாதுகாக்க பற்பசையில் சேர்க்கப்படும் தாது எது?",
    options: ["Iron", "Fluoride", "Zinc", "Copper"],
    options_ta: ["இரும்பு", "புளோரைடு", "துத்தநாகம்", "செம்பு"],
    answer: "Fluoride",
    answer_ta: "புளோரைடு",
    explanation: "Fluoride bonds with tooth enamel to make it stronger and highly resistant to acids! 🪥",
    explanation_ta: "புளோரைடு எனாமலை வலுப்படுத்தி, உணவிலுள்ள அமிலங்களினால் பற்கள் சொத்தையாவதைத் தடுக்கிறது! 🪥",
    classRange: [3, 4]
  },
  {
    title: "🍄 Nature's Cleaners",
    title_ta: "🍄 இயற்கை தூய்மைப் பணியாளர்கள்",
    question: "Which of these is a decomposer that cleans up dead materials?",
    question_ta: "இறந்த கழிவுகளை மக்கச்செய்து இயற்கை சுத்திகரிப்பாளராகச் செயல்படுவது எது?",
    options: ["Mushroom", "Green plant", "Lion", "Rabbit"],
    options_ta: ["காளான்", "பச்சைத் தாவரம்", "சிங்கம்", "முயல்"],
    answer: "Mushroom",
    answer_ta: "காளான்",
    explanation: "Fungi like mushrooms digest dead wood and leaves, returning useful nutrients to the soil! 🍄",
    explanation_ta: "காளான்கள் போன்ற பூஞ்சைகள் இறந்த தாவரங்களைச் சிதைத்து மண்ணுக்கு மீண்டும் சத்துக்களைக் கொண்டு சேர்க்கின்றன! 🍄",
    classRange: [3, 4]
  },
  {
    title: "💧 Clean Water",
    title_ta: "💧 சுத்தமான நீர்",
    question: "Which process uses a barrier to separate solid dirt from water?",
    question_ta: "நீரில் உள்ள திடக் கழிவுகளை வடிகட்டும் முறை மூலம் பிரிப்பது எது?",
    options: ["Evaporation", "Filtration", "Condensation", "Dissolving"],
    options_ta: ["ஆவியாதல்", "வடிகட்டுதல்", "ஒடுக்கம்", "கரைத்தல்"],
    answer: "Filtration",
    answer_ta: "வடிகட்டுதல்",
    explanation: "Filtration uses a porous filter to catch dirt while allowing clean liquid to pass through! 🚰",
    explanation_ta: "வடிகட்டுதல் முறையில் திடக் கழிவுகள் வடிகட்டியினால் தடுத்து நிறுத்தப்பட்டு தூய நீர் பிரித்தெடுக்கப்படுகிறது! 🚰",
    classRange: [3, 4]
  },

  // Grade 5-6 (classRange: [5, 6])
  {
    title: "🫁 Breathing Organs",
    title_ta: "🫁 சுவாச உறுப்புகள்",
    question: "What is the main organ of the human respiratory system?",
    question_ta: "மனித சுவாச மண்டலத்தின் மிக முக்கிய உறுப்பு எது?",
    options: ["Heart", "Stomach", "Lungs", "Kidneys"],
    options_ta: ["இதயம்", "வயிறு", "நுரையீரல்", "சிறுநீரகங்கள்"],
    answer: "Lungs",
    answer_ta: "நுரையீரல்",
    explanation: "Lungs inhale oxygen from the air and transfer it into the blood while expelling carbon dioxide! 🫁",
    explanation_ta: "நுரையீரல்கள் காற்றில் உள்ள ஆக்சிஜனை இரத்தத்திற்கு மாற்றி, கார்பன் டை ஆக்சைடை வெளியேற்றுகின்றன! 🫁",
    classRange: [5, 6]
  },
  {
    title: "💡 Electric Path",
    title_ta: "💡 மின்சாரப்பாதை",
    question: "What material allows electricity to flow easily in a circuit?",
    question_ta: "மின்சுற்றில் மின்சாரத்தை எளிதாகக் கடத்தக்கூடிய பொருள் எது?",
    options: ["Conductor", "Insulator", "Wood", "Rubber"],
    options_ta: ["மின் கடத்தி", "மின்காப்புப் பொருள்", "மரம்", "ரப்பர்"],
    answer: "Conductor",
    answer_ta: "மின் கடத்தி",
    explanation: "Conductors, like copper and aluminum, have free electrons that carry electric current easily! ⚡",
    explanation_ta: "செம்பு போன்ற மின் கடத்திகள் தங்களில் மின்சாரத்தை எளிதாகப் பாய அனுமதிக்கின்றன! ⚡",
    classRange: [5, 6]
  },
  {
    title: "👁️ Light Travel",
    title_ta: "👁️ ஒளிப்பயணம்",
    question: "How does light travel in space?",
    question_ta: "விண்வெளியில் ஒளி எவ்வாறு பயணிக்கிறது?",
    options: ["In curved lines", "In straight lines", "In circles", "It does not travel"],
    options_ta: ["வளைந்த கோடுகளில்", "நேர்கோட்டில்", "வட்ட வடிவில்", "அது பயணிப்பதில்லை"],
    answer: "In straight lines",
    answer_ta: "நேர்கோட்டில்",
    explanation: "Light travels in straight lines called rays, which is why shadows are formed behind blocked paths! 🕯️",
    explanation_ta: "ஒளி எப்போதும் நேர்கோட்டில் செல்லும், இதன் காரணமாகவே ஒளி தடுக்கப்படும் இடத்தில் நிழல் உருவாகிறது! 🕯️",
    classRange: [5, 6]
  },
  {
    title: "🧠 Balance Control",
    title_ta: "🧠 சமநிலைக் கட்டுப்பாடு",
    question: "Which part of the brain controls body balance and coordination?",
    question_ta: "உடலின் சமநிலையையும் தசை இயக்கங்களையும் கட்டுப்படுத்தும் மூளையின் பகுதி எது?",
    options: ["Cerebrum", "Cerebellum", "Brainstem", "Spinal cord"],
    options_ta: ["பெருமூளை", "சிறுமூளை", "தண்டுவடம்", "முதுகுத்தண்டு"],
    answer: "Cerebellum",
    answer_ta: "சிறுமூளை",
    explanation: "The cerebellum, located at the back of the brain, coordinates movements and balance! 🧠",
    explanation_ta: "மூளையின் பின்புறமுள்ள சிறுமூளை உடலின் தசை ஒருங்கிணைப்பிற்கும் சமநிலைக்கும் காரணமாகிறது! 🧠",
    classRange: [5, 6]
  },
  {
    title: "💨 Evaporation Rate",
    title_ta: "💨 ஆவியாதல் வேகம்",
    question: "Which conditions increase the rate of water evaporation?",
    question_ta: "நீரின் ஆவியாதல் வீதத்தை அதிகரிக்கும் காரணிகள் எவை?",
    options: ["High humidity", "Cool temperature", "Strong wind and heat", "Covering the container"],
    options_ta: ["அதிக ஈரப்பதம்", "குறைந்த வெப்பநிலை", "பலத்த காற்று மற்றும் வெப்பம்", "கொள்கலனை மூடி வைப்பது"],
    answer: "Strong wind and heat",
    answer_ta: "பலத்த காற்று மற்றும் வெப்பம்",
    explanation: "Higher temperatures and wind help water molecules break free into vapor much quicker! 💨",
    explanation_ta: "அதிக வெப்பமும் காற்று வேகமும் நீர் மூலக்கூறுகள் வேகமாக நீராவியாக மாற உதவுகின்றன! 💨",
    classRange: [5, 6]
  },
  {
    title: "🌿 Plant Cell Wall",
    title_ta: "🌿 தாவர செல் சுவர்",
    question: "Which structure is present in plant cells but absent in animal cells?",
    question_ta: "தாவர செல்லில் மட்டும் உள்ள ஆனால் விலங்கு செல்லில் இல்லாத உறுப்பு எது?",
    options: ["Cell membrane", "Nucleus", "Cell wall", "Cytoplasm"],
    options_ta: ["செல் சவ்வு", "உட்கரு", "செல் சுவர்", "சைட்டோபிளாசம்"],
    answer: "Cell wall",
    answer_ta: "செல் சுவர்",
    explanation: "Plant cells have a tough outer cellulose cell wall that gives them their shape and rigid structure! 🌿",
    explanation_ta: "தாவர செல்களுக்குச் செல் சுவர் கூடுதல் வலிமையையும் நிலையான வடிவத்தையும் வழங்குகிறது! 🌿",
    classRange: [5, 6]
  },
  {
    title: "🦴 Shoulder Joint",
    title_ta: "🦴 தோள்பட்டை மூட்டு",
    question: "What type of joint is present in the human shoulder?",
    question_ta: "மனித தோள்பட்டையில் உள்ள மூட்டு எந்த வகையைச் சேர்ந்தது?",
    options: ["Hinge joint", "Ball and socket joint", "Pivot joint", "Fixed joint"],
    options_ta: ["கீழ் மூட்டு", "பந்து கிண்ண மூட்டு", "முளை மூட்டு", "நிலையான மூட்டு"],
    answer: "Ball and socket joint",
    answer_ta: "பந்து கிண்ண மூட்டு",
    explanation: "The ball and socket joint allows rotation and movement in almost every direction! 🦴",
    explanation_ta: "பந்து கிண்ண மூட்டே கைகளை எல்லா திசைகளிலும் சுழற்றி இயக்க அனுமதிக்கிறது! 🦴",
    classRange: [5, 6]
  },
  {
    title: "🌧️ Dangerous Rain",
    title_ta: "🌧️ அமில மழை",
    question: "Which gases react with atmospheric moisture to form acid rain?",
    question_ta: "வளிமண்டல நீருடன் வினைபுரிந்து அமில மழையைத் தோற்றுவிக்கும் வாயுக்கள் எவை?",
    options: ["Oxygen and Nitrogen", "Sulfur Dioxide and Nitrogen Oxides", "Helium and Hydrogen", "Carbon Dioxide only"],
    options_ta: ["ஆக்சிஜன் மற்றும் நைட்ரஜன்", "சல்பர் டை ஆக்சைடு மற்றும் நைட்ரஜன் ஆக்சைடுகள்", "ஹீலியம் மற்றும் ஹைட்ரஜன்", "கார்பன் டை ஆக்சைடு மட்டும்"],
    answer: "Sulfur Dioxide and Nitrogen Oxides",
    answer_ta: "சல்பர் டை ஆக்சைடு மற்றும் நைட்ரஜன் ஆக்சைடுகள்",
    explanation: "Burning fossil fuels releases sulfur and nitrogen gases, which form sulfuric and nitric acids in rain! 🏭",
    explanation_ta: "எரிபொருட்களை எரிப்பதால் வெளியாகும் சல்பர் மற்றும் நைட்ரஜன் வாயுக்கள் மழையை அமிலத்தன்மை கொண்டதாக மாற்றுகின்றன! 🏭",
    classRange: [5, 6]
  },
  {
    title: "☀️ Solar Eclipse",
    title_ta: "☀️ சூரிய கிரகணம்",
    question: "Which celestial body aligns in the middle during a solar eclipse?",
    question_ta: "சூரிய கிரகணத்தின் போது எந்த விண்பொருள் நடுவில் அமைகிறது?",
    options: ["Mars", "The Moon", "Venus", "Jupiter"],
    options_ta: ["செவ்வாய்", "சந்திரன்", "வெள்ளி", "வியாழன்"],
    answer: "The Moon",
    answer_ta: "சந்திரன்",
    explanation: "During a solar eclipse, the Moon passes directly between the Sun and Earth, blocking sunlight! 🌑",
    explanation_ta: "சூரிய கிரகணத்தின் போது சந்திரன் பூமிக்கும் சூரியனுக்கும் இடையே வந்து சூரிய ஒளியை மறைக்கிறது! 🌑",
    classRange: [5, 6]
  },
  {
    title: "🍎 Food Absorption",
    title_ta: "🍎 ஊட்டச்சத்து உறிஞ்சுதல்",
    question: "Where does most nutrient absorption happen in the human digestive system?",
    question_ta: "மனித செரிமான மண்டலத்தில் பெரும்பாலான சத்துக்கள் எங்கு உறிஞ்சப்படுகின்றன?",
    options: ["Stomach", "Small Intestine", "Large Intestine", "Esophagus"],
    options_ta: ["வயிறு", "சிறுகுடல்", "பெருங்குடல்", "உணவுக்குழாய்"],
    answer: "Small Intestine",
    answer_ta: "சிறுகுடல்",
    explanation: "The small intestine's inner walls are lined with tiny finger-like villi that absorb nutrients into the blood! 🩸",
    explanation_ta: "சிறுகுடலில் உள்ள சிறிய உறிஞ்சிகள் (வில்லி) செரிமானமடைந்த சத்துக்களை இரத்தத்தில் சேர்க்கின்றன! 🩸",
    classRange: [5, 6]
  },
  {
    title: "🧪 State Leap",
    title_ta: "🧪 பதங்கமாதல்",
    question: "What is the process of a solid turning directly into gas without melting?",
    question_ta: "ஒரு திடப்பொருள் திரவமாக மாறாமல் நேரடியாக வாயுவாக மாறும் நிகழ்வு எது?",
    options: ["Melting", "Sublimation", "Evaporation", "Freezing"],
    options_ta: ["உருகுதல்", "பதங்கமாதல்", "ஆவியாதல்", "உறைதல்"],
    answer: "Sublimation",
    answer_ta: "பதங்கமாதல்",
    explanation: "Sublimation occurs in substances like dry ice or camphor, skipping the liquid phase entirely! ⚗️",
    explanation_ta: "கற்பூரம் அல்லது உலர் பனிக்கட்டி போன்ற பொருட்கள் உருகாமல் நேரடியாக ஆவியாவது பதங்கமாதல் எனப்படும்! ⚗️",
    classRange: [5, 6]
  },
  {
    title: "🔊 Speed of Sound",
    title_ta: "🔊 ஒலியின் வேகம்",
    question: "Through which medium does sound travel the fastest?",
    question_ta: "ஒலி எந்த ஊடகத்தின் வழியாக மிக வேகமாகப் பயணிக்கிறது?",
    options: ["Air", "Water", "Solid (Iron)", "Vacuum"],
    options_ta: ["காற்று", "நீர்", "திடப்பொருள் (இரும்பு)", "வெற்றிடம்"],
    answer: "Solid (Iron)",
    answer_ta: "திடப்பொருள் (இரும்பு)",
    explanation: "Sound travels fastest in solids because the molecules are packed closely together, transmitting vibrations faster! 🔊",
    explanation_ta: "திடப்பொருட்களின் துகள்கள் மிகவும் நெருக்கமாக இருப்பதால் அதிர்வு அலைகள் மிக வேகமாகப் பரவுகின்றன! 🔊",
    classRange: [5, 6]
  },
  {
    title: "🦟 Malaria Carrier",
    title_ta: "🦟 மலேரியா பரப்பி",
    question: "Which insect is responsible for transmitting the malaria parasite to humans?",
    question_ta: "மலேரியா காய்ச்சலை மனிதர்களுக்குப் பரப்பும் காரணி எது?",
    options: ["Housefly", "Male Anopheles mosquito", "Female Anopheles mosquito", "Aedes mosquito"],
    options_ta: ["ஈ", "ஆண் அனாபிலிஸ் கொசு", "பெண் அனாபிலிஸ் கொசு", "ஏடிஸ் கொசு"],
    answer: "Female Anopheles mosquito",
    answer_ta: "பெண் அனாபிலிஸ் கொசு",
    explanation: "Female Anopheles mosquitoes carry the microscopic Plasmodium parasite and infect humans when they bite! 🦟",
    explanation_ta: "பெண் அனாபிலிஸ் கொசுக்கள் பிளாஸ்மோடியம் ஒட்டுண்ணியைத் தங்களின் உமிழ்நீர் மூலம் மனிதர்களுக்குப் பரப்புகின்றன! 🦟",
    classRange: [5, 6]
  },
  {
    title: "🌲 Leaf Pores",
    title_ta: "🌲 இலைத்துளைகள்",
    question: "What are the microscopic pores on the surface of leaves called?",
    question_ta: "இலைகளின் மேற்பரப்பில் காணப்படும் நுண்துளைகள் எவ்வாறு அழைக்கப்படுகின்றன?",
    options: ["Roots", "Stomata", "Vessels", "Fibers"],
    options_ta: ["வேர்கள்", "இலைத்துளைகள் (ஸ்டோமாட்டா)", "நாளங்கள்", "நார்கள்"],
    answer: "Stomata",
    answer_ta: "இலைத்துளைகள் (ஸ்டோமாட்டா)",
    explanation: "Stomata open and close to allow gas exchange (CO2 and O2) and control water loss through transpiration! 🍃",
    explanation_ta: "இலைத்துளைகள் ஒளிச்சேர்க்கைக்குத் தேவையான கார்பன் டை ஆக்சைடை உறிஞ்சவும் நீராவியை வெளியேற்றவும் உதவுகின்றன! 🍃",
    classRange: [5, 6]
  },
  {
    title: "🧪 Neutral pH",
    title_ta: "🧪 நடுநிலை pH",
    question: "A substance with a pH value of exactly 7 is considered...",
    question_ta: "சரியாக 7 pH மதிப்பு கொண்ட ஒரு பொருள் எவ்வாறு கருதப்படுகிறது?",
    options: ["Acidic", "Basic", "Neutral", "Corrosive"],
    options_ta: ["அமிலம்", "காரம்", "நடுநிலை", "அரிக்கும் தன்மை"],
    answer: "Neutral",
    answer_ta: "நடுநிலை",
    explanation: "Pure water has a pH of 7, which means it is completely neutral — neither acidic nor basic! 💧",
    explanation_ta: "தூய நீரின் pH 7 ஆகும். இது அமிலத்தன்மையும் காரத்தன்மையும் அற்ற நடுநிலையானது! 💧",
    classRange: [5, 6]
  },

  // Grade 7-8 (classRange: [7, 8])
  {
    title: "🧪 Highly Reactive Metal",
    title_ta: "🧪 வினைத்திறன் மிக்க உலோகம்",
    question: "Which metal is stored in kerosene due to its extreme reactivity with air and water?",
    question_ta: "காற்றோடும் நீரோடும் மிக எளிதாக வினைபுரிவதால் மண்ணெண்ணெயில் வைக்கப்படும் உலோகம் எது?",
    options: ["Gold", "Sodium", "Iron", "Copper"],
    options_ta: ["தங்கம்", "சோடியம்", "இரும்பு", "செம்பு"],
    answer: "Sodium",
    answer_ta: "சோடியம்",
    explanation: "Sodium reacts violently with moisture in the air and water, so it must be stored under oil! 🧪",
    explanation_ta: "சோடியம் காற்று மற்றும் நீருடன் மிக வேகமாக வினைபுரிந்து வெடிப்பதால் மண்ணெண்ணெயில் பாதுகாக்கப்படுகிறது! 🧪",
    classRange: [7, 8]
  },
  {
    title: "🚀 First Law of Motion",
    title_ta: "🚀 முதல் இயக்க விதி",
    question: "Which Newton's law is also referred to as the Law of Inertia?",
    question_ta: "நியூட்டனின் எந்த இயக்க விதி 'நிலைம விதி' என்று அழைக்கப்படுகிறது?",
    options: ["First Law of Motion", "Second Law of Motion", "Third Law of Motion", "Law of Gravitation"],
    options_ta: ["முதல் இயக்க விதி", "இரண்டாம் இயக்க விதி", "மூன்றாம் இயக்க விதி", "ஈர்ப்பு விதி"],
    answer: "First Law of Motion",
    answer_ta: "முதல் இயக்க விதி",
    explanation: "Newton's First Law states that objects resist changes to their state of motion, which is called inertia! 🚀",
    explanation_ta: "ஒரு பொருள் அதன் ஓய்வு நிலையையோ அல்லது சீரான இயக்க நிலையையோ மாற்றிக்கொள்வதை எதிர்க்கும் பண்பே நிலைமம் ஆகும்! 🚀",
    classRange: [7, 8]
  },
  {
    title: "🧬 Genetics Founder",
    title_ta: "🧬 மரபியல் தந்தை",
    question: "Who is widely recognized as the Father of Genetics?",
    question_ta: "மரபியலின் தந்தை என்று உலகளவில் அங்கீகரிக்கப்பட்டவர் யார்?",
    options: ["Charles Darwin", "Gregor Mendel", "Louis Pasteur", "Francis Crick"],
    options_ta: ["சார்லஸ் டார்வின்", "கிரிகோர் மெண்டல்", "லூயிஸ் பாஸ்டர்", "பிரான்சிஸ் கிரிக்"],
    answer: "Gregor Mendel",
    answer_ta: "கிரிகோர் மெண்டல்",
    explanation: "Gregor Mendel discovered the laws of inheritance through his detailed experiments with pea plants! 🧬",
    explanation_ta: "கிரிகோர் மெண்டல் பட்டாணி தாவரங்களை ஆராய்ந்து மரபுக் கூறுகள் கடத்தப்படும் விதிகளைக் கண்டறிந்தார்! 🧬",
    classRange: [7, 8]
  },
  {
    title: "⚗️ Acid-Base Reaction",
    title_ta: "⚗️ நடுநிலையாக்கல் வினை",
    question: "What is the chemical reaction between an acid and a base called?",
    question_ta: "அமிலமும் காரமும் வினைபுரிந்து உப்பையும் நீரையும் தரும் வினை எது?",
    options: ["Oxidation", "Reduction", "Neutralization", "Hydrolysis"],
    options_ta: ["ஆக்ஸிஜனேற்றம்", "ஒடுக்கம்", "நடுநிலையாக்கல் வினை", "நீராற்பகுப்பு"],
    answer: "Neutralization",
    answer_ta: "நடுநிலையாக்கல் வினை",
    explanation: "Acid and base cancel each other out in a neutralization reaction to form salt and water! 🧪",
    explanation_ta: "அமிலமும் காரமும் தங்களின் குணங்களை இழந்து நடுநிலையாகி உப்பையும் நீரையும் உருவாக்குகின்றன! 🧪",
    classRange: [7, 8]
  },
  {
    title: "⚛️ Nucleus Parts",
    title_ta: "⚛️ உட்கரு துகள்கள்",
    question: "Which subatomic particles are located inside the nucleus of an atom?",
    question_ta: "அணுவின் உட்கருவினுள் காணப்படும் அடிப்படைத் துகள்கள் எவை?",
    options: ["Electrons and Protons", "Protons and Neutrons", "Electrons and Neutrons", "Electrons only"],
    options_ta: ["எலக்ட்ரான்கள் மற்றும் புரோட்டான்கள்", "புரோட்டான்கள் மற்றும் நியூட்ரான்கள்", "எலக்ட்ரான்கள் மற்றும் நியூட்ரான்கள்", "எலக்ட்ரான்கள் மட்டும்"],
    answer: "Protons and Neutrons",
    answer_ta: "புரோட்டான்கள் மற்றும் நியூட்ரான்கள்",
    explanation: "Protons (positive) and Neutrons (neutral) make up the dense central nucleus, while Electrons orbit outside! ⚛️",
    explanation_ta: "நேர்மின்னூட்டம் கொண்ட புரோட்டான்களும் மின்சுமையற்ற நியூட்ரான்களும் உட்கருவில் உள்ளன; எதிர்மின் துகள்கள் வெளியே சுற்றி வருகின்றன! ⚛️",
    classRange: [7, 8]
  },
  {
    title: "🌿 Chemical Change",
    title_ta: "🌿 வேதியியல் மாற்றம்",
    question: "Rusting of iron in the presence of moisture and air is which type of change?",
    question_ta: "ஈரப்பதம் மற்றும் காற்றின் முன்னிலையில் இரும்பு துருப்பிடித்தல் எத்தகைய மாற்றம் ஆகும்?",
    options: ["Physical change", "Chemical change", "Reversible change", "Biological change"],
    options_ta: ["இயற்பியல் மாற்றம்", "வேதியியல் மாற்றம்", "மீளக்கூடிய மாற்றம்", "உயிரியல் மாற்றம்"],
    answer: "Chemical change",
    answer_ta: "வேதியியல் மாற்றம்",
    explanation: "Rusting is a chemical change because a new compound (hydrated iron oxide) is formed and cannot be reversed! 🔩",
    explanation_ta: "துருப்பிடித்தல் என்பது புதிய வேதிப்பொருளை உருவாக்குவதால் அது ஒரு மீளாத வேதியியல் மாற்றம் ஆகும்! 🔩",
    classRange: [7, 8]
  },
  {
    title: "🌡️ Zero Motion",
    title_ta: "🌡️ தனிச்சுழி வெப்பநிலை",
    question: "What temperature represents Absolute Zero, where all molecular motion ceases?",
    question_ta: "மூலக்கூறுகளின் இயக்கம் முற்றிலும் நின்றுவிடும் தனிச்சுழி வெப்பநிலை எவ்வளவு?",
    options: ["0°C", "-273.15°C", "-100°C", "100°C"],
    options_ta: ["0°C", "-273.15°C", "-100°C", "100°C"],
    answer: "-273.15°C",
    answer_ta: "-273.15°C",
    explanation: "Absolute Zero is 0 Kelvin or -273.15°C, the lowest limit of thermodynamic temperature scale! ❄️",
    explanation_ta: "தனிச்சுழி வெப்பநிலை என்பது 0 கெல்வின் அல்லது -273.15°C ஆகும், இதற்கு கீழ் வெப்பநிலையைக் குறைக்க முடியாது! ❄️",
    classRange: [7, 8]
  },
  {
    title: "🩸 Blood Carrier",
    title_ta: "🩸 இரத்த நிறமி",
    question: "Which iron-rich protein gives red blood cells their color and binds oxygen?",
    question_ta: "இரத்த சிவப்பணுக்களுக்குச் சிவப்பு நிறத்தை வழங்குவதோடு ஆக்சிஜனைக் கடத்தும் புரதம் எது?",
    options: ["Chlorophyll", "Hemoglobin", "Melanin", "Plasma"],
    options_ta: ["குளோரோபில்", "ஹீமோகுளோபின்", "மெலனின்", "பிளாஸ்மா"],
    answer: "Hemoglobin",
    answer_ta: "ஹீமோகுளோபின்",
    explanation: "Hemoglobin contains iron molecules that bond with oxygen in the lungs and carry it to tissues! 🩸",
    explanation_ta: "ஹீமோகுளோபினில் உள்ள இரும்புச்சத்து ஆக்சிஜனுடன் பிணைப்பை ஏற்படுத்தி உடல் முழுவதும் கொண்டு சேர்க்கிறது! 🩸",
    classRange: [7, 8]
  },
  {
    title: "💎 Light Speed",
    title_ta: "💎 ஒளியின் வேகம்",
    question: "Through which of these media does light travel the slowest?",
    question_ta: "கீழ்க்கண்டவற்றுள் ஒளி எதன் வழியாக மிக மெதுவாகப் பயணிக்கிறது?",
    options: ["Air", "Water", "Glass", "Diamond"],
    options_ta: ["காற்று", "நீர்", "கண்ணாடி", "வைரம்"],
    answer: "Diamond",
    answer_ta: "வைரம்",
    explanation: "Diamond has a very high optical density and refractive index, which slows light down to 124,000 km/s! 💎",
    explanation_ta: "வைரம் மிக அதிகமான ஒளிவிலகல் எண்ணைக் கொண்டுள்ளதால், அதன் வழியாக ஒளி செல்லும்போது வேகம் பாதியாகக் குறைகிறது! 💎",
    classRange: [7, 8]
  },
  {
    title: "⚡ Resistance Law",
    title_ta: "⚡ ஓம் விதி",
    question: "What is the mathematical equation representing Ohm's Law?",
    question_ta: "ஓம் விதியின் கணிதச் சமன்பாடு எது?",
    options: ["V = IR", "P = VI", "F = ma", "E = mc²"],
    options_ta: ["V = IR", "P = VI", "F = ma", "E = mc²"],
    answer: "V = IR",
    answer_ta: "V = IR",
    explanation: "Ohm's Law states Voltage (V) equals Current (I) multiplied by Resistance (R)! ⚡",
    explanation_ta: "ஓம் விதியின்படி, மின்னழுத்த வேறுபாடு (V) என்பது மின்னோட்டம் (I) மற்றும் மின்தடையின் (R) பெருக்குத்தொகைக்குச் சமம்! ⚡",
    classRange: [7, 8]
  },
  {
    title: "🧬 Cell Division",
    title_ta: "🧬 மயோசிஸ் பகுப்பு",
    question: "Which type of cell division reduces the chromosome number by half to form gametes?",
    question_ta: "குரோமோசோம்களின் எண்ணிக்கையைக் பாதியாகக் குறைத்து இனப்பெருக்கச் செல்களை உருவாக்கும் செல் பகுப்பு எது?",
    options: ["Mitosis", "Meiosis", "Binary fission", "Budding"],
    options_ta: ["மைட்டோசிஸ்", "மயோசிஸ் (குன்றல் பகுப்பு)", "இருபிளவுறுதல்", "மொட்டு விடுதல்"],
    answer: "Meiosis",
    answer_ta: "மயோசிஸ் (குன்றல் பகுப்பு)",
    explanation: "Meiosis occurs in reproductive cells to produce four daughter cells, each with half the parent DNA! 🧬",
    explanation_ta: "மயோசிஸ் அல்லது குன்றல் பகுப்பு மூலம் தாய் செல்லிலிருந்து பாதி குரோமோசோம்கள் கொண்ட 4 சேய் செல்கள் உருவாகின்றன! 🧬",
    classRange: [7, 8]
  },
  {
    title: "💨 Yeast Respiration",
    title_ta: "💨 ஈஸ்ட் சுவாசம்",
    question: "What are the main products of anaerobic respiration in yeast?",
    question_ta: "ஈஸ்ட் காற்றில்லா சுவாசத்தில் ஈடுபடும்போது உருவாகும் முக்கிய விளைபொருட்கள் எவை?",
    options: ["Lactic acid", "Ethanol and Carbon Dioxide", "Water and Oxygen", "Glucose"],
    options_ta: ["லாக்டிக் அமிலம்", "எத்தனால் மற்றும் கார்பன் டை ஆக்சைடு", "நீர் மற்றும் ஆக்சிஜன்", "குளுக்கோஸ்"],
    answer: "Ethanol and Carbon Dioxide",
    answer_ta: "Ethanol and Carbon Dioxide",
    explanation: "Yeast breaks down glucose without oxygen, producing ethanol (alcohol) and CO2 in fermentation! 🍞",
    explanation_ta: "ஈஸ்ட்கள் ஆக்சிஜன் இல்லாத நிலையில் சர்க்கரையை நொதிக்கச் செய்து ஆல்கஹாலையும் கார்பன் டை ஆக்சைடையும் தருகின்றன! 🍞",
    classRange: [7, 8]
  },
  {
    title: "☁️ Air Pressure",
    title_ta: "☁️ காற்று அழுத்தம்",
    question: "Which scientific instrument is used to measure atmospheric pressure?",
    question_ta: "வளிமண்டல அழுத்தத்தை அளவிடப் பயன்படும் அறிவியல் கருவி எது?",
    options: ["Thermometer", "Barometer", "Anemometer", "Hydrometer"],
    options_ta: ["வெப்பநிலைமானி", "பாரோமீட்டர் (அழுத்தமானி)", "அனிமோமீட்டர்", "ஹைட்ரோமீட்டர்"],
    answer: "Barometer",
    answer_ta: "பாரோமீட்டர் (அழுத்தமானி)",
    explanation: "A barometer measures air pressure. Rapid drops in pressure usually signal approaching storms! 🌧️",
    explanation_ta: "பாரோமீட்டர் வளிமண்டல அழுத்தத்தை அளவிடப் பயன்படுகிறது. அழுத்தம் வேகமாகச் சரிந்தால் புயல் வருவதற்கான அறிகுறியாகும்! 🌧️",
    classRange: [7, 8]
  },
  {
    title: "🧪 Isotope Definition",
    title_ta: "🧪 ஐசோடோப்புகள்",
    question: "Isotopes are atoms of the same element that have different numbers of...",
    question_ta: "ஐசோடோப்புகள் என்பவை ஒரே தனிமத்தின் அணுக்களில் எவற்றின் எண்ணிக்கையில் மாறுபடுகின்றன?",
    options: ["Protons", "Electrons", "Neutrons", "Positrons"],
    options_ta: ["புரோட்டான்கள்", "எலக்ட்ரான்கள்", "நியூட்ரான்கள்", "பாசிட்ரான்கள்"],
    answer: "Neutrons",
    answer_ta: "நியூட்ரான்கள்",
    explanation: "Isotopes have the same number of protons (atomic number) but different numbers of neutrons (mass number)! ⚛️",
    explanation_ta: "ஐசோடோப்புகள் ஒரே அணு எண்ணையும் ஆனால் வெவ்வேறு நியூட்ரான்கள் எண்ணிக்கையால் வேறுபட்ட நிறை எண்ணையும் கொண்டவை! ⚛️",
    classRange: [7, 8]
  },
  {
    title: "🔊 Sound Pitch",
    title_ta: "🔊 ஒலியின் சுருதி",
    question: "The pitch of a sound wave is primarily determined by its...",
    question_ta: "ஒலியின் சுருதி எதைப் பொறுத்து அமைகிறது?",
    options: ["Amplitude", "Frequency", "Velocity", "Wavelength"],
    options_ta: ["வீச்சு", "அதிர்வெண்", "திசைவேகம்", "அலைநீளம்"],
    answer: "Frequency",
    answer_ta: "அதிர்வெண்",
    explanation: "Frequency determines pitch. Higher frequency means a higher-pitched, squeakier sound! 🔊",
    explanation_ta: "அதிர்வெண் ஒலியின் சுருதியைத் தீர்மானிக்கிறது. அதிக அதிர்வெண் கொண்ட ஒலி கூர்மையான சுருதியைக் கொண்டிருக்கும்! 🔊",
    classRange: [7, 8]
  }
];
