export interface NMMSQuestion {
  id: string;
  paper_type: 'MAT' | 'SAT';
  subject?: 'mathematics' | 'science' | 'social_science';
  chapter: string;
  topic: string;
  question_text: string;
  question_text_ta?: string;
  option_a: string;
  option_b: string;
  option_c: string;
  option_d: string;
  option_a_ta?: string;
  option_b_ta?: string;
  option_c_ta?: string;
  option_d_ta?: string;
  correct_answer: 'A' | 'B' | 'C' | 'D';
  explanation?: string;
  explanation_ta?: string;
  hint?: string;
  hint_ta?: string;
  difficulty: 'easy' | 'medium' | 'hard';
  question_type: string;
}

const RAW_QUESTIONS: NMMSQuestion[] = [
  // ── MAT: ANALOGY (ஒப்புமை) ──
  {
    id: "mat-analogy-1",
    paper_type: "MAT",
    chapter: "Analogy",
    topic: "Word Analogy",
    question_text: "Tamil Nadu : Chennai :: Karnataka : ?",
    question_text_ta: "தமிழ்நாடு : சென்னை :: கர்நாடகா : ?",
    option_a: "Bengaluru",
    option_b: "Mysuru",
    option_c: "Mangaluru",
    option_d: "Belagavi",
    option_a_ta: "பெங்களூரு",
    option_b_ta: "மைசூரு",
    option_c_ta: "மங்களூரு",
    option_d_ta: "பெலகாவி",
    correct_answer: "A",
    explanation: "Chennai is the capital of Tamil Nadu, and Bengaluru is the capital of Karnataka.",
    explanation_ta: "சென்னை தமிழ்நாட்டின் தலைநகரம், பெங்களூரு கர்நாடகாவின் தலைநகரம் ஆகும்.",
    hint: "Think about state capitals.",
    hint_ta: "மாநில தலைநகரங்களைப் பற்றி யோசித்துப் பாருங்கள்.",
    difficulty: "easy",
    question_type: "analogy"
  },
  {
    id: "mat-analogy-2",
    paper_type: "MAT",
    chapter: "Analogy",
    topic: "Number Analogy",
    question_text: "5 : 25 :: 9 : ?",
    question_text_ta: "5 : 25 :: 9 : ?",
    option_a: "36",
    option_b: "81",
    option_c: "45",
    option_d: "90",
    option_a_ta: "36",
    option_b_ta: "81",
    option_c_ta: "45",
    option_d_ta: "90",
    correct_answer: "B",
    explanation: "The pattern is x : x^2. So, 5^2 = 25, and 9^2 = 81.",
    explanation_ta: "இங்கு முறை x : x^2 ஆகும். எனவே, 5^2 = 25 மற்றும் 9^2 = 81 ஆகும்.",
    hint: "Square the first number.",
    hint_ta: "முதல் எண்ணின் வர்க்கத்தைக் கண்டறியவும்.",
    difficulty: "easy",
    question_type: "analogy"
  },
  {
    id: "mat-analogy-3",
    paper_type: "MAT",
    chapter: "Analogy",
    topic: "Word Analogy",
    question_text: "Doctor : Hospital :: Teacher : ?",
    question_text_ta: "மருத்துவர் : மருத்துவமனை :: ஆசிரியர் : ?",
    option_a: "Office",
    option_b: "School",
    option_c: "Court",
    option_d: "Factory",
    option_a_ta: "அலுவலகம்",
    option_b_ta: "பள்ளி",
    option_c_ta: "நீதிமன்றம்",
    option_d_ta: "தொழிற்சாலை",
    correct_answer: "B",
    explanation: "A doctor works in a hospital, and a teacher works in a school.",
    explanation_ta: "ஒரு மருத்துவர் மருத்துவமனையில் பணிபுரிகிறார், ஒரு ஆசிரியர் பள்ளியில் பணிபுரிகிறார்.",
    hint: "Where does a teacher work?",
    hint_ta: "ஆசிரியர் எங்கு பணிபுரிகிறார்?",
    difficulty: "easy",
    question_type: "analogy"
  },
  {
    id: "mat-analogy-4",
    paper_type: "MAT",
    chapter: "Analogy",
    topic: "Letter Analogy",
    question_text: "ACT : CAT :: PIN : ?",
    question_text_ta: "ACT : CAT :: PIN : ?",
    option_a: "NIP",
    option_b: "IPN",
    option_c: "Pni",
    option_d: "IPN",
    option_a_ta: "NIP",
    option_b_ta: "IPN",
    option_c_ta: "Pni",
    option_d_ta: "IPN",
    correct_answer: "D",
    explanation: "The letters of ACT are rearranged such that the middle letter comes first, followed by the first letter, then the third: A(1) C(2) T(3) -> C(2) A(1) T(3). Applying this to PIN: P(1) I(2) N(3) -> I(2) P(1) N(3) = IPN.",
    explanation_ta: "ACT-ன் எழுத்துக்கள் இடமாற்றம் செய்யப்பட்டுள்ளன (நடுவெழுத்து, முதலெழுத்து, மூன்றாம் எழுத்து). PIN-க்கு இதைப் பயன்படுத்தினால்: I-P-N.",
    hint: "Look at the order of letters.",
    hint_ta: "எழுத்துக்களின் வரிசையை கவனித்துப் பாருங்கள்.",
    difficulty: "medium",
    question_type: "analogy"
  },
  {
    id: "mat-analogy-5",
    paper_type: "MAT",
    chapter: "Analogy",
    topic: "Number Analogy",
    question_text: "8 : 64 :: 11 : ?",
    question_text_ta: "8 : 64 :: 11 : ?",
    option_a: "110",
    option_b: "121",
    option_c: "132",
    option_d: "100",
    option_a_ta: "110",
    option_b_ta: "121",
    option_c_ta: "132",
    option_d_ta: "100",
    correct_answer: "B",
    explanation: "8^2 = 64. Similarly, 11^2 = 121.",
    explanation_ta: "8^2 = 64. அதேபோல், 11^2 = 121.",
    hint: "What is the square of 11?",
    hint_ta: "11-ன் வர்க்கம் என்ன?",
    difficulty: "easy",
    question_type: "analogy"
  },

  // ── MAT: CLASSIFICATION (ஒற்றைப்படை கண்டறிதல்) ──
  {
    id: "mat-class-1",
    paper_type: "MAT",
    chapter: "Classification",
    topic: "Odd One Out",
    question_text: "Find the odd one out:",
    question_text_ta: "வேறுபட்ட ஒன்றைக் கண்டறியவும்:",
    option_a: "Apple",
    option_b: "Mango",
    option_c: "Potato",
    option_d: "Banana",
    option_a_ta: "ஆப்பிள்",
    option_b_ta: "மாம்பழம்",
    option_c_ta: "உருளைக்கிழங்கு",
    option_d_ta: "வாழைப்பழம்",
    correct_answer: "C",
    explanation: "Apple, Mango, and Banana are fruits, whereas Potato is a vegetable.",
    explanation_ta: "ஆப்பிள், மாம்பழம் மற்றும் வாழைப்பழம் ஆகியவை பழங்கள், ஆனால் உருளைக்கிழங்கு ஒரு காய்கறி ஆகும்.",
    hint: "Identify fruits vs vegetables.",
    hint_ta: "பழங்கள் மற்றும் காய்கறிகளை வேறுபடுத்திப் பாருங்கள்.",
    difficulty: "easy",
    question_type: "classification"
  },
  {
    id: "mat-class-2",
    paper_type: "MAT",
    chapter: "Classification",
    topic: "Odd One Out",
    question_text: "Find the odd number:",
    question_text_ta: "வேறுபட்ட எண்ணைக் கண்டறியவும்:",
    option_a: "17",
    option_b: "23",
    option_c: "27",
    option_d: "29",
    option_a_ta: "17",
    option_b_ta: "23",
    option_c_ta: "27",
    option_d_ta: "29",
    correct_answer: "C",
    explanation: "17, 23, and 29 are prime numbers, while 27 is a composite number (divisible by 1, 3, 9, 27).",
    explanation_ta: "17, 23 மற்றும் 29 ஆகியவை பகா எண்கள், ஆனால் 27 ஒரு பகு எண் ஆகும் (3 மற்றும் 9-ஆல் வகுபடும்).",
    hint: "Check for prime numbers.",
    hint_ta: "பகா எண்களைச் சரிபார்க்கவும்.",
    difficulty: "medium",
    question_type: "classification"
  },
  {
    id: "mat-class-3",
    paper_type: "MAT",
    chapter: "Classification",
    topic: "Odd One Out",
    question_text: "Find the odd word:",
    question_text_ta: "வேறுபட்ட வார்த்தையைக் கண்டறியவும்:",
    option_a: "Tiger",
    option_b: "Lion",
    option_c: "Leopard",
    option_d: "Cow",
    option_a_ta: "புலி",
    option_b_ta: "சிங்கம்",
    option_c_ta: "சிறுத்தை",
    option_d_ta: "பசு",
    correct_answer: "D",
    explanation: "Tiger, Lion, and Leopard are wild carnivores, whereas Cow is a domestic herbivore.",
    explanation_ta: "புலி, சிங்கம் மற்றும் சிறுத்தை ஆகியவை காட்டு விலங்குகள் (ஊனுண்ணிகள்), ஆனால் பசு ஒரு வீட்டு விலங்கு (தாவர உண்ணி).",
    hint: "Wild vs Domestic animals.",
    hint_ta: "காட்டு விலங்குகள் மற்றும் வீட்டு விலங்குகளை ஒப்பிடுக.",
    difficulty: "easy",
    question_type: "classification"
  },
  {
    id: "mat-class-4",
    paper_type: "MAT",
    chapter: "Classification",
    topic: "Odd One Out",
    question_text: "Find the odd one:",
    question_text_ta: "வேறுபட்ட ஒன்றைக் கண்டறியவும்:",
    option_a: "Physics",
    option_b: "Chemistry",
    option_c: "Biology",
    option_d: "History",
    option_a_ta: "இயற்பியல்",
    option_b_ta: "வேதியியல்",
    option_c_ta: "உயிரியல்",
    option_d_ta: "வரலாறு",
    correct_answer: "D",
    explanation: "Physics, Chemistry, and Biology are branches of Science, while History is a Social Science subject.",
    explanation_ta: "இயற்பியல், வேதியியல் மற்றும் உயிரியல் ஆகியவை அறிவியல் பிரிவுகள், ஆனால் வரலாறு ஒரு சமூக அறிவியல் பாடம்.",
    hint: "Science vs Social Science.",
    hint_ta: "அறிவியல் மற்றும் சமூக அறிவியல் பிரிவுகளை கவனிக்கவும்.",
    difficulty: "easy",
    question_type: "classification"
  },

  // ── MAT: SERIES REASONING (தொடர் வரிசை) ──
  {
    id: "mat-series-1",
    paper_type: "MAT",
    chapter: "Series",
    topic: "Number Series",
    question_text: "Complete the series: 3, 6, 12, 24, ?",
    question_text_ta: "தொடரை முழுமையாக்குக: 3, 6, 12, 24, ?",
    option_a: "30",
    option_b: "36",
    option_c: "48",
    option_d: "60",
    option_a_ta: "30",
    option_b_ta: "36",
    option_c_ta: "48",
    option_d_ta: "60",
    correct_answer: "C",
    explanation: "Each number in the series is multiplied by 2: 3*2=6, 6*2=12, 12*2=24, 24*2=48.",
    explanation_ta: "தொடரிலுள்ள ஒவ்வொரு எண்ணும் 2-ஆல் பெருக்கப்படுகிறது: 3*2=6, 6*2=12, 12*2=24, 24*2=48.",
    hint: "Multiply by 2.",
    hint_ta: "2-ஆல் பெருக்கவும்.",
    difficulty: "easy",
    question_type: "series"
  },
  {
    id: "mat-series-2",
    paper_type: "MAT",
    chapter: "Series",
    topic: "Number Series",
    question_text: "Complete the series: 2, 5, 10, 17, ?",
    question_text_ta: "தொடரை முழுமையாக்குக: 2, 5, 10, 17, ?",
    option_a: "24",
    option_b: "26",
    option_c: "28",
    option_d: "30",
    option_a_ta: "24",
    option_b_ta: "26",
    option_c_ta: "28",
    option_d_ta: "30",
    correct_answer: "B",
    explanation: "The pattern is n^2 + 1: 1^2+1=2, 2^2+1=5, 3^2+1=10, 4^2+1=17. The next term is 5^2+1 = 26.",
    explanation_ta: "இதன் முறை n^2 + 1 ஆகும்: 1^2+1=2, 2^2+1=5, 3^2+1=10, 4^2+1=17. அடுத்த உறுப்பு 5^2+1 = 26.",
    hint: "Squares plus one.",
    hint_ta: "வர்க்கங்களுடன் ஒன்றை கூட்டவும்.",
    difficulty: "medium",
    question_type: "series"
  },
  {
    id: "mat-series-3",
    paper_type: "MAT",
    chapter: "Series",
    topic: "Letter Series",
    question_text: "Complete the series: A, C, E, G, ?",
    question_text_ta: "தொடரை முழுமையாக்குக: A, C, E, G, ?",
    option_a: "H",
    option_b: "I",
    option_c: "J",
    option_d: "K",
    option_a_ta: "H",
    option_b_ta: "I",
    option_c_ta: "J",
    option_d_ta: "K",
    correct_answer: "B",
    explanation: "The letters skip one in between (odd positions): A(1), C(3), E(5), G(7), I(9).",
    explanation_ta: "எழுத்துக்கள் ஒன்று விட்டு ஒன்றாக வருகின்றன: A(1), C(3), E(5), G(7), I(9).",
    hint: "Skip one letter.",
    hint_ta: "ஒரு எழுத்தை விட்டுவிட்டு எழுதவும்.",
    difficulty: "easy",
    question_type: "series"
  },

  // ── MAT: CODING-DECODING (குறியீட்டு முறை) ──
  {
    id: "mat-coding-1",
    paper_type: "MAT",
    chapter: "Coding-Decoding",
    topic: "Letter Coding",
    question_text: "If SUN is coded as TVO, then STAR is coded as:",
    question_text_ta: "SUN என்பது TVO எனக் குறிக்கப்பட்டால், STAR என்பது எவ்வாறு குறிக்கப்படும்:",
    option_a: "TUBS",
    option_b: "TSBS",
    option_c: "RFBS",
    option_d: "SUBS",
    option_a_ta: "TUBS",
    option_b_ta: "TSBS",
    option_c_ta: "RFBS",
    option_d_ta: "SUBS",
    correct_answer: "A",
    explanation: "Each letter is replaced by its next alphabetical letter (+1 shift): S->T, U->V, N->O. Thus, S->T, T->U, A->B, R->S, resulting in TUBS.",
    explanation_ta: "ஒவ்வொரு எழுத்தும் அதற்கு அடுத்த எழுத்தால் மாற்றப்படுகிறது (+1): S->T, U->V, N->O. அதேபோல் STAR -> TUBS.",
    hint: "Move forward by 1 letter.",
    hint_ta: "ஒவ்வொரு எழுத்தையும் 1 முறை முன்னோக்கி நகர்த்தவும்.",
    difficulty: "medium",
    question_type: "coding"
  },
  {
    id: "mat-coding-2",
    paper_type: "MAT",
    chapter: "Coding-Decoding",
    topic: "Number Coding",
    question_text: "If CAT is coded as 24 (C=3, A=1, T=20), then DOG is coded as:",
    question_text_ta: "CAT என்பது 24 எனக் குறிக்கப்பட்டால் (C=3, A=1, T=20), DOG என்பது எவ்வாறு குறிக்கப்படும்:",
    option_a: "22",
    option_b: "26",
    option_c: "30",
    option_d: "35",
    option_a_ta: "22",
    option_b_ta: "26",
    option_c_ta: "30",
    option_d_ta: "35",
    correct_answer: "B",
    explanation: "The code is the sum of alphabetical positions: D=4, O=15, G=7. Sum = 4 + 15 + 7 = 26.",
    explanation_ta: "வார்த்தையின் எழுத்துக்களின் எண்களின் கூட்டுத்தொகை ஆகும்: D=4, O=15, G=7. கூட்டுத்தொகை = 4 + 15 + 7 = 26.",
    hint: "Add letter positions.",
    hint_ta: "எழுத்துக்களின் இட மதிப்புகளைக் கூட்டவும்.",
    difficulty: "medium",
    question_type: "coding"
  },

  // ── SAT: MATHEMATICS (கணிதம்) ──
  {
    id: "sat-math-1",
    paper_type: "SAT",
    subject: "mathematics",
    chapter: "Number System",
    topic: "Rational Numbers",
    question_text: "What is the additive inverse of -5/9?",
    question_text_ta: "-5/9-ன் கூட்டல் நேர்மாறு என்ன?",
    option_a: "5/9",
    option_b: "-9/5",
    option_c: "9/5",
    option_d: "1",
    option_a_ta: "5/9",
    option_b_ta: "-9/5",
    option_c_ta: "9/5",
    option_d_ta: "5/9",
    correct_answer: "A",
    explanation: "The additive inverse of a number x is -x, such that x + (-x) = 0. The additive inverse of -5/9 is 5/9.",
    explanation_ta: "ஒரு எண்ணின் கூட்டல் நேர்மாறு என்பது அதன் குறியை மாற்றுவதாகும். -5/9-ன் கூட்டல் நேர்மாறு 5/9 ஆகும்.",
    hint: "Change the negative sign to positive.",
    hint_ta: "எதிர்மறைக் குறியை நேர்மறையாக மாற்றவும்.",
    difficulty: "easy",
    question_type: "mcq"
  },
  {
    id: "sat-math-2",
    paper_type: "SAT",
    subject: "mathematics",
    chapter: "Algebra",
    topic: "Linear Equations",
    question_text: "If 2x + 5 = 15, then the value of x is:",
    question_text_ta: "2x + 5 = 15 எனில், x-ன் மதிப்பு:",
    option_a: "10",
    option_b: "5",
    option_c: "20",
    option_d: "7.5",
    option_a_ta: "10",
    option_b_ta: "5",
    option_c_ta: "20",
    option_d_ta: "7.5",
    correct_answer: "B",
    explanation: "Subtract 5 from both sides: 2x = 10. Divide by 2: x = 5.",
    explanation_ta: "இருபுறமும் 5-ஐக் கழிக்க: 2x = 10. 2-ஆல் வகுக்க: x = 5.",
    hint: "Move 5 to the other side first.",
    hint_ta: "முதலில் 5-ஐ வலது புறம் கொண்டு செல்லவும்.",
    difficulty: "easy",
    question_type: "mcq"
  },
  {
    id: "sat-math-3",
    paper_type: "SAT",
    subject: "mathematics",
    chapter: "Mensuration",
    topic: "Area of Circle",
    question_text: "Find the area of a circle with radius 7 cm. (Take pi = 22/7)",
    question_text_ta: "ஆரம் 7 செ.மீ கொண்ட வட்டத்தின் பரப்பளவைக் காண்க. (pi = 22/7)",
    option_a: "44 sq.cm",
    option_b: "154 sq.cm",
    option_c: "88 sq.cm",
    option_d: "14 sq.cm",
    option_a_ta: "44 ச.செ.மீ",
    option_b_ta: "154 ச.செ.மீ",
    option_c_ta: "88 ச.செ.மீ",
    option_d_ta: "14 ச.செ.மீ",
    correct_answer: "B",
    explanation: "Area of Circle = pi * r^2 = (22/7) * 7 * 7 = 154 sq.cm.",
    explanation_ta: "வட்டத்தின் பரப்பளவு = pi * r^2 = (22/7) * 7 * 7 = 154 ச.செ.மீ.",
    hint: "Use Area = pi * r^2",
    hint_ta: "பரப்பளவு = pi * r^2 சூத்திரத்தைப் பயன்படுத்தவும்.",
    difficulty: "medium",
    question_type: "mcq"
  },

  // ── SAT: SCIENCE (அறிவியல்) ──
  {
    id: "sat-sci-1",
    paper_type: "SAT",
    subject: "science",
    chapter: "Physics",
    topic: "Light",
    question_text: "What is the speed of light in a vacuum?",
    question_text_ta: "வெற்றிடத்தில் ஒளியின் வேகம் என்ன?",
    option_a: "3,000 m/s",
    option_b: "300,000 m/s",
    option_c: "3 x 10^8 m/s",
    option_d: "3 x 10^5 m/s",
    option_a_ta: "3,000 மீ/வி",
    option_b_ta: "300,000 மீ/வி",
    option_c_ta: "3 x 10^8 மீ/வி",
    option_d_ta: "3 x 10^5 மீ/வி",
    correct_answer: "C",
    explanation: "The speed of light in a vacuum is approximately 300,000 km/s, which is 3 x 10^8 meters per second.",
    explanation_ta: "வெற்றிடத்தில் ஒளியின் வேகம் தோராயமாக 3 x 10^8 மீட்டர்/விநாடி ஆகும்.",
    hint: "It is 30 crore meters per second.",
    hint_ta: "இது வினாடிக்கு 30 கோடி மீட்டர் ஆகும்.",
    difficulty: "medium",
    question_type: "mcq"
  },
  {
    id: "sat-sci-2",
    paper_type: "SAT",
    subject: "science",
    chapter: "Chemistry",
    topic: "Acids and Bases",
    question_text: "Which acid is present in lemon?",
    question_text_ta: "எலுமிச்சையில் உள்ள அமிலம் எது?",
    option_a: "Lactic acid",
    option_b: "Citric acid",
    option_c: "Acetic acid",
    option_d: "Tartaric acid",
    option_a_ta: "லாக்டிக் அமிலம்",
    option_b_ta: "சிட்ரிக் அமிலம்",
    option_c_ta: "அசிட்டிக் அமிலம்",
    option_d_ta: "டார்டாரிக் அமிலம்",
    correct_answer: "B",
    explanation: "Lemon contains citric acid, which gives it a sour taste.",
    explanation_ta: "எலுமிச்சம்பழத்தில் சிட்ரிக் அமிலம் உள்ளது, இது அதற்கு புளிப்புச் சுவையைத் தருகிறது.",
    hint: "Citrus fruits contain this acid.",
    hint_ta: "சிட்ரஸ் பழங்களில் இந்த அமிலம் காணப்படுகிறது.",
    difficulty: "easy",
    question_type: "mcq"
  },
  {
    id: "sat-sci-3",
    paper_type: "SAT",
    subject: "science",
    chapter: "Biology",
    topic: "Cell Structure",
    question_text: "Which cell organelle is known as the powerhouse of the cell?",
    question_text_ta: "செல்லின் ஆற்றல் மையம் என்று அழைக்கப்படும் உறுப்பு எது?",
    option_a: "Nucleus",
    option_b: "Mitochondria",
    option_c: "Ribosome",
    option_d: "Lysosome",
    option_a_ta: "உட்கரு",
    option_b_ta: "மைட்டோகாண்ட்ரியா",
    option_c_ta: "ரைபோசோம்",
    option_d_ta: "லைசோசோம்",
    correct_answer: "B",
    explanation: "Mitochondria are called the powerhouses of the cell because they produce energy in the form of ATP.",
    explanation_ta: "மைட்டோகாண்ட்ரியாக்கள் செல்லின் ஆற்றலை (ATP) உருவாக்குவதால் அவை செல்லின் ஆற்றல் மையம் எனப்படும்.",
    hint: "Starts with M.",
    hint_ta: "இது 'M' என்ற எழுத்தில் தொடங்கும்.",
    difficulty: "easy",
    question_type: "mcq"
  },

  // ── SAT: SOCIAL SCIENCE (சமூக அறிவியல்) ──
  {
    id: "sat-soc-1",
    paper_type: "SAT",
    subject: "social_science",
    chapter: "History",
    topic: "Mughal Empire",
    question_text: "Who was the founder of the Mughal Empire in India?",
    question_text_ta: "இந்தியாவில் முகலாயப் பேரரசை நிறுவியவர் யார்?",
    option_a: "Babur",
    option_b: "Akbar",
    option_c: "Humayun",
    option_d: "Sher Shah",
    option_a_ta: "பாபர்",
    option_b_ta: "அக்பர்",
    option_c_ta: "ஹுமாயூன்",
    option_d_ta: "ஷெர்ஷா",
    correct_answer: "A",
    explanation: "Babur founded the Mughal Empire after winning the First Battle of Panipat in 1526.",
    explanation_ta: "பாபர் 1526-ல் நடைபெற்ற முதலாம் பானிபட் போருக்குப் பிறகு முகலாயப் பேரரசை நிறுவினார்.",
    hint: "He won the First Battle of Panipat.",
    hint_ta: "இவர் முதலாம் பானிபட் போரில் வென்றவர்.",
    difficulty: "easy",
    question_type: "mcq"
  },
  {
    id: "sat-soc-2",
    paper_type: "SAT",
    subject: "social_science",
    chapter: "Civics",
    topic: "Indian Constitution",
    question_text: "Who is known as the Father of the Indian Constitution?",
    question_text_ta: "இந்திய அரசியலமைப்பின் தந்தை என்று அழைக்கப்படுபவர் யார்?",
    option_a: "Mahatma Gandhi",
    option_b: "Dr. B.R. Ambedkar",
    option_c: "Jawaharlal Nehru",
    option_d: "Dr. Rajendra Prasad",
    option_a_ta: "மகாத்மா காந்தி",
    option_b_ta: "டாக்டர் பி.ஆர். அம்பேத்கர்",
    option_c_ta: "ஜவஹர்லால் நேரு",
    option_d_ta: "டாக்டர் ராஜேந்திர பிரசாத்",
    correct_answer: "B",
    explanation: "Dr. B.R. Ambedkar was the Chairman of the Drafting Committee and is recognized as the Father of the Constitution.",
    explanation_ta: "டாக்டர் பி.ஆர். அம்பேத்கர் அரசியலமைப்பு வரைவுக் குழுவின் தலைவராக இருந்தவர், எனவே அவர் அரசியலமைப்பின் தந்தை என அழைக்கப்படுகிறார்.",
    hint: "He was the chief architect of the constitution.",
    hint_ta: "அரசியலமைப்பை உருவாக்கிய முதன்மை வடிவமைப்பாளர் இவர்.",
    difficulty: "easy",
    question_type: "mcq"
  },
  {
    id: "sat-soc-3",
    paper_type: "SAT",
    subject: "social_science",
    chapter: "Geography",
    topic: "Resources",
    question_text: "Which of the following is a renewable resource?",
    question_text_ta: "கீழ்க்கண்டவற்றுள் புதுப்பிக்கத்தக்க வளம் எது?",
    option_a: "Coal",
    option_b: "Petroleum",
    option_c: "Solar Energy",
    option_d: "Natural Gas",
    option_a_ta: "நிலக்கரி",
    option_b_ta: "பெட்ரோலியம்",
    option_c_ta: "சூரிய ஆற்றல்",
    option_d_ta: "இயற்கை எரிவாயு",
    correct_answer: "C",
    explanation: "Solar energy is clean and renewable because it is replenished constantly by nature.",
    explanation_ta: "சூரிய ஆற்றல் இயற்கையிலிருந்து தொடர்ந்து கிடைப்பதால் அது ஒரு புதுப்பிக்கத்தக்க வளம் ஆகும்.",
    hint: "Comes from the Sun.",
    hint_ta: "இது சூரியனிடமிருந்து கிடைக்கிறது.",
  }
];

function getStableUuid(str: string): string {
  let h1 = 0, h2 = 0, h3 = 0, h4 = 0;
  for (let i = 0; i < str.length; i++) {
    const c = str.charCodeAt(i);
    h1 = (h1 * 31 + c) | 0;
    h2 = (h2 * 37 + c) | 0;
    h3 = (h3 * 41 + c) | 0;
    h4 = (h4 * 43 + c) | 0;
  }
  const toHex = (n: number) => {
    return (n >>> 0).toString(16).padStart(8, '0');
  };
  const hex = toHex(h1) + toHex(h2) + toHex(h3) + toHex(h4);
  return `${hex.slice(0, 8)}-${hex.slice(8, 12)}-${hex.slice(12, 16)}-${hex.slice(16, 20)}-${hex.slice(20)}`;
}

export const NMMS_STATIC_QUESTIONS: NMMSQuestion[] = RAW_QUESTIONS.map(q => ({
  ...q,
  id: getStableUuid(q.id)
}));

