// ── Math Problem Generator (class-based difficulty) ──
export const generateMathProblem = (classLevel: number) => {
  const level = Math.min(classLevel, 8);
  let a: number, b: number, answer: number, question: string;

  if (level <= 2) {
    const isAdd = Math.random() > 0.4;
    a = Math.floor(Math.random() * 15) + 1;
    b = Math.floor(Math.random() * (isAdd ? 10 : a)) + 1;
    if (isAdd) { answer = a + b; question = `${a} + ${b}`; }
    else { answer = a - b; question = `${a} - ${b}`; }
  } else if (level <= 4) {
    const ops = ["+", "-", "×", "÷"];
    const op = ops[Math.floor(Math.random() * 4)];
    if (op === "+") { a = Math.floor(Math.random() * 50) + 1; b = Math.floor(Math.random() * 50) + 1; answer = a + b; question = `${a} + ${b}`; }
    else if (op === "-") { a = Math.floor(Math.random() * 50) + 10; b = Math.floor(Math.random() * a) + 1; answer = a - b; question = `${a} - ${b}`; }
    else if (op === "×") { a = Math.floor(Math.random() * 10) + 2; b = Math.floor(Math.random() * 10) + 2; answer = a * b; question = `${a} × ${b}`; }
    else { b = Math.floor(Math.random() * 9) + 2; a = b * (Math.floor(Math.random() * 10) + 1); answer = a / b; question = `${a} ÷ ${b}`; }
  } else if (level <= 6) {
    const ops = ["+", "-", "×", "÷", "mixed"];
    const op = ops[Math.floor(Math.random() * 5)];
    if (op === "+") { a = Math.floor(Math.random() * 200) + 50; b = Math.floor(Math.random() * 200) + 50; answer = a + b; question = `${a} + ${b}`; }
    else if (op === "-") { a = Math.floor(Math.random() * 300) + 100; b = Math.floor(Math.random() * a) + 1; answer = a - b; question = `${a} - ${b}`; }
    else if (op === "×") { a = Math.floor(Math.random() * 12) + 2; b = Math.floor(Math.random() * 15) + 2; answer = a * b; question = `${a} × ${b}`; }
    else if (op === "÷") { b = Math.floor(Math.random() * 12) + 2; a = b * (Math.floor(Math.random() * 12) + 2); answer = a / b; question = `${a} ÷ ${b}`; }
    else { a = Math.floor(Math.random() * 10) + 2; b = Math.floor(Math.random() * 5) + 1; const c = Math.floor(Math.random() * 10) + 1; answer = a * b + c; question = `${a} × ${b} + ${c}`; }
  } else {
    const types = ["square", "cube", "large_mult", "large_div", "mixed"];
    const type = types[Math.floor(Math.random() * 5)];
    if (type === "square") { a = Math.floor(Math.random() * 15) + 2; answer = a * a; question = `${a}²`; }
    else if (type === "cube") { a = Math.floor(Math.random() * 8) + 2; answer = a * a * a; question = `${a}³`; }
    else if (type === "large_mult") { a = Math.floor(Math.random() * 20) + 10; b = Math.floor(Math.random() * 15) + 5; answer = a * b; question = `${a} × ${b}`; }
    else if (type === "large_div") { b = Math.floor(Math.random() * 15) + 2; a = b * (Math.floor(Math.random() * 20) + 5); answer = a / b; question = `${a} ÷ ${b}`; }
    else { a = Math.floor(Math.random() * 12) + 2; b = Math.floor(Math.random() * 12) + 2; const c = Math.floor(Math.random() * 10) + 1; answer = a * b - c; question = `${a} × ${b} - ${c}`; }
  }

  question += " = ?";
  const wrongSet = new Set<number>();
  while (wrongSet.size < 3) {
    const offset = Math.floor(Math.random() * Math.max(10, Math.abs(answer) * 0.3)) + 1;
    const wrong = Math.random() > 0.5 ? answer + offset : Math.max(0, answer - offset);
    if (wrong !== answer) wrongSet.add(wrong);
  }
  const options = shuffle([answer, ...wrongSet].map(String));
  return { question, answer: String(answer), options };
};

// ── GK Quiz Data (30+ questions, bilingual, class-tagged) ──
export const GK_QUESTIONS: { q: string; q_ta: string; options: string[]; options_ta: string[]; answer: string; answer_ta: string; classRange: [number, number] }[] = [
  // Class 1-3 New Addition
  { q: "What color is the sky on a sunny day? ☀️", q_ta: "வெயில் நாளில் வானம் என்ன நிறத்தில் இருக்கும்? ☀️", options: ["Blue", "Green", "Red", "Yellow"], options_ta: ["நீலம்", "பச்சை", "சிவப்பு", "மஞ்சள்"], answer: "Blue", answer_ta: "நீலம்", classRange: [1, 3] },
  { q: "Which animal goes 'Moo'? 🐄", q_ta: "எந்த விலங்கு 'மூ' என்று கத்தும்? 🐄", options: ["Dog", "Cow", "Cat", "Sheep"], options_ta: ["நாய்", "பசு", "பூனை", "செம்மறியாடு"], answer: "Cow", answer_ta: "பசு", classRange: [1, 3] },
  { q: "How many legs does a dog have? 🐶", q_ta: "நாய்க்கு எத்தனை கால்கள் உள்ளன? 🐶", options: ["2", "4", "6", "8"], options_ta: ["2", "4", "6", "8"], answer: "4", answer_ta: "4", classRange: [1, 3] },
  { q: "Which fruit is yellow and curved? 🍌", q_ta: "எந்தப் பழம் மஞ்சள் நிறமானதும் வளைந்ததும் ஆகும்? 🍌", options: ["Apple", "Banana", "Orange", "Grapes"], options_ta: ["ஆப்பிள்", "வாழைப்பழம்", "ஆரஞ்சு", "திராட்சை"], answer: "Banana", answer_ta: "வாழைப்பழம்", classRange: [1, 3] },
  { q: "What part of your body do you use to see? 👀", q_ta: "நீங்கள் எந்த உறுப்பைப் பயன்படுத்தி பார்க்கிறீர்கள்? 👀", options: ["Ears", "Nose", "Eyes", "Hands"], options_ta: ["காதுகள்", "மூக்கு", "கண்கள்", "கைகள்"], answer: "Eyes", answer_ta: "கண்கள்", classRange: [1, 3] },
  { q: "Which day comes right after Monday?", q_ta: "திங்கட்கிழமைக்கு அடுத்து வரும் நாள் எது?", options: ["Sunday", "Tuesday", "Wednesday", "Friday"], options_ta: ["ஞாயிற்றுக்கிழமை", "செவ்வாய்க்கிழமை", "புதன்கிழமை", "வெள்ளிக்கிழமை"], answer: "Tuesday", answer_ta: "செவ்வாய்க்கிழமை", classRange: [1, 3] },
  { q: "What falls from the clouds when it rains? 🌧️", q_ta: "மழை பெய்யும்போது மேகங்களிலிருந்து விழ்வது எது? 🌧️", options: ["Stones", "Water drops", "Leaves", "Snow"], options_ta: ["கற்கள்", "நீர் துளிகள்", "இலைகள்", "பனி"], answer: "Water drops", answer_ta: "நீர் துளிகள்", classRange: [1, 3] },
  { q: "Which animal has a very long neck to reach high leaves? 🦒", q_ta: "உயரமான இலைகளை எட்ட நீளமான கழுத்து கொண்ட விலங்கு எது? 🦒", options: ["Elephant", "Giraffe", "Zebra", "Lion"], options_ta: ["யானை", "ஒட்டகச்சிவிங்கி", "வரிக்குதிரை", "சிங்கம்"], answer: "Giraffe", answer_ta: "ஒட்டகச்சிவிங்கி", classRange: [1, 3] },
  { q: "What do bees make that is sweet to eat? 🐝", q_ta: "தேனீக்கள் எந்த இனிப்பான உணவை உருவாக்குகின்றன? 🐝", options: ["Milk", "Juice", "Honey", "Soup"], options_ta: ["பால்", "சாறு", "தேன்", "சூப்"], answer: "Honey", answer_ta: "தேன்", classRange: [1, 3] },
  { q: "Which of these is the biggest animal in the ocean? 🐋", q_ta: "கடலில் உள்ள மிகப்பெரிய விலங்கு எது? 🐋", options: ["Shark", "Blue Whale", "Dolphin", "Octopus"], options_ta: ["சுறா", "நீலத்திமிங்கிலம்", "டால்பின்", "ஆக்டோபஸ்"], answer: "Blue Whale", answer_ta: "நீலத்திமிங்கிலம்", classRange: [1, 3] },
  // Class 1-3 Existing
  { q: "How many legs does a spider have?", q_ta: "ஒரு சிலந்திக்கு எத்தனை கால்கள்?", options: ["6", "8", "10", "4"], options_ta: ["6", "8", "10", "4"], answer: "8", answer_ta: "8", classRange: [1, 3] },
  { q: "What color are bananas?", q_ta: "வாழைப்பழங்கள் என்ன நிறம்?", options: ["Red", "Green", "Yellow", "Blue"], options_ta: ["சிவப்பு", "பச்சை", "மஞ்சள்", "நீலம்"], answer: "Yellow", answer_ta: "மஞ்சள்", classRange: [1, 3] },
  { q: "How many days are in a week?", q_ta: "ஒரு வாரத்தில் எத்தனை நாட்கள்?", options: ["5", "6", "7", "8"], options_ta: ["5", "6", "7", "8"], answer: "7", answer_ta: "7", classRange: [1, 3] },
  { q: "Which animal says 'Moo'?", q_ta: "எந்த விலங்கு 'மா' என்று சொல்கிறது?", options: ["Dog", "Cat", "Cow", "Horse"], options_ta: ["நாய்", "பூனை", "பசு", "குதிரை"], answer: "Cow", answer_ta: "பசு", classRange: [1, 3] },
  { q: "What shape has 3 sides?", q_ta: "எந்த வடிவத்திற்கு 3 பக்கங்கள்?", options: ["Square", "Triangle", "Circle", "Rectangle"], options_ta: ["சதுரம்", "முக்கோணம்", "வட்டம்", "செவ்வகம்"], answer: "Triangle", answer_ta: "முக்கோணம்", classRange: [1, 3] },
  { q: "What is the baby of a cat called?", q_ta: "பூனையின் குட்டி எவ்வாறு அழைக்கப்படுகிறது?", options: ["Puppy", "Kitten", "Cub", "Calf"], options_ta: ["நாய்க்குட்டி", "பூனைக்குட்டி", "சிங்கக்குட்டி", "கன்று"], answer: "Kitten", answer_ta: "பூனைக்குட்டி", classRange: [1, 3] },
  { q: "Which fruit is red and round?", q_ta: "எந்தப் பழம் சிவப்பு மற்றும் உருண்டையானது?", options: ["Banana", "Apple", "Grapes", "Mango"], options_ta: ["வாழை", "ஆப்பிள்", "திராட்சை", "மாம்பழம்"], answer: "Apple", answer_ta: "ஆப்பிள்", classRange: [1, 3] },
  { q: "How many fingers do you have?", q_ta: "உங்களுக்கு எத்தனை விரல்கள் உள்ளன?", options: ["8", "10", "12", "5"], options_ta: ["8", "10", "12", "5"], answer: "10", answer_ta: "10", classRange: [1, 3] },
  { q: "What sound does a dog make?", q_ta: "நாய் என்ன ஒலி எழுப்பும்?", options: ["Meow", "Bark", "Moo", "Roar"], options_ta: ["மியாவ்", "வௌ வௌ", "மா", "கர்ஜனை"], answer: "Bark", answer_ta: "வௌ வௌ", classRange: [1, 3] },
  // Class 3-5 New Addition
  { q: "Which gas do humans breathe to survive?", q_ta: "மனிதர்கள் உயிர்வாழ எந்த வாயுவை சுவாசிக்கிறார்கள்?", options: ["Oxygen", "Carbon Dioxide", "Nitrogen", "Helium"], options_ta: ["ஆக்சிஜன்", "கார்பன் டை ஆக்சைடு", "நைட்ரஜன்", "ஹீலியம்"], answer: "Oxygen", answer_ta: "ஆக்சிஜன்", classRange: [3, 5] },
  { q: "What is the national bird of India?", q_ta: "இந்தியாவின் தேசியப் பறவை எது?", options: ["Pigeon", "Peacock", "Parrot", "Eagle"], options_ta: ["புறா", "மயில்", "கிளி", "கழுகு"], answer: "Peacock", answer_ta: "மயில்", classRange: [3, 5] },
  { q: "How many days are there in a leap year?", q_ta: "ஒரு லீப் ஆண்டில் எத்தனை நாட்கள் உள்ளன?", options: ["364", "365", "366", "367"], options_ta: ["364", "365", "366", "367"], answer: "366", answer_ta: "366", classRange: [3, 5] },
  { q: "Which planet is closest to Earth?", q_ta: "பூமிக்கு அருகிலுள்ள கிரகம் எது?", options: ["Mars", "Venus", "Mercury", "Jupiter"], options_ta: ["செவ்வாய்", "வெள்ளி", "புதன்", "வியாழன்"], answer: "Venus", answer_ta: "வெள்ளி", classRange: [3, 5] },
  { q: "Which festival is known as the festival of lights in India?", q_ta: "இந்தியாவில் தீபத் திருநாள் என்று அழைக்கப்படும் பண்டிகை எது?", options: ["Holi", "Diwali", "Pongal", "Eid"], options_ta: ["ஹோலி", "தீபாவளி", "பொங்கல்", "ஈத்"], answer: "Diwali", answer_ta: "தீபாவளி", classRange: [3, 5] },
  { q: "Who is known as the Iron Man of India?", q_ta: "இந்தியாவின் இரும்பு மனிதர் என்று அழைக்கப்படுபவர் யார்?", options: ["Gandhi", "Nehru", "Sardar Patel", "Subhas Bose"], options_ta: ["காந்தி", "நேரு", "சர்தார் படேல்", "சுபாஷ் போஸ்"], answer: "Sardar Patel", answer_ta: "சர்தார் படேல்", classRange: [3, 5] },
  { q: "What is the largest mammal on Earth?", q_ta: "பூமியில் உள்ள மிகப்பெரிய பாலூட்டி எது?", options: ["Elephant", "Blue Whale", "Giraffe", "Shark"], options_ta: ["யானை", "நீல திமிங்கலம்", "ஒட்டகச்சிவிங்கி", "சுறா"], answer: "Blue Whale", answer_ta: "நீல திமிங்கலம்", classRange: [3, 5] },
  { q: "What is the freezing point of water?", q_ta: "நீரின் உறைநிலை என்ன?", options: ["0°C", "10°C", "50°C", "100°C"], options_ta: ["0°C", "10°C", "50°C", "100°C"], answer: "0°C", answer_ta: "0°C", classRange: [3, 5] },
  { q: "How many states are there in India currently?", q_ta: "தற்போது இந்தியாவில் எத்தனை மாநிலங்கள் உள்ளன?", options: ["27", "28", "29", "30"], options_ta: ["27", "28", "29", "30"], answer: "28", answer_ta: "28", classRange: [3, 5] },
  { q: "Which is the tallest animal in the world?", q_ta: "உலகின் மிக உயரமான விலங்கு எது?", options: ["Elephant", "Camel", "Giraffe", "Ostrich"], options_ta: ["யானை", "ஒட்டகம்", "ஒட்டகச்சிவிங்கி", "தீக்கோழி"], answer: "Giraffe", answer_ta: "ஒட்டகச்சிவிங்கி", classRange: [3, 5] },
  // Class 3-5 Existing
  { q: "What is the capital of India?", q_ta: "இந்தியாவின் தலைநகரம் என்ன?", options: ["Mumbai", "New Delhi", "Chennai", "Kolkata"], options_ta: ["மும்பை", "புது டெல்லி", "சென்னை", "கொல்கத்தா"], answer: "New Delhi", answer_ta: "புது டெல்லி", classRange: [3, 5] },
  { q: "Which planet is known as the Red Planet?", q_ta: "எந்த கிரகம் செவ்வாய் கிரகம் என அறியப்படுகிறது?", options: ["Venus", "Mars", "Jupiter", "Saturn"], options_ta: ["வெள்ளி", "செவ்வாய்", "வியாழன்", "சனி"], answer: "Mars", answer_ta: "செவ்வாய்", classRange: [3, 5] },
  { q: "How many continents are there?", q_ta: "எத்தனை கண்டங்கள் உள்ளன?", options: ["5", "6", "7", "8"], options_ta: ["5", "6", "7", "8"], answer: "7", answer_ta: "7", classRange: [3, 5] },
  { q: "What is the largest ocean?", q_ta: "மிகப்பெரிய பெருங்கடல் எது?", options: ["Atlantic", "Indian", "Pacific", "Arctic"], options_ta: ["அட்லாண்டிக்", "இந்தியப் பெருங்கடல்", "பசிபிக்", "ஆர்க்டிக்"], answer: "Pacific", answer_ta: "பசிபிக்", classRange: [3, 5] },
  { q: "Which is the national animal of India?", q_ta: "இந்தியாவின் தேசிய விலங்கு எது?", options: ["Lion", "Elephant", "Tiger", "Peacock"], options_ta: ["சிங்கம்", "யானை", "புலி", "மயில்"], answer: "Tiger", answer_ta: "புலி", classRange: [3, 5] },
  { q: "What gas do plants absorb?", q_ta: "தாவரங்கள் எந்த வாயுவை உறிஞ்சுகின்றன?", options: ["Oxygen", "Nitrogen", "Carbon Dioxide", "Hydrogen"], options_ta: ["ஆக்சிஜன்", "நைட்ரஜன்", "கார்பன் டை ஆக்சைடு", "ஹைட்ரஜன்"], answer: "Carbon Dioxide", answer_ta: "கார்பன் டை ஆக்சைடு", classRange: [3, 5] },
  { q: "Who invented the light bulb?", q_ta: "மின்விளக்கை யார் கண்டுபிடித்தார்?", options: ["Newton", "Einstein", "Edison", "Tesla"], options_ta: ["நியூட்டன்", "ஐன்ஸ்டீன்", "எடிசன்", "டெஸ்லா"], answer: "Edison", answer_ta: "எடிசன்", classRange: [3, 5] },
  { q: "How many bones are in the human body?", q_ta: "மனித உடலில் எத்தனை எலும்புகள் உள்ளன?", options: ["106", "206", "306", "186"], options_ta: ["106", "206", "306", "186"], answer: "206", answer_ta: "206", classRange: [3, 5] },
  { q: "What is the capital of Tamil Nadu?", q_ta: "தமிழ்நாட்டின் தலைநகரம் என்ன?", options: ["Madurai", "Coimbatore", "Chennai", "Trichy"], options_ta: ["மதுரை", "கோயம்புத்தூர்", "சென்னை", "திருச்சி"], answer: "Chennai", answer_ta: "சென்னை", classRange: [3, 5] },
  { q: "Which is the longest river in Tamil Nadu?", q_ta: "தமிழ்நாட்டின் மிக நீளமான ஆறு எது?", options: ["Vaigai", "Cauvery", "Palar", "Thamiraparani"], options_ta: ["வைகை", "காவிரி", "பாலாறு", "தாமிரபரணி"], answer: "Cauvery", answer_ta: "காவிரி", classRange: [3, 5] },
  // Class 5-8 New Addition
  { q: "Who wrote the play Romeo and Juliet?", q_ta: "ரோமியோ ஜூலியட் நாடகத்தை எழுதியவர் யார்?", options: ["Charles Dickens", "William Shakespeare", "Mark Twain", "Homer"], options_ta: ["சார்லஸ் டிக்கன்ஸ்", "வில்லியம் ஷேக்ஸ்பியர்", "மார்க் ட்வைன்", "ஹோமர்"], answer: "William Shakespeare", answer_ta: "வில்லியம் ஷேக்ஸ்பியர்", classRange: [5, 8] },
  { q: "What is the chemical symbol for Iron?", q_ta: "இரும்பின் வேதியியல் குறியீடு என்ன?", options: ["Ir", "Fe", "In", "I"], options_ta: ["Ir", "Fe", "In", "I"], answer: "Fe", answer_ta: "Fe", classRange: [5, 8] },
  { q: "Which gas is most abundant in the Earth's atmosphere?", q_ta: "பூமியின் வளிமண்டலத்தில் எந்த வாயு அதிகமாக உள்ளது?", options: ["Oxygen", "Carbon Dioxide", "Nitrogen", "Hydrogen"], options_ta: ["ஆக்சிஜன்", "கார்பன் டை ஆக்சைடு", "நைட்ரஜன்", "ஹைட்ரஜன்"], answer: "Nitrogen", answer_ta: "நைட்ரஜன்", classRange: [5, 8] },
  { q: "Who was the first woman Prime Minister of India?", q_ta: "இந்தியாவின் முதல் பெண் பிரதமர் யார்?", options: ["Sarojini Naidu", "Indira Gandhi", "Annie Besant", "Sonia Gandhi"], options_ta: ["சரோஜினி நாயுடு", "இந்திரா காந்தி", "அன்னி பெசன்ட்", "சோனியா காந்தி"], answer: "Indira Gandhi", answer_ta: "இந்திரா காந்தி", classRange: [5, 8] },
  { q: "What is the square root of 144?", q_ta: "144-ன் வர்க்கமூலம் என்ன?", options: ["10", "12", "14", "16"], options_ta: ["10", "12", "14", "16"], answer: "12", answer_ta: "12", classRange: [5, 8] },
  { q: "What is the longest bone in the human body?", q_ta: "மனித உடலில் உள்ள மிக நீளமான எலும்பு எது?", options: ["Femur", "Tibia", "Fibula", "Humerus"], options_ta: ["தொடை எலும்பு", "கால் முளை எலும்பு", "கால் மெல்லிய எலும்பு", "மேற்கை எலும்பு"], answer: "Femur", answer_ta: "தொடை எலும்பு", classRange: [5, 8] },
  { q: "Who discovered penicillin?", q_ta: "பென்சிலினைக் கண்டுபிடித்தவர் யார்?", options: ["Marie Curie", "Albert Einstein", "Alexander Fleming", "Isaac Newton"], options_ta: ["மேரி கியூரி", "ஆல்பர்ட் ஐன்ஸ்டீன்", "அலெக்சாண்டர் பிளெமிங்", "ஐசக் நியூட்டன்"], answer: "Alexander Fleming", answer_ta: "அலெக்சாண்டர் பிளெமிங்", classRange: [5, 8] },
  { q: "Which planet has a day longer than its year?", q_ta: "எந்த கிரகத்தின் ஒரு நாள் அதன் ஆண்டை விட பெரியது?", options: ["Mars", "Jupiter", "Venus", "Mercury"], options_ta: ["செவ்வாய்", "வியாழன்", "வெள்ளி", "புதன்"], answer: "Venus", answer_ta: "வெள்ளி", classRange: [5, 8] },
  { q: "What is the largest hot desert in the world?", q_ta: "உலகின் மிகப்பெரிய வெப்ப பாலைவனம் எது?", options: ["Gobi", "Kalahari", "Thar", "Sahara"], options_ta: ["கோபி", "கலஹாரி", "தார்", "சஹாரா"], answer: "Sahara", answer_ta: "சஹாரா", classRange: [5, 8] },
  { q: "How many players are there in a standard cricket team?", q_ta: "ஒரு நிலையான கிரிக்கெட் அணியில் எத்தனை வீரர்கள் உள்ளனர்?", options: ["9", "10", "11", "12"], options_ta: ["9", "10", "11", "12"], answer: "11", answer_ta: "11", classRange: [5, 8] },
  // Class 5-8 Existing
  { q: "Which is the tallest mountain in the world?", q_ta: "உலகின் மிக உயரமான மலை எது?", options: ["K2", "Kangchenjunga", "Mt. Everest", "Lhotse"], options_ta: ["K2", "கஞ்சன்ஜங்கா", "எவரெஸ்ட்", "லோட்ஸே"], answer: "Mt. Everest", answer_ta: "எவரெஸ்ட்", classRange: [5, 8] },
  { q: "Which is the smallest continent?", q_ta: "மிகச்சிறிய கண்டம் எது?", options: ["Europe", "Australia", "Antarctica", "South America"], options_ta: ["ஐரோப்பா", "ஆஸ்திரேலியா", "அண்டார்டிகா", "தென் அமெரிக்கா"], answer: "Australia", answer_ta: "ஆஸ்திரேலியா", classRange: [5, 8] },
  { q: "Which river is the longest in India?", q_ta: "இந்தியாவின் மிக நீளமான ஆறு எது?", options: ["Yamuna", "Godavari", "Ganga", "Brahmaputra"], options_ta: ["யமுனா", "கோதாவரி", "கங்கை", "பிரம்மபுத்ரா"], answer: "Ganga", answer_ta: "கங்கை", classRange: [5, 8] },
  { q: "What is H₂O commonly known as?", q_ta: "H₂O என்பது பொதுவாக எவ்வாறு அறியப்படுகிறது?", options: ["Salt", "Sugar", "Water", "Acid"], options_ta: ["உப்பு", "சர்க்கரை", "நீர்", "அமிலம்"], answer: "Water", answer_ta: "நீர்", classRange: [5, 8] },
  { q: "What is the speed of light?", q_ta: "ஒளியின் வேகம் என்ன?", options: ["3×10⁶ m/s", "3×10⁸ m/s", "3×10⁴ m/s", "3×10¹⁰ m/s"], options_ta: ["3×10⁶ m/s", "3×10⁸ m/s", "3×10⁴ m/s", "3×10¹⁰ m/s"], answer: "3×10⁸ m/s", answer_ta: "3×10⁸ m/s", classRange: [5, 8] },
  { q: "Who wrote the Indian national anthem?", q_ta: "இந்திய தேசிய கீதத்தை யார் எழுதினார்?", options: ["Mahatma Gandhi", "Rabindranath Tagore", "Subhas Bose", "Jawaharlal Nehru"], options_ta: ["மகாத்மா காந்தி", "ரவீந்திரநாத் தாகூர்", "சுபாஷ் போஸ்", "ஜவஹர்லால் நேரு"], answer: "Rabindranath Tagore", answer_ta: "ரவீந்திரநாத் தாகூர்", classRange: [5, 8] },
  { q: "What is the currency of Japan?", q_ta: "ஜப்பானின் நாணயம் என்ன?", options: ["Won", "Yuan", "Yen", "Ringgit"], options_ta: ["வான்", "யுவான்", "யென்", "ரிங்கிட்"], answer: "Yen", answer_ta: "யென்", classRange: [5, 8] },
  { q: "Which organ pumps blood in the human body?", q_ta: "மனித உடலில் இரத்தத்தை பம்ப் செய்யும் உறுப்பு எது?", options: ["Lungs", "Liver", "Heart", "Brain"], options_ta: ["நுரையீரல்", "கல்லீரல்", "இதயம்", "மூளை"], answer: "Heart", answer_ta: "இதயம்", classRange: [5, 8] },
  { q: "What is the chemical symbol for Gold?", q_ta: "தங்கத்தின் வேதியியல் குறியீடு என்ன?", options: ["Go", "Gd", "Au", "Ag"], options_ta: ["Go", "Gd", "Au", "Ag"], answer: "Au", answer_ta: "Au", classRange: [5, 8] },
  { q: "Which planet has the most moons?", q_ta: "எந்த கிரகத்திற்கு அதிக நிலவுகள் உள்ளன?", options: ["Jupiter", "Saturn", "Neptune", "Uranus"], options_ta: ["வியாழன்", "சனி", "நெப்டியூன்", "யுரேனஸ்"], answer: "Saturn", answer_ta: "சனி", classRange: [5, 8] },
  { q: "What is the boiling point of water in °C?", q_ta: "நீரின் கொதிநிலை °C-ல் என்ன?", options: ["90", "100", "110", "120"], options_ta: ["90", "100", "110", "120"], answer: "100", answer_ta: "100", classRange: [5, 8] },
  { q: "Who discovered gravity?", q_ta: "புவியீர்ப்பு விசையை யார் கண்டுபிடித்தார்?", options: ["Einstein", "Newton", "Galileo", "Edison"], options_ta: ["ஐன்ஸ்டீன்", "நியூட்டன்", "கலிலியோ", "எடிசன்"], answer: "Newton", answer_ta: "நியூட்டன்", classRange: [5, 8] },
  { q: "In which year did India gain independence?", q_ta: "இந்தியா எந்த ஆண்டு சுதந்திரம் பெற்றது?", options: ["1942", "1945", "1947", "1950"], options_ta: ["1942", "1945", "1947", "1950"], answer: "1947", answer_ta: "1947", classRange: [5, 8] },
  { q: "Who is known as the Father of the Nation?", q_ta: "தேசத்தந்தை என்று யார் அறியப்படுகிறார்?", options: ["Nehru", "Gandhi", "Patel", "Ambedkar"], options_ta: ["நேரு", "காந்தி", "படேல்", "அம்பேத்கர்"], answer: "Gandhi", answer_ta: "காந்தி", classRange: [5, 8] },
  { q: "Which is the hardest natural substance?", q_ta: "மிகக் கடினமான இயற்கைப் பொருள் எது?", options: ["Gold", "Iron", "Diamond", "Platinum"], options_ta: ["தங்கம்", "இரும்பு", "வைரம்", "பிளாட்டினம்"], answer: "Diamond", answer_ta: "வைரம்", classRange: [5, 8] },
];

// ── Vocabulary Data (bilingual, class-tagged) ──
export const VOCAB_WORDS: { word: string; word_ta: string; meaning: string; meaning_ta: string; options: string[]; options_ta: string[]; classRange: [number, number] }[] = [
  // Class 1 New Addition
  { word: "Hot", word_ta: "வெப்பமான", meaning: "Very warm", meaning_ta: "மிகவும் சூடான", options: ["Cold", "Very warm", "Fast", "Sweet"], options_ta: ["குளிர்ந்த", "மிகவும் சூடான", "வேகமான", "இனிப்பான"], classRange: [1, 2] },
  { word: "Cold", word_ta: "குளிர்ந்த", meaning: "Having a low temperature", meaning_ta: "குறைந்த தட்பவெப்பநிலை கொண்ட", options: ["Hot", "Having a low temperature", "Loud", "Fast"], options_ta: ["வெப்பமான", "குறைந்த தட்பவெப்பநிலை கொண்ட", "சத்தமான", "வேகமான"], classRange: [1, 2] },
  { word: "Fast", word_ta: "வேகமான", meaning: "Moving quickly", meaning_ta: "விரைவாக நகரும்", options: ["Slow", "Moving quickly", "Tall", "Quiet"], options_ta: ["மெதுவான", "விரைவாக நகரும்", "உயரமான", "அமைதியான"], classRange: [1, 2] },
  { word: "Slow", word_ta: "மெதுவான", meaning: "Taking a long time", meaning_ta: "அதிக நேரம் எடுக்கும்", options: ["Fast", "Taking a long time", "Short", "Cold"], options_ta: ["வேகமான", "அதிக நேரம் எடுக்கும்", "குட்டையான", "குளிர்ந்த"], classRange: [1, 2] },
  { word: "Tall", word_ta: "உயரமான", meaning: "High in height", meaning_ta: "உயரம் அதிகமுள்ள", options: ["Short", "High in height", "New", "Soft"], options_ta: ["குட்டையான", "உயரம் அதிகமுள்ள", "புதிய", "மென்மையான"], classRange: [1, 2] },
  { word: "Short", word_ta: "குட்டையான", meaning: "Not tall", meaning_ta: "உயரம் குறைவான", options: ["Tall", "Not tall", "Round", "Heavy"], options_ta: ["உயரமான", "உயரம் குறைவான", "உருண்டையான", "கனமான"], classRange: [1, 2] },
  { word: "Good", word_ta: "நல்ல", meaning: "Nice and positive", meaning_ta: "நல்ல மற்றும் சிறப்பான", options: ["Bad", "Nice and positive", "Angry", "Sad"], options_ta: ["கெட்ட", "நல்ல மற்றும் சிறப்பான", "கோபமான", "சோகமான"], classRange: [1, 2] },
  { word: "Bad", word_ta: "கெட்ட", meaning: "Not good", meaning_ta: "நல்லதல்ல", options: ["Good", "Not good", "Happy", "Fast"], options_ta: ["நல்ல", "நல்லதல்ல", "மகிழ்ச்சியான", "வேகமான"], classRange: [1, 2] },
  { word: "Soft", word_ta: "மென்மையான", meaning: "Not hard, gentle", meaning_ta: "கடினமற்ற, மென்மையான", options: ["Hard", "Not hard, gentle", "Loud", "Bright"], options_ta: ["கடினமான", "கடினமற்ற, மென்மையான", "சத்தமான", "பிரகாசமான"], classRange: [1, 2] },
  { word: "Hard", word_ta: "கடினமான", meaning: "Firm and solid", meaning_ta: "உறுதியான மற்றும் கெட்டியான", options: ["Soft", "Firm and solid", "Dark", "Sweet"], options_ta: ["மென்மையான", "உறுதியான மற்றும் கெட்டியான", "இருட்டான", "இனிப்பான"], classRange: [1, 2] },
  // Class 1-3 Existing
  { word: "Big", word_ta: "பெரிய", meaning: "Large in size", meaning_ta: "அளவில் பெரிய", options: ["Small", "Large in size", "Fast", "Round"], options_ta: ["சிறிய", "அளவில் பெரிய", "வேகமான", "உருண்டையான"], classRange: [1, 3] },
  { word: "Happy", word_ta: "மகிழ்ச்சி", meaning: "Feeling joy", meaning_ta: "மகிழ்வாக உணர்தல்", options: ["Sad", "Feeling joy", "Angry", "Sleepy"], options_ta: ["சோகம்", "மகிழ்வாக உணர்தல்", "கோபம்", "தூக்கம்"], classRange: [1, 3] },
  { word: "Quick", word_ta: "விரைவான", meaning: "Moving fast", meaning_ta: "வேகமாக நகர்தல்", options: ["Slow", "Moving fast", "Heavy", "Quiet"], options_ta: ["மெதுவான", "வேகமாக நகர்தல்", "கனமான", "அமைதியான"], classRange: [1, 3] },
  { word: "Tiny", word_ta: "மிகச்சிறிய", meaning: "Very small", meaning_ta: "மிகவும் சிறிய", options: ["Very small", "Very big", "Very tall", "Very loud"], options_ta: ["மிகவும் சிறிய", "மிகவும் பெரிய", "மிகவும் உயரமான", "மிகவும் சத்தமான"], classRange: [1, 3] },
  { word: "Bright", word_ta: "பிரகாசமான", meaning: "Full of light", meaning_ta: "ஒளி நிறைந்த", options: ["Dark", "Full of light", "Wet", "Cold"], options_ta: ["இருட்டான", "ஒளி நிறைந்த", "ஈரமான", "குளிர்ந்த"], classRange: [1, 3] },
  // Class 3-5 New Addition
  { word: "Curious", word_ta: "ஆர்வமுள்ள", meaning: "Eager to know or learn something", meaning_ta: "ஒன்றை அறிய அல்லது கற்க ஆவலாக இருப்பது", options: ["Bored", "Eager to know or learn something", "Angry", "Tired"], options_ta: ["சலிப்பான", "ஒன்றை அறிய அல்லது கற்க ஆவலாக இருப்பது", "கோபமான", "சோர்வான"], classRange: [3, 5] },
  { word: "Brilliant", word_ta: "புத்திசாலித்தனமான", meaning: "Exceptionally clever or talented", meaning_ta: "அசாதாரணமான புத்திசாலி அல்லது திறமையான", options: ["Foolish", "Dark", "Exceptionally clever or talented", "Slow"], options_ta: ["முட்டாள்தனமான", "இருண்ட", "அசாதாரணமான புத்திசாலி அல்லது திறமையான", "மெதுவான"], classRange: [3, 5] },
  { word: "Gigantic", word_ta: "பிரம்மாண்டமான", meaning: "Of very great size or extent", meaning_ta: "மிகப்பெரிய அளவில் உள்ள", options: ["Tiny", "Of very great size or extent", "Fast", "Quiet"], options_ta: ["சிறிய", "மிகப்பெரிய அளவில் உள்ள", "வேகமான", "அமைதியான"], classRange: [3, 5] },
  { word: "Whisper", word_ta: "கிசுகிசு", meaning: "To speak very softly", meaning_ta: "மிகவும் மெதுவாகப் பேசுவது", options: ["Shout", "Run fast", "To speak very softly", "Cry loud"], options_ta: ["கத்துவது", "வேகமாக ஓடுவது", "மிகவும் மெதுவாகப் பேசுவது", "சத்தமாக அழுவது"], classRange: [3, 5] },
  { word: "Journey", word_ta: "பயணம்", meaning: "Traveling from one place to another", meaning_ta: "ஒரு இடத்திலிருந்து மற்றொரு இடத்திற்குச் செல்வது", options: ["Staying at home", "Traveling from one place to another", "Sleeping", "Cooking"], options_ta: ["வீட்டிலேயே இருப்பது", "ஒரு இடத்திலிருந்து மற்றொரு இடத்திற்குச் செல்வது", "தூங்குவது", "சமைப்பது"], classRange: [3, 5] },
  { word: "Wealthy", word_ta: "பணக்கார", meaning: "Having a great deal of money", meaning_ta: "நிறைய பணம் வைத்திருப்பது", options: ["Poor", "Having a great deal of money", "Sad", "Healthy"], options_ta: ["ஏழை", "நிறைய பணம் வைத்திருப்பது", "சோகமான", "ஆரோக்கியமான"], classRange: [3, 5] },
  { word: "Honest", word_ta: "நேர்மையான", meaning: "Telling the truth", meaning_ta: "உண்மையைப் பேசுவது", options: ["Liar", "Telling the truth", "Thief", "Brave"], options_ta: ["பொய்யர்", "உண்மையைப் பேசுவது", "திருடன்", "தைரியமான"], classRange: [3, 5] },
  { word: "Courage", word_ta: "தைரியம்", meaning: "The ability to do something that frightens one", meaning_ta: "பயமுறுத்தும் ஒன்றைச் செய்வதற்கான திறன்", options: ["Fear", "Weakness", "The ability to do something that frightens one", "Laziness"], options_ta: ["பயம்", "பலவீனம்", "பயமுறுத்தும் ஒன்றைச் செய்வதற்கான திறன்", "சோம்பல்"], classRange: [3, 5] },
  { word: "Discover", word_ta: "கண்டுபிடி", meaning: "Find unexpectedly or during a search", meaning_ta: "எதிர்பாராமல் அல்லது தேடிப் பெறுவது", options: ["Lose", "Hide", "Find unexpectedly or during a search", "Sleep"], options_ta: ["இழப்பது", "மறைப்பது", "எதிர்பாராமல் அல்லது தேடிப் பெறுவது", "தூங்குவது"], classRange: [3, 5] },
  { word: "Fearless", word_ta: "பயமற்ற", meaning: "Lacking fear", meaning_ta: "பயம் இல்லாத", options: ["Cowardly", "Lacking fear", "Happy", "Sad"], options_ta: ["கோழைத்தனமான", "பயம் இல்லாத", "மகிழ்ச்சியான", "சோகமான"], classRange: [3, 5] },
  // Class 3-5 Existing
  { word: "Enormous", word_ta: "மகத்தான", meaning: "Very large", meaning_ta: "மிகவும் பெரிய", options: ["Tiny", "Very large", "Fast", "Colorful"], options_ta: ["சிறிய", "மிகவும் பெரிய", "வேகமான", "வண்ணமயமான"], classRange: [3, 5] },
  { word: "Brave", word_ta: "தைரியமான", meaning: "Courageous", meaning_ta: "துணிச்சலான", options: ["Scared", "Courageous", "Lazy", "Hungry"], options_ta: ["பயந்த", "துணிச்சலான", "சோம்பேறி", "பசியுள்ள"], classRange: [3, 5] },
  { word: "Ancient", word_ta: "பண்டைய", meaning: "Very old", meaning_ta: "மிகவும் பழமையான", options: ["Modern", "Very old", "Bright", "Quiet"], options_ta: ["நவீன", "மிகவும் பழமையான", "பிரகாசமான", "அமைதியான"], classRange: [3, 5] },
  { word: "Rapid", word_ta: "துரிதமான", meaning: "Very fast", meaning_ta: "மிகவும் வேகமான", options: ["Slow", "Very fast", "Heavy", "Dark"], options_ta: ["மெதுவான", "மிகவும் வேகமான", "கனமான", "இருட்டான"], classRange: [3, 5] },
  { word: "Fragile", word_ta: "உடையக்கூடிய", meaning: "Easily broken", meaning_ta: "எளிதில் உடையக்கூடிய", options: ["Strong", "Easily broken", "Wet", "Large"], options_ta: ["வலுவான", "எளிதில் உடையக்கூடிய", "ஈரமான", "பெரிய"], classRange: [3, 5] },
  // Class 5-8 New Addition
  { word: "Resilient", word_ta: "மீள்திறன் கொண்ட", meaning: "Able to withstand or recover quickly from difficult conditions", meaning_ta: "கடினமான சூழ்நிலைகளிலிருந்து விரைவாக மீளக்கூடிய தன்மை", options: ["Fragile", "Able to withstand or recover quickly from difficult conditions", "Weak", "Lazy"], options_ta: ["உடையக்கூடிய", "கடினமான சூழ்நிலைகளிலிருந்து விரைவாக மீளக்கூடிய தன்மை", "பலவீனமான", "சோம்பேறி"], classRange: [5, 8] },
  { word: "Eloquent", word_ta: "சொல்திறமிக்க", meaning: "Fluent or persuasive in speaking or writing", meaning_ta: "பேசுவதில் அல்லது எழுதுவதில் சரளமாக உள்ள", options: ["Silent", "Fluent or persuasive in speaking or writing", "Stuttering", "Confused"], options_ta: ["அமைதியான", "பேசுவதில் அல்லது எழுதுவதில் சரளமாக உள்ள", "தடுமாறும்", "குழப்பமான"], classRange: [5, 8] },
  { word: "Ambiguous", word_ta: "தெளிவற்ற", meaning: "Open to more than one interpretation", meaning_ta: "ஒன்றுக்கும் மேற்பட்ட பொருள்களைத் தரக்கூடிய", options: ["Clear", "Open to more than one interpretation", "Definite", "Bright"], options_ta: ["தெளிவான", "ஒன்றுக்கும் மேற்பட்ட பொருள்களைத் தரக்கூடிய", "உறுதியான", "பிரகாசமான"], classRange: [5, 8] },
  { word: "Meticulous", word_ta: "கவனமான", meaning: "Showing great attention to detail", meaning_ta: "விவரங்களில் மிகுந்த கவனம் செலுத்துவது", options: ["Careless", "Sloppy", "Showing great attention to detail", "Fast"], options_ta: ["கவனக்குறைவான", "அலட்சியமான", "விவரங்களில் மிகுந்த கவனம் செலுத்துவது", "வேகமான"], classRange: [5, 8] },
  { word: "Notorious", word_ta: "கெட்ட பெயரெடுத்த", meaning: "Famous or well known, typically for some bad quality or deed", meaning_ta: "பழிக்கப்பட்ட அல்லது கெட்ட செயலுக்காக பிரபலமான", options: ["Respected", "Famous or well known, typically for some bad quality or deed", "Unknown", "Kind"], options_ta: ["மரியாதைக்குரிய", "பழிக்கப்பட்ட அல்லது கெட்ட செயலுக்காக பிரபலமான", "அறியப்படாத", "அன்பான"], classRange: [5, 8] },
  { word: "Authentic", word_ta: "உண்மையான", meaning: "Of undisputed origin and not a copy; genuine", meaning_ta: "போலியற்ற மற்றும் உண்மையான", options: ["Fake", "Of undisputed origin and not a copy; genuine", "Copied", "Artificial"], options_ta: ["போலியான", "போலியற்ற மற்றும் உண்மையான", "நகலெடுக்கப்பட்ட", "செயற்கையான"], classRange: [5, 8] },
  { word: "Inevitable", word_ta: "தவிர்க்க முடியாத", meaning: "Certain to happen; unavoidable", meaning_ta: "கட்டாயம் நிகழக்கூடிய; தவிர்க்க இயலாத", options: ["Avoidable", "Certain to happen; unavoidable", "Uncertain", "Optional"], options_ta: ["தவிர்க்கக்கூடிய", "கட்டாயம் நிகழக்கூடிய; தவிர்க்க இயலாத", "நிச்சயமற்ற", "விருப்பத்திற்குரிய"], classRange: [5, 8] },
  { word: "Profound", word_ta: "ஆழ்ந்த", meaning: "Very great or intense", meaning_ta: "மிகப்பெரிய அல்லது ஆழமான", options: ["Shallow", "Very great or intense", "Superficial", "Light"], options_ta: ["ஆழமற்ற", "மிகப்பெரிய அல்லது ஆழமான", "மேலோட்டமான", "இலேசான"], classRange: [5, 8] },
  { word: "Solitary", word_ta: "தனிமையான", meaning: "Done or existing alone", meaning_ta: "தனியாக இருப்பது அல்லது செய்யப்படுவது", options: ["Crowded", "Done or existing alone", "Together", "Public"], options_ta: ["கூட்டமான", "தனியாக இருப்பது அல்லது செய்யப்படுவது", "ஒன்றாக", "பொதுவான"], classRange: [5, 8] },
  { word: "Tenacious", word_ta: "விடாப்பிடியான", meaning: "Tending to keep a firm hold of something", meaning_ta: "ஒன்றை உறுதியாகப் பற்றிக்கொள்ளும் தன்மை", options: ["Giving up", "Tending to keep a firm hold of something", "Weak", "Loose"], options_ta: ["விட்டுக்கொடுப்பது", "ஒன்றை உறுதியாகப் பற்றிக்கொள்ளும் தன்மை", "பலவீனமான", "தளர்வான"], classRange: [5, 8] },
  // Class 5-8 Existing
  { word: "Furious", word_ta: "கோபமான", meaning: "Very angry", meaning_ta: "மிகவும் கோபமான", options: ["Happy", "Calm", "Very angry", "Sleepy"], options_ta: ["மகிழ்ச்சியான", "அமைதியான", "மிகவும் கோபமான", "தூக்கமான"], classRange: [5, 8] },
  { word: "Abundant", word_ta: "ஏராளமான", meaning: "Plenty", meaning_ta: "நிறைய", options: ["Scarce", "Plenty", "Empty", "Sweet"], options_ta: ["பற்றாக்குறை", "நிறைய", "காலியான", "இனிப்பான"], classRange: [5, 8] },
  { word: "Luminous", word_ta: "ஒளிரும்", meaning: "Giving off light", meaning_ta: "ஒளி வீசும்", options: ["Dark", "Heavy", "Giving off light", "Soft"], options_ta: ["இருட்டான", "கனமான", "ஒளி வீசும்", "மென்மையான"], classRange: [5, 8] },
  { word: "Diligent", word_ta: "கடினமாக உழைக்கும்", meaning: "Hardworking", meaning_ta: "கடின உழைப்பாளி", options: ["Hardworking", "Lazy", "Smart", "Funny"], options_ta: ["கடின உழைப்பாளி", "சோம்பேறி", "புத்திசாலி", "நகைச்சுவையான"], classRange: [5, 8] },
  { word: "Serene", word_ta: "அமைதியான", meaning: "Calm and peaceful", meaning_ta: "அமைதியான மற்றும் சாந்தமான", options: ["Noisy", "Calm and peaceful", "Hot", "Wild"], options_ta: ["சத்தமான", "அமைதியான மற்றும் சாந்தமான", "வெப்பமான", "காட்டு"], classRange: [5, 8] },
  { word: "Benevolent", word_ta: "கருணையுள்ள", meaning: "Kind and generous", meaning_ta: "கருணையும் தாராள மனமும் உள்ள", options: ["Cruel", "Kind and generous", "Strict", "Quiet"], options_ta: ["கொடூரமான", "கருணையும் தாராள மனமும் உள்ள", "கண்டிப்பான", "அமைதியான"], classRange: [5, 8] },
  { word: "Ephemeral", word_ta: "நிலையற்ற", meaning: "Lasting a short time", meaning_ta: "குறுகிய காலம் நீடிக்கும்", options: ["Lasting a short time", "Permanent", "Colorful", "Heavy"], options_ta: ["குறுகிய காலம் நீடிக்கும்", "நிரந்தரமான", "வண்ணமயமான", "கனமான"], classRange: [5, 8] },
  { word: "Pragmatic", word_ta: "நடைமுறை", meaning: "Practical", meaning_ta: "நடைமுறையான", options: ["Dreamy", "Practical", "Fearful", "Gentle"], options_ta: ["கனவு காண்பவர்", "நடைமுறையான", "பயந்த", "மென்மையான"], classRange: [5, 8] },
];

// ── Science Lab Data (bilingual, class-tagged) ──
export const SCIENCE_EXPERIMENTS: { title: string; title_ta: string; question: string; question_ta: string; options: string[]; options_ta: string[]; answer: string; answer_ta: string; explanation: string; explanation_ta: string; classRange: [number, number] }[] = [
  // Class 1 New Additions
  { title: "☀️ The Bright Sun", title_ta: "☀️ பிரகாசமான சூரியன்", question: "When do we see the Sun in the sky?", question_ta: "நாம் எப்போது வானத்தில் சூரியனைக் காண்போம்?", options: ["At night", "In the morning", "When it snows", "Under the bed"], options_ta: ["இரவில்", "காலையில்", "பனி பெய்யும்போது", "கட்டிலுக்கு அடியில்"], answer: "In the morning", answer_ta: "காலையில்", explanation: "The Sun rises in the morning and gives us light and warmth! 🌅", explanation_ta: "சூரியன் காலையில் உதித்து நமக்கு ஒளியும் வெப்பமும் தருகிறது! 🌅", classRange: [1, 2] },
  { title: "🌧️ Puddle Jumping", title_ta: "🌧️ குட்டையில் குதித்தல்", question: "What makes puddles on the ground?", question_ta: "தரையிலுள்ள குட்டைகளை உருவாக்குவது எது?", options: ["Sun", "Rain", "Wind", "Snow"], options_ta: ["சூரியன்", "மழை", "காற்று", "பனி"], answer: "Rain", answer_ta: "மழை", explanation: "When it rains, water collects on the ground to make fun puddles! 💧", explanation_ta: "மழை பெய்யும்போது, தண்ணீர் தரையில் சேர்ந்து வேடிக்கையான குட்டைகளை உருவாக்குகிறது! 💧", classRange: [1, 2] },
  { title: "👁️ My Five Senses", title_ta: "👁️ என் ஐம்புலன்கள்", question: "Which body part do we use to taste sweet chocolate?", question_ta: "இனிப்பான சாக்லேட்டை சுவைக்க எந்த உடல் உறுப்பை பயன்படுத்துகிறோம்?", options: ["Eyes", "Ears", "Tongue", "Feet"], options_ta: ["கண்கள்", "காதுகள்", "நாக்கு", "கால் முனைகள்"], answer: "Tongue", answer_ta: "நாக்கு", explanation: "Our tongue has tiny taste buds that let us taste yummy food! 👅", explanation_ta: "நமது நாக்கில் உணவை சுவைக்க உதவும் சுவை மொட்டுகள் உள்ளன! 👅", classRange: [1, 2] },
  { title: "🦷 Shiny Teeth", title_ta: "🦷 பிரகாசமான பற்கள்", question: "What should we do to keep our teeth clean?", question_ta: "பற்களை சுத்தமாக வைத்திருக்க நாம் என்ன செய்ய வேண்டும்?", options: ["Eat more candy", "Brush them", "Never wash", "Drink soda"], options_ta: ["அதிக மிட்டாய் சாப்பிடுதல்", "துலக்குதல்", "எப்பொழுதும் கழுவாமை", "சோடா குடித்தல்"], answer: "Brush them", answer_ta: "துலக்குதல்", explanation: "Brushing your teeth twice a day keeps the cavities away! 🪥", explanation_ta: "தினமும் இருமுறை பல் துலக்குவது பற்சிதைவைத் தடுக்கும்! 🪥", classRange: [1, 2] },
  { title: "🎈 Floating Balloon", title_ta: "🎈 மிதக்கும் பலூன்", question: "If you let go of a helium balloon, where does it go?", question_ta: "ஹிலியம் பலூனைக் கைவிட்டால், அது எங்கே செல்லும்?", options: ["Down to the floor", "Up into the sky", "Stays still", "Turns into a bird"], options_ta: ["கீழே தரைக்கு", "மேலே வானத்திற்கு", "அப்படியே இருக்கும்", "பறவையாக மாறும்"], answer: "Up into the sky", answer_ta: "மேலே வானத்திற்கு", explanation: "Helium is lighter than air, so it floats up, up, and away! ☁️", explanation_ta: "ஹிலியம் காற்றை விட இலேசானது, எனவே அது மேலே மிதந்து செல்கிறது! ☁️", classRange: [1, 2] },
  { title: "🌬️ Windy Day", title_ta: "🌬️ காற்று வீசும் நாள்", question: "What can the wind move?", question_ta: "காற்றால் எதை நகர்த்த முடியும்?", options: ["A heavy rock", "A big mountain", "Leaves on a tree", "A house"], options_ta: ["ஒரு கனமான பாறையை", "ஒரு பெரிய மலையை", "மரத்திலுள்ள இலைகளை", "ஒரு வீட்டை"], answer: "Leaves on a tree", answer_ta: "மரத்திலுள்ள இலைகளை", explanation: "Wind is moving air! It is strong enough to blow light things like leaves. 🍃", explanation_ta: "காற்று என்பது நகரும் வளிமம்! இது இலைகள் போன்ற இலேசான பொருட்களை வீசும் அளவுக்கு வலிமையானது. 🍃", classRange: [1, 2] },
  { title: "🌙 Night Sky", title_ta: "🌙 இரவு வானம்", question: "What can you see in the sky at night?", question_ta: "இரவு வானத்தில் எதைப் பார்க்கலாம்?", options: ["The Sun", "A rainbow", "Stars and the Moon", "Blue clouds"], options_ta: ["சூரியனை", "வானவில்லை", "நட்சத்திரங்கள் மற்றும் நிலவை", "நீல நிற மேகங்களை"], answer: "Stars and the Moon", answer_ta: "நட்சத்திரங்கள் மற்றும் நிலவை", explanation: "When the Sun sets, the sky gets dark and the Moon and stars come out to shine! ✨", explanation_ta: "சூரியன் மறைந்ததும், வானம் இருட்டாகி நிலவும் நட்சத்திரங்களும் ஒளிர வருகின்றன! ✨", classRange: [1, 2] },
  { title: "🧊 Melting Ice", title_ta: "🧊 உருகும் பனிக்கட்டி", question: "What happens if you leave an ice cube in the warm sun?", question_ta: "சூடான வெயிலில் பனிக்கட்டியை வைத்தால் என்ன ஆகும்?", options: ["It turns to stone", "It melts into water", "It catches fire", "It starts flying"], options_ta: ["கல்லாக மாறும்", "நீராக உருகும்", "தீப்பிடிக்கும்", "பறக்கத் தொடங்கும்"], answer: "It melts into water", answer_ta: "நீராக உருகும்", explanation: "Heat turns solid ice back into liquid water! 🧊➡️💧", explanation_ta: "வெப்பம் திடமான பனிக்கட்டியை மீண்டும் திரவ நீராக மாற்றுகிறது! 🧊➡️💧", classRange: [1, 2] },
  { title: "🐶 Growing Up", title_ta: "🐶 வளர்தல்", question: "What do we call a baby dog?", question_ta: "நாய் குட்டியை எவ்வாறு அழைப்போம்?", options: ["Kitten", "Puppy", "Cub", "Calf"], options_ta: ["பூனைக்குட்டி", "நாய்க்குட்டி", "சிங்கக்குட்டி", "கன்றுக்குட்டி"], answer: "Puppy", answer_ta: "நாய்க்குட்டி", explanation: "A baby dog is a puppy! It grows up to be an adult dog. 🐕", explanation_ta: "ஒரு குட்டி நாய் நாய்க்குட்டி! அது வளர்ந்து பெரிய நாயாக மாறுகிறது. 🐕", classRange: [1, 2] },
  { title: "🧱 Push and Pull", title_ta: "🧱 தள்ளுதல் மற்றும் இழுத்தல்", question: "How do you close an open door?", question_ta: "திறந்த கதவை எவ்வாறு மூடுவீர்கள்?", options: ["Sing to it", "Wait for magic", "Push or pull it", "Blow on it"], options_ta: ["அதில் பாடுதல்", "மாயாஜாலத்திற்கு காத்திருத்தல்", "தள்ளுதல் அல்லது இழுத்தல்", "அதில் ஊதுதல்"], answer: "Push or pull it", answer_ta: "தள்ளுதல் அல்லது இழுத்தல்", explanation: "We use pushes and pulls (called forces) to move things around us! 🚪", explanation_ta: "நம்மைச் சுற்றியுள்ள பொருட்களை நகர்த்த தள்ளுதல் மற்றும் இழுத்தல் (விசைகள்) பயன்படுத்துகிறோம்! 🚪", classRange: [1, 2] },
  // Class 1-3 Existing
  { title: "🌱 Growing Plants", title_ta: "🌱 தாவரங்கள் வளர்தல்", question: "What do plants need to grow?", question_ta: "தாவரங்கள் வளர என்ன தேவை?", options: ["Only water", "Water, sunlight, and air", "Only sunlight", "Only soil"], options_ta: ["நீர் மட்டும்", "நீர், சூரிய ஒளி, காற்று", "சூரிய ஒளி மட்டும்", "மண் மட்டும்"], answer: "Water, sunlight, and air", answer_ta: "நீர், சூரிய ஒளி, காற்று", explanation: "Plants need water, sunlight, and air to make their own food through photosynthesis!", explanation_ta: "தாவரங்கள் ஒளிச்சேர்க்கை மூலம் தங்கள் உணவை தாங்களே தயாரிக்க நீர், சூரிய ஒளி, காற்று தேவை!", classRange: [1, 3] },
  { title: "🌈 Rainbow Colors", title_ta: "🌈 வானவில் நிறங்கள்", question: "How many colors are in a rainbow?", question_ta: "வானவில்லில் எத்தனை நிறங்கள்?", options: ["5", "6", "7", "8"], options_ta: ["5", "6", "7", "8"], answer: "7", answer_ta: "7", explanation: "A rainbow has 7 colors: Red, Orange, Yellow, Green, Blue, Indigo, and Violet (VIBGYOR)!", explanation_ta: "வானவில்லில் 7 நிறங்கள்: சிவப்பு, ஆரஞ்சு, மஞ்சள், பச்சை, நீலம், கருநீலம், ஊதா!", classRange: [1, 3] },
  { title: "🐛 Butterfly Life", title_ta: "🐛 வண்ணத்துப்பூச்சி வாழ்க்கை", question: "What does a caterpillar turn into?", question_ta: "புழு எதாக மாறும்?", options: ["Ant", "Butterfly", "Spider", "Bee"], options_ta: ["எறும்பு", "வண்ணத்துப்பூச்சி", "சிலந்தி", "தேனீ"], answer: "Butterfly", answer_ta: "வண்ணத்துப்பூச்சி", explanation: "A caterpillar goes through metamorphosis — egg → caterpillar → pupa → butterfly!", explanation_ta: "புழு மாற்றமடைகிறது — முட்டை → புழு → கூட்டுப்புழு → வண்ணத்துப்பூச்சி!", classRange: [1, 3] },
  // Class 3-5 New Additions
  { title: "🌋 Volcano Eruption", title_ta: "🌋 எரிமலை வெடிப்பு", question: "What gas is made when you mix baking soda and vinegar?", question_ta: "சமையல் சோடாவையும் வினிகரையும் கலக்கும்போது என்ன வாயு உருவாகிறது?", options: ["Oxygen", "Carbon Dioxide", "Helium", "Nitrogen"], options_ta: ["ஆக்சிஜன்", "கார்பன் டை ஆக்சைடு", "ஹீலியம்", "நைட்ரஜன்"], answer: "Carbon Dioxide", answer_ta: "கார்பன் டை ஆக்சைடு", explanation: "Mixing baking soda (base) and vinegar (acid) creates carbon dioxide gas bubbles! 🫧", explanation_ta: "சமையல் சோடாவையும் (காரம்) வினிகரையும் (அமிலம்) கலக்கும்போது கார்பன் டை ஆக்சைடு குமிழ்கள் உருவாகின்றன! 🫧", classRange: [3, 5] },
  { title: "🪞 Mirrors and Light", title_ta: "🪞 கண்ணாடிகள் மற்றும் ஒளி", question: "What happens when light hits a mirror?", question_ta: "ஒளி கண்ணாடியின் மீது படும்போது என்ன நடக்கும்?", options: ["It gets absorbed", "It reflects back", "It turns to heat", "It changes color"], options_ta: ["அது உறிஞ்சப்படுகிறது", "அது பிரதிபலிக்கிறது", "வெப்பமாக மாறுகிறது", "நிறம் மாறுகிறது"], answer: "It reflects back", answer_ta: "அது பிரதிபலிக்கிறது", explanation: "A mirror's smooth surface reflects light, allowing you to see your reflection! ✨", explanation_ta: "கண்ணாடியின் மென்மையான மேற்பரப்பு ஒளியை பிரதிபலிக்கிறது, இதனால் உங்கள் பிம்பத்தைக் காண முடிகிறது! ✨", classRange: [3, 5] },
  { title: "🌱 Seed Germination", title_ta: "🌱 விதை முளைத்தல்", question: "Which of these is NOT needed for a seed to sprout?", question_ta: "ஒரு விதை முளைப்பதற்கு இவற்றில் எது தேவையில்லை?", options: ["Water", "Warmth", "Air", "Light"], options_ta: ["நீர்", "வெதுவெதுப்பு", "காற்று", "வெளிச்சம்"], answer: "Light", answer_ta: "வெளிச்சம்", explanation: "Most seeds need water, oxygen, and warmth to sprout. They don't need light until they grow leaves!", explanation_ta: "பெரும்பாலான விதைகளுக்கு நீர், ஆக்சிஜன் கட்றும் வெதுவெதுப்பு தேவை. இலைகள் வளரும் வரை வெளிச்சம் தேவையில்லை!", classRange: [3, 5] },
  { title: "🧊 Ice and Salt", title_ta: "🧊 பனிக்கட்டி மற்றும் உப்பு", question: "What happens to ice when you sprinkle salt on it?", question_ta: "பனிக்கட்டியின் மீது உப்பைத் தூவினால் என்ன நடக்கும்?", options: ["It turns to stone", "It melts faster", "It grows bigger", "It starts burning"], options_ta: ["கல்லாக மாறும்", "வேகமாக உருகும்", "பெரியதாக வளரும்", "எரியத் தொடங்கும்"], answer: "It melts faster", answer_ta: "வேகமாக உருகும்", explanation: "Salt lowers the freezing point of water, making ice melt even below 0°C! 🧂", explanation_ta: "உப்பு நீரின் உறைநிலையைக் குறைப்பதால், 0°C-க்கும் கீழேயும் பனிக்கட்டி உருகும்! 🧂", classRange: [3, 5] },
  { title: "🎈 Static Electricity", title_ta: "🎈 நிலைமின்சாரம்", question: "Why does a balloon stick to the wall after you rub it on your hair?", question_ta: "உங்கள் தலைமுடியில் தேய்த்த பிறகு பலூன் ஏன் சுவரில் ஒட்டிக்கொள்கிறது?", options: ["It gets sticky", "It gets a static charge", "It becomes magnetic", "It loses air"], options_ta: ["அது ஒட்டும் தன்மையைப் பெறுகிறது", "நிலை மின்துகளைப் பெறுகிறது", "காந்தமாக மாறுகிறது", "காற்றை இழக்கிறது"], answer: "It gets a static charge", answer_ta: "நிலை மின்துகளைப் பெறுகிறது", explanation: "Rubbing the balloon transfers electrons, giving it a static electrical charge! ⚡", explanation_ta: "பலூனைத் தேய்ப்பது எலக்ட்ரான்களை மாற்றி, நிலை மின்னூட்டத்தைக் கொடுக்கிறது! ⚡", classRange: [3, 5] },
  { title: "🚰 Water Cycle", title_ta: "🚰 நீர் சுழற்சி", question: "What is it called when water vapor turns into clouds?", question_ta: "நீராவியானது மேகங்களாக மாறுவது எவ்வாறு அழைக்கப்படுகிறது?", options: ["Evaporation", "Condensation", "Precipitation", "Melting"], options_ta: ["ஆவியாதல்", "ஒடுக்கம்", "மழைப்பொழிவு", "உருகுதல்"], answer: "Condensation", answer_ta: "ஒடுக்கம்", explanation: "When invisible water vapor cools in the air, it condenses to form clouds! ☁️", explanation_ta: "கண்ணுக்குத் தெரியாத நீராவி காற்றில் குளிர்ந்து ஒடுங்குவதால் மேகங்கள் உருவாகின்றன! ☁️", classRange: [3, 5] },
  { title: "🧭 Compass Magic", title_ta: "🧭 திசைகாட்டி மந்திரம்", question: "Which direction does a compass needle always point?", question_ta: "திசைகாட்டி ஊசி எப்போதும் எத்திசையைக் காட்டுகிறது?", options: ["East", "West", "North", "South"], options_ta: ["கிழக்கு", "மேற்கு", "வடக்கு", "தெற்கு"], answer: "North", answer_ta: "வடக்கு", explanation: "A compass needle is a tiny magnet that lines up with Earth's magnetic north pole! 🧲", explanation_ta: "திசைகாட்டி ஊசி என்பது பூமியின் காந்த வட துருவத்துடன் ஒத்திசையும் ஒரு சிறிய காந்தம்! 🧲", classRange: [3, 5] },
  { title: "👂 Sound Waves", title_ta: "👂 ஒலி அலைகள்", question: "How does sound travel through the air?", question_ta: "காற்றில் ஒலி எவ்வாறு பயணிக்கிறது?", options: ["By vibrating particles", "By shooting light", "By making it hot", "By magnetic fields"], options_ta: ["துகள்களை அதிர்வடையச் செய்வதன் மூலம்", "ஒளியை செலுத்துவதன் மூலம்", "சூடாக்குவதன் மூலம்", "காந்தப் புலங்கள் மூலம்"], answer: "By vibrating particles", answer_ta: "துகள்களை அதிர்வடையச் செய்வதன் மூலம்", explanation: "Sound is a wave of vibrations that bumps air particles into each other! 🌊", explanation_ta: "ஒலி என்பது காற்றில் உள்ள துகள்களை ஒன்றோடொன்று மோதச் செய்யும் அதிர்வுகளின் அலை! 🌊", classRange: [3, 5] },
  { title: "🌬️ Air Pressure", title_ta: "🌬️ காற்றின் அழுத்தம்", question: "Does an empty bottle have anything inside it?", question_ta: "காலியான பாட்டிலுக்குள் ஏதேனும் உள்ளதா?", options: ["No, it's completely empty", "Yes, it has air in it", "Yes, it has invisible water", "Yes, it has a vacuum"], options_ta: ["இல்லை, முற்றிலும் காலியானது", "ஆம், அதனுள் காற்று உள்ளது", "ஆம், கண்ணுக்குத் தெரியாத நீர் உள்ளது", "ஆம், அதனுள் வெற்றிடம் உள்ளது"], answer: "Yes, it has air in it", answer_ta: "ஆம், அதனுள் காற்று உள்ளது", explanation: "Air is matter! It takes up space inside the 'empty' bottle and pushes outward. 💨", explanation_ta: "காற்று ஒரு பருப்பொருள்! அது 'காலி' பாட்டிலுக்குள் இடத்தைப் பிடித்துக்கொண்டு வெளிநோக்கித் தள்ளுகிறது. 💨", classRange: [3, 5] },
  { title: "🌡️ Temperature Change", title_ta: "🌡️ வெப்பநிலை மாற்றம்", question: "What happens to the red liquid inside a thermometer when it gets hot?", question_ta: "வெப்பமடையும்போது வெப்பமானிக்குள் இருக்கும் சிவப்பு திரவம் என்ன ஆகும்?", options: ["It turns green", "It freezes", "It goes down", "It expands and goes up"], options_ta: ["பச்சை நிறமாக மாறும்", "உறைந்துவிடும்", "கீழே இறங்கும்", "விரிவடைந்து மேலே ஏறும்"], answer: "It expands and goes up", answer_ta: "விரிவடைந்து மேலே ஏறும்", explanation: "Liquids expand when heated, making the line in the thermometer rise! 📈", explanation_ta: "திரவங்கள் வெப்பமடையும் போது விரிவடைகின்றன, இதனால் வெப்பமானியின் வரி மேலே செல்கிறது! 📈", classRange: [3, 5] },
  // Class 3-5 Existing
  { title: "🧪 Density Tower", title_ta: "🧪 அடர்த்தி கோபுரம்", question: "If you pour honey, water, and oil in a glass, which layer will be on top?", question_ta: "தேன், நீர், எண்ணெய் ஒரு கிளாஸில் ஊற்றினால், எது மேலே இருக்கும்?", options: ["Honey", "Water", "Oil", "They mix"], options_ta: ["தேன்", "நீர்", "எண்ணெய்", "கலக்கும்"], answer: "Oil", answer_ta: "எண்ணெய்", explanation: "Oil is the least dense, so it floats on top!", explanation_ta: "எண்ணெய் குறைந்த அடர்த்தி கொண்டது, எனவே மேலே மிதக்கிறது!", classRange: [3, 5] },
  { title: "🧲 Magnet Magic", title_ta: "🧲 காந்த மந்திரம்", question: "Which material will a magnet attract?", question_ta: "காந்தம் எந்தப் பொருளை ஈர்க்கும்?", options: ["Wood", "Plastic", "Iron nail", "Glass"], options_ta: ["மரம்", "பிளாஸ்டிக்", "இரும்பு ஆணி", "கண்ணாடி"], answer: "Iron nail", answer_ta: "இரும்பு ஆணி", explanation: "Magnets attract ferromagnetic materials like iron, cobalt, and nickel.", explanation_ta: "காந்தங்கள் இரும்பு, கோபால்ட், நிக்கல் போன்ற பொருட்களை ஈர்க்கின்றன.", classRange: [3, 5] },
  { title: "🌍 Day and Night", title_ta: "🌍 பகல் இரவு", question: "What causes day and night on Earth?", question_ta: "பூமியில் பகல் இரவுக்கு என்ன காரணம்?", options: ["Moon's orbit", "Earth's rotation", "Sun moving", "Stars twinkling"], options_ta: ["நிலவின் சுற்றுப்பாதை", "பூமியின் சுழற்சி", "சூரியன் நகர்தல்", "நட்சத்திரங்கள் மின்னுதல்"], answer: "Earth's rotation", answer_ta: "பூமியின் சுழற்சி", explanation: "Earth rotates on its axis once every 24 hours!", explanation_ta: "பூமி 24 மணி நேரத்திற்கு ஒருமுறை தன் அச்சில் சுழல்கிறது!", classRange: [3, 5] },
  // Class 5-8 New Additions
  { title: "⚖️ Newton's Laws", title_ta: "⚖️ நியூட்டனின் விதிகள்", question: "According to Newton's 3rd law, for every action there is an equal and opposite...", question_ta: "நியூட்டனின் 3வது விதியின்படி, ஒவ்வொரு வினைக்கும் ஒரு சமமான மற்றும் எதிர்...", options: ["Speed", "Reaction", "Force", "Weight"], options_ta: ["வேகம்", "எதிர்வினை", "விசை", "எடை"], answer: "Reaction", answer_ta: "எதிர்வினை", explanation: "If you push against a wall, the wall pushes back with equal force! 🏃‍♂️🧱", explanation_ta: "நீங்கள் சுவரைத் தள்ளினால், சுவர் அதே விசையுடன் உங்களைத் தள்ளுகிறது! 🏃‍♂️🧱", classRange: [5, 8] },
  { title: "🧪 Chemical Reactions", title_ta: "🧪 வேதியியல் வினைகள்", question: "A chemical reaction turns 'Reactants' into...", question_ta: "ஒரு வேதியியல் வினை 'வினைபடு பொருட்களை' எதாக மாற்றுகிறது?", options: ["Products", "Water", "Atoms", "Magic"], options_ta: ["விளைபொருட்கள்", "நீர்", "அணுக்கள்", "மந்திரம்"], answer: "Products", answer_ta: "விளைபொருட்கள்", explanation: "Reactants mix and combine to create brand new substances called Products! ✨", explanation_ta: "வினைபடு பொருட்கள் கலந்து புதிய பொருட்களான விளைபொருட்களை உருவாக்குகின்றன! ✨", classRange: [5, 8] },
  { title: "🧬 DNA Structure", title_ta: "🧬 டி.என்.ஏ அமைப்பு", question: "What shape is a DNA molecule?", question_ta: "டி.என்.ஏ மூலக்கூறு என்ன வடிவத்தில் உள்ளது?", options: ["A straight line", "A double helix", "A perfect circle", "A triangle"], options_ta: ["ஒரு நேர்கோடு", "ஒரு இரட்டைச் சுருள்", "ஒரு வட்ட வளைவு", "ஒரு முக்கோணம்"], answer: "A double helix", answer_ta: "ஒரு இரட்டைச் சுருள்", explanation: "DNA looks like a twisted ladder, which scientists call a 'double helix'. 🧬", explanation_ta: "டி.என்.ஏ ஒரு திருகப்பட்ட ஏணி போல் தெரிகிறது, இதனை விஞ்ஞானிகள் 'இரட்டைச் சுருள்' என்று அழைக்கின்றனர். 🧬", classRange: [5, 8] },
  { title: "⚡ Electromagnetism", title_ta: "⚡ மின்காந்தவியல்", question: "Wrapping copper wire around an iron nail and connecting it to a battery creates a...", question_ta: "இரும்பு ஆணியைச் சுற்றி செப்பு கம்பியைச் சுற்றி பேட்டரியுடன் இணைப்பது எதை உருவாக்குகிறது?", options: ["Explosion", "Electromagnet", "Permanent magnet", "Lightbulb"], options_ta: ["வெடிப்பு", "மின்காந்தம்", "நிரந்தர காந்தம்", "மின்விளக்கு"], answer: "Electromagnet", answer_ta: "மின்காந்தம்", explanation: "Electricity flowing through the coiled wire creates a magnetic field! 🔋🧲", explanation_ta: "சுருள் கம்பி வழியாக பாயும் மின்சாரம் ஒரு காந்தப் புலத்தை உருவாக்குகிறது! 🔋🧲", classRange: [5, 8] },
  { title: "🧫 Microorganisms", title_ta: "🧫 நுண்ணுயிரிகள்", question: "Which microorganism is used to turn milk into yogurt?", question_ta: "பாலை தயிராக மாற்ற எந்த நுண்ணுயிரி பயன்படுத்தப்படுகிறது?", options: ["Virus", "Fungi", "Bacteria", "Algae"], options_ta: ["வைரஸ்", "பூஞ்சை", "பாக்டீரியா", "பாசி"], answer: "Bacteria", answer_ta: "பாக்டீரியா", explanation: "Good bacteria called 'Lactobacillus' eat sugar in milk and produce acid to make yogurt! 🥣", explanation_ta: "'லாக்டோபாகிலஸ்' எனப்படும் நல்ல பாக்டீரியா பாலில் உள்ள சர்க்கரையை உண்டு, தயிரை உருவாக்க அமிலத்தை உற்பத்தி செய்கிறது! 🥣", classRange: [5, 8] },
  { title: "🌡️ Heat Transfer", title_ta: "🌡️ வெப்ப பரிமாற்றம்", question: "How does heat from the Sun reach the Earth?", question_ta: "சூரியனிலிருந்து வெப்பம் பூமியை எவ்வாறு வந்தடைகிறது?", options: ["Conduction", "Convection", "Radiation", "Insulation"], options_ta: ["கடத்துதல்", "சலனம்", "கதிர்வீச்சு", "காப்புறுதி"], answer: "Radiation", answer_ta: "கதிர்வீச்சு", explanation: "Heat travels across the empty vacuum of space through electromagnetic radiation! ☀️", explanation_ta: "வெப்பம் விண்வெளியின் வெற்றிடம் வழியாக மின்காந்த கதிர்வீச்சினால் பயணிக்கிறது! ☀️", classRange: [5, 8] },
  { title: "🌌 The Expanding Universe", title_ta: "🌌 விரிவடையும் பிரபஞ்சம்", question: "What theory explains the origin of our universe?", question_ta: "நம் பிரபஞ்சத்தின் தோற்றத்தை விளக்கும் கோட்பாடு எது?", options: ["String Theory", "Big Bang Theory", "Quantum Theory", "Evolution Theory"], options_ta: ["சரக் கோட்பாடு", "பெருவெடிப்புக் கோட்பாடு", "குவாண்டம் கோட்பாடு", "பரிணாமக் கோட்பாடு"], answer: "Big Bang Theory", answer_ta: "பெருவெடிப்புக் கோட்பாடு", explanation: "The Big Bang Theory describes how the universe expanded from a single, intensely hot point! 💥", explanation_ta: "பெருவெடிப்புக் கோட்பாடு பிரபஞ்சம் எப்படி ஒரு அதிவெப்பப் புள்ளியிலிருந்து விரிவடைந்தது என்பதை விளக்குகிறது! 💥", classRange: [5, 8] },
  { title: "♻️ Renewable Energy", title_ta: "♻️ புதுப்பிக்கத்தக்க ஆற்றல்", question: "Which of these is a renewable energy source?", question_ta: "இவற்றில் எது மேம்படுத்தக்கூடிய (புதுப்பிக்கத்தக்க) ஆற்றல் மூலமாகும்?", options: ["Coal", "Wind", "Oil", "Natural Gas"], options_ta: ["நிலக்கரி", "காற்று", "பெட்ரோலியம்", "இயற்கை எரிவாயு"], answer: "Wind", answer_ta: "காற்று", explanation: "Wind is a renewable resource because it won't run out! Coal and oil will eventually run out. 🌬️", explanation_ta: "காற்று ஒரு புதுப்பிக்கத்தக்க வளமாகும், ஏனெனில் அது ஒருபோதும் தீர்ந்து போகாது! 🌬️", classRange: [5, 8] },
  { title: "🩸 Human Circulatory System", title_ta: "🩸 மனித இரத்த ஓட்ட அமைப்பு", question: "Which blood vessels carry oxygenated blood AWAY from the heart?", question_ta: "எந்த இரத்த நாளங்கள் இதயம் விட்டு வெளியே ஆக்சிஜன் நிறைந்த இரத்தத்தை எடுத்துச் செல்கின்றன?", options: ["Veins", "Arteries", "Capillaries", "Nerves"], options_ta: ["சிரைகள்", "தமனிகள்", "நுண்நாளங்கள்", "நரம்புகள்"], answer: "Arteries", answer_ta: "தமனிகள்", explanation: "Arteries carry oxygen-rich blood away from the heart to the rest of the body! ❤️", explanation_ta: "தமனிகள் ஆக்சிஜன் நிறைந்த இரத்தத்தை இதயத்திலிருந்து உடலின் மற்ற பகுதிகளுக்கு எடுத்துச் செல்கின்றன! ❤️", classRange: [5, 8] },
  { title: "🌊 Ocean Currents", title_ta: "🌊 கடல் நீரோட்டங்கள்", question: "What mainly drives deep ocean currents?", question_ta: "ஆழமான கடல் நீரோட்டங்களை முக்கியமாக இயக்குவது எது?", options: ["Wind", "Whales swimming", "Differences in water density", "Earthquakes"], options_ta: ["காற்று", "மிதக்கும் திமிங்கலங்கள்", "நீர் அடர்த்தியில் உள்ள வேறுபாடுகள்", "பூகம்பங்கள்"], answer: "Differences in water density", answer_ta: "நீர் அடர்த்தியில் உள்ள வேறுபாடுகள்", explanation: "Cold, salty water is denser and sinks, while warm water rises, creating deep ocean currents! 🌊", explanation_ta: "குளிர்ந்த, உப்பு நிறைந்த நீர் அடர்த்தியானது மற்றும் மூழ்குகிறது, அதே சமயம் வெதுவெதுப்பான நீர் மேலே எழும்பி ஆழமான கடல் நீரோட்டங்களை உருவாக்குகிறது! 🌊", classRange: [5, 8] },
  // Class 5-8 Existing
  { title: "🔋 Circuit Challenge", title_ta: "🔋 மின்சுற்று சவால்", question: "What happens when you break a circuit?", question_ta: "மின்சுற்றை உடைத்தால் என்ன நடக்கும்?", options: ["Current flows faster", "Light gets brighter", "Current stops flowing", "Battery charges"], options_ta: ["மின்சாரம் வேகமாகும்", "விளக்கு பிரகாசமாகும்", "மின்சாரம் நிற்கும்", "பேட்டரி சார்ஜ் ஆகும்"], answer: "Current stops flowing", answer_ta: "மின்சாரம் நிற்கும்", explanation: "A break in the circuit stops the flow of electricity.", explanation_ta: "மின்சுற்றில் உடைப்பு மின்சார ஓட்டத்தை நிறுத்துகிறது.", classRange: [5, 8] },
  { title: "🌈 Light & Colors", title_ta: "🌈 ஒளியும் நிறங்களும்", question: "What color do you get when you mix all colors of light?", question_ta: "ஒளியின் அனைத்து நிறங்களையும் கலந்தால் என்ன நிறம் கிடைக்கும்?", options: ["Black", "White", "Gray", "Brown"], options_ta: ["கருப்பு", "வெள்ளை", "சாம்பல்", "பழுப்பு"], answer: "White", answer_ta: "வெள்ளை", explanation: "When all colors of light combine, they make white light.", explanation_ta: "ஒளியின் அனைத்து நிறங்களும் இணையும்போது வெள்ளை ஒளி உருவாகிறது.", classRange: [5, 8] },
  { title: "🌍 Gravity Drop", title_ta: "🌍 புவியீர்ப்பு வீழ்ச்சி", question: "In a vacuum, which falls faster — a feather or a hammer?", question_ta: "வெற்றிடத்தில் எது வேகமாக விழும் — இறகு அல்லது சுத்தியல்?", options: ["Feather", "Hammer", "Both same rate", "Neither falls"], options_ta: ["இறகு", "சுத்தியல்", "இரண்டும் ஒரே வேகம்", "எதுவும் விழாது"], answer: "Both same rate", answer_ta: "இரண்டும் ஒரே வேகம்", explanation: "Without air resistance, gravity pulls all objects at the same rate — 9.8 m/s²!", explanation_ta: "காற்றுத் தடையின்றி, புவியீர்ப்பு அனைத்துப் பொருட்களையும் ஒரே வேகத்தில் இழுக்கிறது — 9.8 m/s²!", classRange: [5, 8] },
  { title: "⚗️ Acids & Bases", title_ta: "⚗️ அமிலங்கள் & காரங்கள்", question: "What is the pH of pure water?", question_ta: "தூய நீரின் pH மதிப்பு என்ன?", options: ["0", "5", "7", "14"], options_ta: ["0", "5", "7", "14"], answer: "7", answer_ta: "7", explanation: "Pure water has a neutral pH of 7.", explanation_ta: "தூய நீரின் நடுநிலை pH மதிப்பு 7.", classRange: [5, 8] },
  { title: "🔬 Cell Biology", title_ta: "🔬 உயிரணு உயிரியல்", question: "What is the powerhouse of the cell?", question_ta: "உயிரணுவின் ஆற்றல் நிலையம் எது?", options: ["Nucleus", "Mitochondria", "Ribosome", "Golgi body"], options_ta: ["கரு", "மைட்டோகாண்ட்ரியா", "ரைபோசோம்", "கோல்கி உடலம்"], answer: "Mitochondria", answer_ta: "மைட்டோகாண்ட்ரியா", explanation: "Mitochondria convert nutrients into ATP (energy)!", explanation_ta: "மைட்டோகாண்ட்ரியா ஊட்டச்சத்துக்களை ATP (ஆற்றல்) ஆக மாற்றுகிறது!", classRange: [5, 8] },
];

export const shuffle = <T,>(arr: T[]): T[] => [...arr].sort(() => Math.random() - 0.5);

export const filterByClass = <T extends { classRange: [number, number] }>(items: T[], classLevel: number): T[] => {
  return items.filter(item => classLevel >= item.classRange[0] && classLevel <= item.classRange[1]);
};

export const getClassLabel = (level: number): string => {
  if (level <= 2) return "Beginner";
  if (level <= 4) return "Intermediate";
  if (level <= 6) return "Advanced";
  return "Expert";
};

export const getClassLabelTamil = (level: number): string => {
  if (level <= 2) return "தொடக்கம்";
  if (level <= 4) return "இடைநிலை";
  if (level <= 6) return "மேம்பட்ட";
  return "நிபுணர்";
};
