// ── General Knowledge Questions Bank (Bilingual: English + Tamil) ──
// 68 questions across 4 grade bands: [1,2], [3,4], [5,6], [7,8]

export const GK_QUESTIONS_BANK: {
  q: string;
  q_ta: string;
  options: string[];
  options_ta: string[];
  answer: string;
  answer_ta: string;
  classRange: [number, number];
}[] = [
  // ═══════════════════════════════════════════════════════════════
  // GRADE 1-2 (classRange: [1, 2]) — 17 questions
  // Topics: Colors, shapes, animals, fruits, body parts, family,
  //         basic numbers, festivals, everyday objects
  // ═══════════════════════════════════════════════════════════════

  {
    q: "What color is the sky on a clear day? ☀️",
    q_ta: "தெளிவான நாளில் வானம் என்ன நிறம்? ☀️",
    options: ["Red", "Blue", "Green", "Yellow"],
    options_ta: ["சிவப்பு", "நீலம்", "பச்சை", "மஞ்சள்"],
    answer: "Blue",
    answer_ta: "நீலம்",
    classRange: [1, 2],
  },
  {
    q: "How many fingers do you have on both hands? ✋",
    q_ta: "உங்கள் இரண்டு கைகளிலும் எத்தனை விரல்கள் உள்ளன? ✋",
    options: ["5", "8", "10", "12"],
    options_ta: ["5", "8", "10", "12"],
    answer: "10",
    answer_ta: "10",
    classRange: [1, 2],
  },
  {
    q: "Which animal says 'Meow'? 🐱",
    q_ta: "எந்த விலங்கு 'மியாவ்' என்று ஒலிக்கும்? 🐱",
    options: ["Dog", "Cat", "Cow", "Parrot"],
    options_ta: ["நாய்", "பூனை", "பசு", "கிளி"],
    answer: "Cat",
    answer_ta: "பூனை",
    classRange: [1, 2],
  },
  {
    q: "What shape is a ball? ⚽",
    q_ta: "பந்து எந்த வடிவத்தில் இருக்கும்? ⚽",
    options: ["Square", "Triangle", "Circle", "Rectangle"],
    options_ta: ["சதுரம்", "முக்கோணம்", "வட்டம்", "செவ்வகம்"],
    answer: "Circle",
    answer_ta: "வட்டம்",
    classRange: [1, 2],
  },
  {
    q: "Which fruit is yellow and curved? 🍌",
    q_ta: "எந்தப் பழம் மஞ்சள் நிறமும் வளைந்த வடிவமும் கொண்டது? 🍌",
    options: ["Apple", "Banana", "Grapes", "Orange"],
    options_ta: ["ஆப்பிள்", "வாழைப்பழம்", "திராட்சை", "ஆரஞ்சு"],
    answer: "Banana",
    answer_ta: "வாழைப்பழம்",
    classRange: [1, 2],
  },
  {
    q: "What do we use our eyes for? 👀",
    q_ta: "நாம் கண்களை எதற்குப் பயன்படுத்துகிறோம்? 👀",
    options: ["Hearing", "Seeing", "Smelling", "Tasting"],
    options_ta: ["கேட்பதற்கு", "பார்ப்பதற்கு", "நுகர்வதற்கு", "சுவைப்பதற்கு"],
    answer: "Seeing",
    answer_ta: "பார்ப்பதற்கு",
    classRange: [1, 2],
  },
  {
    q: "How many legs does a hen have? 🐔",
    q_ta: "ஒரு கோழிக்கு எத்தனை கால்கள் உள்ளன? 🐔",
    options: ["2", "4", "6", "8"],
    options_ta: ["2", "4", "6", "8"],
    answer: "2",
    answer_ta: "2",
    classRange: [1, 2],
  },
  {
    q: "What color is a ripe mango? 🥭",
    q_ta: "பழுத்த மாம்பழம் என்ன நிறம்? 🥭",
    options: ["Blue", "Green", "Yellow", "White"],
    options_ta: ["நீலம்", "பச்சை", "மஞ்சள்", "வெள்ளை"],
    answer: "Yellow",
    answer_ta: "மஞ்சள்",
    classRange: [1, 2],
  },
  {
    q: "Which festival do we celebrate by lighting lamps? 🪔",
    q_ta: "எந்த பண்டிகையில் நாம் விளக்குகள் ஏற்றுவோம்? 🪔",
    options: ["Holi", "Diwali", "Christmas", "Eid"],
    options_ta: ["ஹோலி", "தீபாவளி", "கிறிஸ்துமஸ்", "ஈத்"],
    answer: "Diwali",
    answer_ta: "தீபாவளி",
    classRange: [1, 2],
  },
  {
    q: "What gives us light during the day? ☀️",
    q_ta: "பகலில் நமக்கு ஒளி தருவது எது? ☀️",
    options: ["Moon", "Stars", "Sun", "Lamp"],
    options_ta: ["நிலவு", "நட்சத்திரங்கள்", "சூரியன்", "விளக்கு"],
    answer: "Sun",
    answer_ta: "சூரியன்",
    classRange: [1, 2],
  },
  {
    q: "How many days are in a week? 📅",
    q_ta: "ஒரு வாரத்தில் எத்தனை நாட்கள்? 📅",
    options: ["5", "6", "7", "8"],
    options_ta: ["5", "6", "7", "8"],
    answer: "7",
    answer_ta: "7",
    classRange: [1, 2],
  },
  {
    q: "What does a bee make? 🐝",
    q_ta: "தேனீ என்ன உருவாக்குகிறது? 🐝",
    options: ["Milk", "Honey", "Butter", "Sugar"],
    options_ta: ["பால்", "தேன்", "வெண்ணெய்", "சர்க்கரை"],
    answer: "Honey",
    answer_ta: "தேன்",
    classRange: [1, 2],
  },
  {
    q: "Which body part do we use to hear? 👂",
    q_ta: "நாம் கேட்க எந்த உறுப்பைப் பயன்படுத்துகிறோம்? 👂",
    options: ["Eyes", "Nose", "Ears", "Mouth"],
    options_ta: ["கண்கள்", "மூக்கு", "காதுகள்", "வாய்"],
    answer: "Ears",
    answer_ta: "காதுகள்",
    classRange: [1, 2],
  },
  {
    q: "What is the color of milk? 🥛",
    q_ta: "பாலின் நிறம் என்ன? 🥛",
    options: ["Red", "Blue", "White", "Brown"],
    options_ta: ["சிவப்பு", "நீலம்", "வெள்ளை", "பழுப்பு"],
    answer: "White",
    answer_ta: "வெள்ளை",
    classRange: [1, 2],
  },
  {
    q: "Which animal is called the King of the Jungle? 🦁",
    q_ta: "எந்த விலங்கு காட்டு ராஜா என்று அழைக்கப்படுகிறது? 🦁",
    options: ["Elephant", "Tiger", "Lion", "Bear"],
    options_ta: ["யானை", "புலி", "சிங்கம்", "கரடி"],
    answer: "Lion",
    answer_ta: "சிங்கம்",
    classRange: [1, 2],
  },
  {
    q: "What shape has four equal sides? ◻️",
    q_ta: "நான்கு சம பக்கங்கள் கொண்ட வடிவம் எது? ◻️",
    options: ["Triangle", "Circle", "Square", "Oval"],
    options_ta: ["முக்கோணம்", "வட்டம்", "சதுரம்", "நீள்வட்டம்"],
    answer: "Square",
    answer_ta: "சதுரம்",
    classRange: [1, 2],
  },
  {
    q: "Your mother's mother is called your ___? 👵",
    q_ta: "உங்கள் அம்மாவின் அம்மா உங்களுக்கு ___? 👵",
    options: ["Aunt", "Sister", "Grandmother", "Cousin"],
    options_ta: ["அத்தை", "சகோதரி", "பாட்டி", "உறவினர்"],
    answer: "Grandmother",
    answer_ta: "பாட்டி",
    classRange: [1, 2],
  },

  // ═══════════════════════════════════════════════════════════════
  // GRADE 3-4 (classRange: [3, 4]) — 17 questions
  // Topics: National symbols, capitals, festivals, famous
  //         personalities, basic geography, Tamil Nadu, basic science
  // ═══════════════════════════════════════════════════════════════

  {
    q: "What is the capital of India? 🇮🇳",
    q_ta: "இந்தியாவின் தலைநகரம் என்ன? 🇮🇳",
    options: ["Mumbai", "New Delhi", "Chennai", "Kolkata"],
    options_ta: ["மும்பை", "புது டெல்லி", "சென்னை", "கொல்கத்தா"],
    answer: "New Delhi",
    answer_ta: "புது டெல்லி",
    classRange: [3, 4],
  },
  {
    q: "Who is known as the Father of the Nation of India?",
    q_ta: "இந்தியாவின் தேசத்தந்தை என்று அழைக்கப்படுபவர் யார்?",
    options: ["Jawaharlal Nehru", "Mahatma Gandhi", "Subhas Chandra Bose", "Sardar Patel"],
    options_ta: ["ஜவஹர்லால் நேரு", "மகாத்மா காந்தி", "சுபாஷ் சந்திர போஸ்", "சர்தார் படேல்"],
    answer: "Mahatma Gandhi",
    answer_ta: "மகாத்மா காந்தி",
    classRange: [3, 4],
  },
  {
    q: "What is the national bird of India? 🦚",
    q_ta: "இந்தியாவின் தேசியப் பறவை எது? 🦚",
    options: ["Parrot", "Peacock", "Pigeon", "Eagle"],
    options_ta: ["கிளி", "மயில்", "புறா", "கழுகு"],
    answer: "Peacock",
    answer_ta: "மயில்",
    classRange: [3, 4],
  },
  {
    q: "What is the national animal of India? 🐅",
    q_ta: "இந்தியாவின் தேசிய விலங்கு எது? 🐅",
    options: ["Lion", "Elephant", "Tiger", "Deer"],
    options_ta: ["சிங்கம்", "யானை", "புலி", "மான்"],
    answer: "Tiger",
    answer_ta: "புலி",
    classRange: [3, 4],
  },
  {
    q: "What is the national flower of India? 🌸",
    q_ta: "இந்தியாவின் தேசிய மலர் எது? 🌸",
    options: ["Rose", "Lotus", "Jasmine", "Sunflower"],
    options_ta: ["ரோஜா", "தாமரை", "மல்லிகை", "சூரியகாந்தி"],
    answer: "Lotus",
    answer_ta: "தாமரை",
    classRange: [3, 4],
  },
  {
    q: "How many colors are there in the Indian national flag?",
    q_ta: "இந்திய தேசியக் கொடியில் எத்தனை நிறங்கள் உள்ளன?",
    options: ["2", "3", "4", "5"],
    options_ta: ["2", "3", "4", "5"],
    answer: "3",
    answer_ta: "3",
    classRange: [3, 4],
  },
  {
    q: "What is the capital of Tamil Nadu?",
    q_ta: "தமிழ்நாட்டின் தலைநகரம் என்ன?",
    options: ["Madurai", "Coimbatore", "Chennai", "Trichy"],
    options_ta: ["மதுரை", "கோயம்புத்தூர்", "சென்னை", "திருச்சி"],
    answer: "Chennai",
    answer_ta: "சென்னை",
    classRange: [3, 4],
  },
  {
    q: "Which festival is the harvest festival of Tamil Nadu? 🌾",
    q_ta: "தமிழ்நாட்டின் அறுவடை திருநாள் எது? 🌾",
    options: ["Diwali", "Pongal", "Holi", "Onam"],
    options_ta: ["தீபாவளி", "பொங்கல்", "ஹோலி", "ஓணம்"],
    answer: "Pongal",
    answer_ta: "பொங்கல்",
    classRange: [3, 4],
  },
  {
    q: "How many continents are there in the world? 🌍",
    q_ta: "உலகில் எத்தனை கண்டங்கள் உள்ளன? 🌍",
    options: ["5", "6", "7", "8"],
    options_ta: ["5", "6", "7", "8"],
    answer: "7",
    answer_ta: "7",
    classRange: [3, 4],
  },
  {
    q: "Which planet is closest to the Sun? ☀️",
    q_ta: "சூரியனுக்கு மிக அருகில் உள்ள கிரகம் எது? ☀️",
    options: ["Venus", "Earth", "Mercury", "Mars"],
    options_ta: ["வெள்ளி", "பூமி", "புதன்", "செவ்வாய்"],
    answer: "Mercury",
    answer_ta: "புதன்",
    classRange: [3, 4],
  },
  {
    q: "What gas do plants absorb from the air? 🌱",
    q_ta: "தாவரங்கள் காற்றிலிருந்து எந்த வாயுவை உறிஞ்சுகின்றன? 🌱",
    options: ["Oxygen", "Nitrogen", "Carbon Dioxide", "Hydrogen"],
    options_ta: ["ஆக்சிஜன்", "நைட்ரஜன்", "கார்பன் டை ஆக்சைடு", "ஹைட்ரஜன்"],
    answer: "Carbon Dioxide",
    answer_ta: "கார்பன் டை ஆக்சைடு",
    classRange: [3, 4],
  },
  {
    q: "What is the largest ocean in the world? 🌊",
    q_ta: "உலகின் மிகப்பெரிய பெருங்கடல் எது? 🌊",
    options: ["Atlantic", "Indian", "Pacific", "Arctic"],
    options_ta: ["அட்லாண்டிக்", "இந்தியப் பெருங்கடல்", "பசிபிக்", "ஆர்க்டிக்"],
    answer: "Pacific",
    answer_ta: "பசிபிக்",
    classRange: [3, 4],
  },
  {
    q: "How many days are in a leap year?",
    q_ta: "ஒரு லீப் ஆண்டில் எத்தனை நாட்கள் உள்ளன?",
    options: ["364", "365", "366", "367"],
    options_ta: ["364", "365", "366", "367"],
    answer: "366",
    answer_ta: "366",
    classRange: [3, 4],
  },
  {
    q: "Which direction does the Sun rise from? 🌅",
    q_ta: "சூரியன் எந்த திசையில் உதிக்கிறது? 🌅",
    options: ["West", "North", "East", "South"],
    options_ta: ["மேற்கு", "வடக்கு", "கிழக்கு", "தெற்கு"],
    answer: "East",
    answer_ta: "கிழக்கு",
    classRange: [3, 4],
  },
  {
    q: "Who invented the light bulb? 💡",
    q_ta: "மின் விளக்கைக் கண்டுபிடித்தவர் யார்? 💡",
    options: ["Isaac Newton", "Albert Einstein", "Thomas Edison", "Alexander Graham Bell"],
    options_ta: ["ஐசக் நியூட்டன்", "ஆல்பர்ட் ஐன்ஸ்டீன்", "தாமஸ் எடிசன்", "அலெக்சாண்டர் கிரஹாம் பெல்"],
    answer: "Thomas Edison",
    answer_ta: "தாமஸ் எடிசன்",
    classRange: [3, 4],
  },
  {
    q: "Which is the national fruit of India? 🥭",
    q_ta: "இந்தியாவின் தேசியப் பழம் எது? 🥭",
    options: ["Banana", "Mango", "Apple", "Guava"],
    options_ta: ["வாழைப்பழம்", "மாம்பழம்", "ஆப்பிள்", "கொய்யா"],
    answer: "Mango",
    answer_ta: "மாம்பழம்",
    classRange: [3, 4],
  },
  {
    q: "How many bones does an adult human body have? 🦴",
    q_ta: "ஒரு பெரியவரின் உடலில் எத்தனை எலும்புகள் உள்ளன? 🦴",
    options: ["106", "206", "306", "186"],
    options_ta: ["106", "206", "306", "186"],
    answer: "206",
    answer_ta: "206",
    classRange: [3, 4],
  },

  // ═══════════════════════════════════════════════════════════════
  // GRADE 5-6 (classRange: [5, 6]) — 17 questions
  // Topics: World geography, inventions, Indian history, rivers,
  //         mountains, space, science, famous people
  // ═══════════════════════════════════════════════════════════════

  {
    q: "Who invented the telephone? 📞",
    q_ta: "தொலைபேசியைக் கண்டுபிடித்தவர் யார்? 📞",
    options: ["Thomas Edison", "Alexander Graham Bell", "Nikola Tesla", "Guglielmo Marconi"],
    options_ta: ["தாமஸ் எடிசன்", "அலெக்சாண்டர் கிரஹாம் பெல்", "நிகோலா டெஸ்லா", "குல்யெல்மோ மார்கோனி"],
    answer: "Alexander Graham Bell",
    answer_ta: "அலெக்சாண்டர் கிரஹாம் பெல்",
    classRange: [5, 6],
  },
  {
    q: "Which is the longest river in India?",
    q_ta: "இந்தியாவின் நீளமான ஆறு எது?",
    options: ["Yamuna", "Godavari", "Ganga", "Brahmaputra"],
    options_ta: ["யமுனா", "கோதாவரி", "கங்கை", "பிரம்மபுத்ரா"],
    answer: "Ganga",
    answer_ta: "கங்கை",
    classRange: [5, 6],
  },
  {
    q: "Which is the tallest mountain in the world? 🏔️",
    q_ta: "உலகின் மிக உயரமான மலை எது? 🏔️",
    options: ["K2", "Kangchenjunga", "Mount Everest", "Mount Kilimanjaro"],
    options_ta: ["K2", "கஞ்சன்ஜங்கா", "எவரெஸ்ட் மலை", "கிலிமஞ்சாரோ மலை"],
    answer: "Mount Everest",
    answer_ta: "எவரெஸ்ட் மலை",
    classRange: [5, 6],
  },
  {
    q: "Which planet is known as the Red Planet? 🔴",
    q_ta: "எந்த கிரகம் சிவப்பு கிரகம் என்று அழைக்கப்படுகிறது? 🔴",
    options: ["Venus", "Mars", "Jupiter", "Saturn"],
    options_ta: ["வெள்ளி", "செவ்வாய்", "வியாழன்", "சனி"],
    answer: "Mars",
    answer_ta: "செவ்வாய்",
    classRange: [5, 6],
  },
  {
    q: "In which year did India gain independence? 🇮🇳",
    q_ta: "இந்தியா எந்த ஆண்டு சுதந்திரம் பெற்றது? 🇮🇳",
    options: ["1942", "1945", "1947", "1950"],
    options_ta: ["1942", "1945", "1947", "1950"],
    answer: "1947",
    answer_ta: "1947",
    classRange: [5, 6],
  },
  {
    q: "Who was the first Prime Minister of India?",
    q_ta: "இந்தியாவின் முதல் பிரதமர் யார்?",
    options: ["Mahatma Gandhi", "Jawaharlal Nehru", "Sardar Patel", "Dr. Rajendra Prasad"],
    options_ta: ["மகாத்மா காந்தி", "ஜவஹர்லால் நேரு", "சர்தார் படேல்", "டாக்டர் ராஜேந்திர பிரசாத்"],
    answer: "Jawaharlal Nehru",
    answer_ta: "ஜவஹர்லால் நேரு",
    classRange: [5, 6],
  },
  {
    q: "Which is the smallest continent in the world?",
    q_ta: "உலகின் மிகச்சிறிய கண்டம் எது?",
    options: ["Europe", "Australia", "Antarctica", "South America"],
    options_ta: ["ஐரோப்பா", "ஆஸ்திரேலியா", "அண்டார்டிகா", "தென் அமெரிக்கா"],
    answer: "Australia",
    answer_ta: "ஆஸ்திரேலியா",
    classRange: [5, 6],
  },
  {
    q: "What is the largest hot desert in the world? 🏜️",
    q_ta: "உலகின் மிகப்பெரிய வெப்பப் பாலைவனம் எது? 🏜️",
    options: ["Gobi", "Kalahari", "Thar", "Sahara"],
    options_ta: ["கோபி", "கலஹாரி", "தார்", "சஹாரா"],
    answer: "Sahara",
    answer_ta: "சஹாரா",
    classRange: [5, 6],
  },
  {
    q: "Who wrote the Indian national anthem? 🎵",
    q_ta: "இந்திய தேசிய கீதத்தை எழுதியவர் யார்? 🎵",
    options: ["Mahatma Gandhi", "Rabindranath Tagore", "Subhas Chandra Bose", "Bankim Chandra Chatterjee"],
    options_ta: ["மகாத்மா காந்தி", "ரவீந்திரநாத் தாகூர்", "சுபாஷ் சந்திர போஸ்", "பங்கிம் சந்திர சட்டர்ஜி"],
    answer: "Rabindranath Tagore",
    answer_ta: "ரவீந்திரநாத் தாகூர்",
    classRange: [5, 6],
  },
  {
    q: "What is the boiling point of water? 🌡️",
    q_ta: "நீரின் கொதிநிலை என்ன? 🌡️",
    options: ["50°C", "75°C", "100°C", "120°C"],
    options_ta: ["50°C", "75°C", "100°C", "120°C"],
    answer: "100°C",
    answer_ta: "100°C",
    classRange: [5, 6],
  },
  {
    q: "Which is the longest river in the world?",
    q_ta: "உலகின் மிக நீளமான ஆறு எது?",
    options: ["Amazon", "Nile", "Yangtze", "Mississippi"],
    options_ta: ["அமேசான்", "நைல்", "யாங்ட்சி", "மிசிசிப்பி"],
    answer: "Nile",
    answer_ta: "நைல்",
    classRange: [5, 6],
  },
  {
    q: "Who discovered gravity? 🍎",
    q_ta: "புவியீர்ப்பு விசையைக் கண்டுபிடித்தவர் யார்? 🍎",
    options: ["Albert Einstein", "Isaac Newton", "Galileo Galilei", "Thomas Edison"],
    options_ta: ["ஆல்பர்ட் ஐன்ஸ்டீன்", "ஐசக் நியூட்டன்", "கலிலியோ கலிலி", "தாமஸ் எடிசன்"],
    answer: "Isaac Newton",
    answer_ta: "ஐசக் நியூட்டன்",
    classRange: [5, 6],
  },
  {
    q: "Which organ pumps blood in the human body? ❤️",
    q_ta: "மனித உடலில் இரத்தத்தை செலுத்தும் உறுப்பு எது? ❤️",
    options: ["Brain", "Lungs", "Heart", "Liver"],
    options_ta: ["மூளை", "நுரையீரல்", "இதயம்", "கல்லீரல்"],
    answer: "Heart",
    answer_ta: "இதயம்",
    classRange: [5, 6],
  },
  {
    q: "Which famous Tamil poet wrote 'Thirukkural'? 📜",
    q_ta: "புகழ்பெற்ற 'திருக்குறள்' நூலை எழுதிய தமிழ் கவிஞர் யார்? 📜",
    options: ["Bharathiar", "Thiruvalluvar", "Kambar", "Avvaiyar"],
    options_ta: ["பாரதியார்", "திருவள்ளுவர்", "கம்பர்", "ஔவையார்"],
    answer: "Thiruvalluvar",
    answer_ta: "திருவள்ளுவர்",
    classRange: [5, 6],
  },
  {
    q: "What is H₂O commonly known as? 💧",
    q_ta: "H₂O என்பது பொதுவாக எவ்வாறு அழைக்கப்படுகிறது? 💧",
    options: ["Salt", "Sugar", "Water", "Acid"],
    options_ta: ["உப்பு", "சர்க்கரை", "நீர்", "அமிலம்"],
    answer: "Water",
    answer_ta: "நீர்",
    classRange: [5, 6],
  },
  {
    q: "Which Indian city is known as the 'Pink City'? 🏙️",
    q_ta: "எந்த இந்திய நகரம் 'இளஞ்சிவப்பு நகரம்' என்று அழைக்கப்படுகிறது? 🏙️",
    options: ["Udaipur", "Jaipur", "Jodhpur", "Delhi"],
    options_ta: ["உதய்பூர்", "ஜெய்ப்பூர்", "ஜோத்பூர்", "டெல்லி"],
    answer: "Jaipur",
    answer_ta: "ஜெய்ப்பூர்",
    classRange: [5, 6],
  },
  {
    q: "How many players are in a cricket team? 🏏",
    q_ta: "ஒரு கிரிக்கெட் அணியில் எத்தனை வீரர்கள் உள்ளனர்? 🏏",
    options: ["9", "10", "11", "12"],
    options_ta: ["9", "10", "11", "12"],
    answer: "11",
    answer_ta: "11",
    classRange: [5, 6],
  },

  // ═══════════════════════════════════════════════════════════════
  // GRADE 7-8 (classRange: [7, 8]) — 17 questions
  // Topics: World history, economics basics, Indian constitution,
  //         famous scientists, chemistry, physics, advanced geography
  // ═══════════════════════════════════════════════════════════════

  {
    q: "What is the chemical symbol for Gold? 🥇",
    q_ta: "தங்கத்தின் வேதியியல் குறியீடு என்ன? 🥇",
    options: ["Go", "Gd", "Au", "Ag"],
    options_ta: ["Go", "Gd", "Au", "Ag"],
    answer: "Au",
    answer_ta: "Au",
    classRange: [7, 8],
  },
  {
    q: "Who wrote the Indian Constitution? 📜",
    q_ta: "இந்திய அரசியலமைப்பை எழுதியவர் யார்? 📜",
    options: ["Mahatma Gandhi", "Dr. B.R. Ambedkar", "Jawaharlal Nehru", "Sardar Patel"],
    options_ta: ["மகாத்மா காந்தி", "டாக்டர் பி.ஆர். அம்பேத்கர்", "ஜவஹர்லால் நேரு", "சர்தார் படேல்"],
    answer: "Dr. B.R. Ambedkar",
    answer_ta: "டாக்டர் பி.ஆர். அம்பேத்கர்",
    classRange: [7, 8],
  },
  {
    q: "What is the speed of light approximately? ⚡",
    q_ta: "ஒளியின் வேகம் தோராயமாக என்ன? ⚡",
    options: ["3 × 10⁶ m/s", "3 × 10⁸ m/s", "3 × 10⁴ m/s", "3 × 10¹⁰ m/s"],
    options_ta: ["3 × 10⁶ m/s", "3 × 10⁸ m/s", "3 × 10⁴ m/s", "3 × 10¹⁰ m/s"],
    answer: "3 × 10⁸ m/s",
    answer_ta: "3 × 10⁸ m/s",
    classRange: [7, 8],
  },
  {
    q: "Which gas is most abundant in Earth's atmosphere?",
    q_ta: "பூமியின் வளிமண்டலத்தில் அதிகமாக உள்ள வாயு எது?",
    options: ["Oxygen", "Carbon Dioxide", "Nitrogen", "Argon"],
    options_ta: ["ஆக்சிஜன்", "கார்பன் டை ஆக்சைடு", "நைட்ரஜன்", "ஆர்கான்"],
    answer: "Nitrogen",
    answer_ta: "நைட்ரஜன்",
    classRange: [7, 8],
  },
  {
    q: "What is the chemical formula for table salt?",
    q_ta: "உப்பின் வேதியியல் வாய்ப்பாடு என்ன?",
    options: ["NaOH", "NaCl", "KCl", "HCl"],
    options_ta: ["NaOH", "NaCl", "KCl", "HCl"],
    answer: "NaCl",
    answer_ta: "NaCl",
    classRange: [7, 8],
  },
  {
    q: "Who discovered penicillin? 💊",
    q_ta: "பென்சிலினைக் கண்டுபிடித்தவர் யார்? 💊",
    options: ["Marie Curie", "Louis Pasteur", "Alexander Fleming", "Edward Jenner"],
    options_ta: ["மேரி கியூரி", "லூயி பாஸ்டர்", "அலெக்சாண்டர் ஃபிளெமிங்", "எட்வர்ட் ஜென்னர்"],
    answer: "Alexander Fleming",
    answer_ta: "அலெக்சாண்டர் ஃபிளெமிங்",
    classRange: [7, 8],
  },
  {
    q: "Which country is known as the 'Land of the Rising Sun'? 🌅",
    q_ta: "எந்த நாடு 'உதயசூரியன் நாடு' என்று அழைக்கப்படுகிறது? 🌅",
    options: ["China", "Japan", "South Korea", "Thailand"],
    options_ta: ["சீனா", "ஜப்பான்", "தென் கொரியா", "தாய்லாந்து"],
    answer: "Japan",
    answer_ta: "ஜப்பான்",
    classRange: [7, 8],
  },
  {
    q: "What is the SI unit of force?",
    q_ta: "விசையின் SI அலகு என்ன?",
    options: ["Joule", "Watt", "Newton", "Pascal"],
    options_ta: ["ஜூல்", "வாட்", "நியூட்டன்", "பாஸ்கல்"],
    answer: "Newton",
    answer_ta: "நியூட்டன்",
    classRange: [7, 8],
  },
  {
    q: "In which year was the United Nations established?",
    q_ta: "ஐக்கிய நாடுகள் சபை எந்த ஆண்டு நிறுவப்பட்டது?",
    options: ["1940", "1945", "1950", "1955"],
    options_ta: ["1940", "1945", "1950", "1955"],
    answer: "1945",
    answer_ta: "1945",
    classRange: [7, 8],
  },
  {
    q: "Which is the hardest natural substance on Earth? 💎",
    q_ta: "பூமியில் உள்ள மிகக் கடினமான இயற்கைப் பொருள் எது? 💎",
    options: ["Gold", "Iron", "Diamond", "Platinum"],
    options_ta: ["தங்கம்", "இரும்பு", "வைரம்", "பிளாட்டினம்"],
    answer: "Diamond",
    answer_ta: "வைரம்",
    classRange: [7, 8],
  },
  {
    q: "What is the currency of Japan? 💴",
    q_ta: "ஜப்பானின் நாணயம் என்ன? 💴",
    options: ["Won", "Yuan", "Yen", "Ringgit"],
    options_ta: ["வான்", "யுவான்", "யென்", "ரிங்கிட்"],
    answer: "Yen",
    answer_ta: "யென்",
    classRange: [7, 8],
  },
  {
    q: "Who proposed the theory of relativity? 🧠",
    q_ta: "சார்பியல் கோட்பாட்டை முன்மொழிந்தவர் யார்? 🧠",
    options: ["Isaac Newton", "Niels Bohr", "Albert Einstein", "Stephen Hawking"],
    options_ta: ["ஐசக் நியூட்டன்", "நீல்ஸ் போர்", "ஆல்பர்ட் ஐன்ஸ்டீன்", "ஸ்டீபன் ஹாக்கிங்"],
    answer: "Albert Einstein",
    answer_ta: "ஆல்பர்ட் ஐன்ஸ்டீன்",
    classRange: [7, 8],
  },
  {
    q: "What does GDP stand for? 📊",
    q_ta: "GDP என்பதன் விரிவாக்கம் என்ன? 📊",
    options: ["Gross Domestic Product", "General Domestic Price", "Grand Development Plan", "Global Domestic Production"],
    options_ta: ["மொத்த உள்நாட்டு உற்பத்தி", "பொது உள்நாட்டு விலை", "பெரிய வளர்ச்சி திட்டம்", "உலகளாவிய உள்நாட்டு உற்பத்தி"],
    answer: "Gross Domestic Product",
    answer_ta: "மொத்த உள்நாட்டு உற்பத்தி",
    classRange: [7, 8],
  },
  {
    q: "Which vitamin is produced when sunlight falls on the skin?",
    q_ta: "சூரிய ஒளி தோலின் மீது படும்போது எந்த வைட்டமின் உற்பத்தி ஆகிறது?",
    options: ["Vitamin A", "Vitamin B", "Vitamin C", "Vitamin D"],
    options_ta: ["வைட்டமின் A", "வைட்டமின் B", "வைட்டமின் C", "வைட்டமின் D"],
    answer: "Vitamin D",
    answer_ta: "வைட்டமின் D",
    classRange: [7, 8],
  },
  {
    q: "What is the chemical symbol for Iron?",
    q_ta: "இரும்பின் வேதியியல் குறியீடு என்ன?",
    options: ["Ir", "Fe", "In", "Fn"],
    options_ta: ["Ir", "Fe", "In", "Fn"],
    answer: "Fe",
    answer_ta: "Fe",
    classRange: [7, 8],
  },
  {
    q: "Which Indian scientist was known as the 'Missile Man of India'? 🚀",
    q_ta: "எந்த இந்திய விஞ்ஞானி 'இந்தியாவின் ஏவுகணை மனிதர்' என்று அழைக்கப்பட்டார்? 🚀",
    options: ["C.V. Raman", "Homi Bhabha", "A.P.J. Abdul Kalam", "Vikram Sarabhai"],
    options_ta: ["சி.வி. ராமன்", "ஹோமி பாபா", "ஏ.பி.ஜே. அப்துல் கலாம்", "விக்ரம் சாராபாய்"],
    answer: "A.P.J. Abdul Kalam",
    answer_ta: "ஏ.பி.ஜே. அப்துல் கலாம்",
    classRange: [7, 8],
  },
  {
    q: "What is the longest bone in the human body? 🦴",
    q_ta: "மனித உடலில் உள்ள நீளமான எலும்பு எது? 🦴",
    options: ["Humerus", "Femur", "Tibia", "Fibula"],
    options_ta: ["மேற்கை எலும்பு", "தொடை எலும்பு", "கால் எலும்பு", "கால் மெல்லிய எலும்பு"],
    answer: "Femur",
    answer_ta: "தொடை எலும்பு",
    classRange: [7, 8],
  },
];
