// ── Vocabulary Word Bank (bilingual, class-tagged, 4 grade bands) ──
// Each entry: word + Tamil, meaning + Tamil, 4 options + Tamil, classRange
// Grade bands: [1,2] Beginner, [3,4] Intermediate, [5,6] Advanced, [7,8] Expert

export const VOCAB_WORDS_BANK: {
  word: string;
  word_ta: string;
  meaning: string;
  meaning_ta: string;
  options: string[];
  options_ta: string[];
  classRange: [number, number];
}[] = [

  // ═══════════════════════════════════════════════════════════════
  // GRADE 1-2 (Beginner) — Basic adjectives, simple nouns, common verbs
  // ═══════════════════════════════════════════════════════════════

  {
    word: "Big",
    word_ta: "பெரிய",
    meaning: "Large in size",
    meaning_ta: "அளவில் பெரிய",
    options: ["Large in size", "Very small", "Moving fast", "Round in shape"],
    options_ta: ["அளவில் பெரிய", "மிகவும் சிறிய", "வேகமாக நகரும்", "உருண்டை வடிவம்"],
    classRange: [1, 2],
  },
  {
    word: "Small",
    word_ta: "சிறிய",
    meaning: "Little in size",
    meaning_ta: "அளவில் சிறிய",
    options: ["Very tall", "Little in size", "Very loud", "Very heavy"],
    options_ta: ["மிகவும் உயரமான", "அளவில் சிறிய", "மிகவும் சத்தமான", "மிகவும் கனமான"],
    classRange: [1, 2],
  },
  {
    word: "Happy",
    word_ta: "மகிழ்ச்சியான",
    meaning: "Feeling joy",
    meaning_ta: "மகிழ்வாக உணர்தல்",
    options: ["Feeling sad", "Feeling joy", "Feeling angry", "Feeling sleepy"],
    options_ta: ["சோகமாக உணர்தல்", "மகிழ்வாக உணர்தல்", "கோபமாக உணர்தல்", "தூக்கமாக உணர்தல்"],
    classRange: [1, 2],
  },
  {
    word: "Sad",
    word_ta: "சோகமான",
    meaning: "Feeling unhappy",
    meaning_ta: "மகிழ்ச்சியின்றி உணர்தல்",
    options: ["Feeling unhappy", "Feeling brave", "Very fast", "Very bright"],
    options_ta: ["மகிழ்ச்சியின்றி உணர்தல்", "தைரியமாக உணர்தல்", "மிகவும் வேகமான", "மிகவும் பிரகாசமான"],
    classRange: [1, 2],
  },
  {
    word: "Run",
    word_ta: "ஓடு",
    meaning: "Move quickly on foot",
    meaning_ta: "கால்களால் வேகமாக நகர்தல்",
    options: ["Sit quietly", "Move quickly on foot", "Sleep well", "Eat food"],
    options_ta: ["அமைதியாக உட்கார்தல்", "கால்களால் வேகமாக நகர்தல்", "நன்றாகத் தூங்குதல்", "உணவு சாப்பிடுதல்"],
    classRange: [1, 2],
  },
  {
    word: "Eat",
    word_ta: "சாப்பிடு",
    meaning: "Put food in your mouth and swallow",
    meaning_ta: "உணவை வாயில் போட்டு விழுங்குதல்",
    options: ["Drink water", "Throw away", "Put food in your mouth and swallow", "Close your eyes"],
    options_ta: ["தண்ணீர் குடிப்பது", "தூக்கி எறிவது", "உணவை வாயில் போட்டு விழுங்குதல்", "கண்களை மூடுவது"],
    classRange: [1, 2],
  },
  {
    word: "Dog",
    word_ta: "நாய்",
    meaning: "A pet animal that barks",
    meaning_ta: "குரைக்கும் செல்ல விலங்கு",
    options: ["A pet animal that barks", "A bird that flies", "A fish in water", "An insect that buzzes"],
    options_ta: ["குரைக்கும் செல்ல விலங்கு", "பறக்கும் பறவை", "நீரில் மீன்", "ரீங்காரமிடும் பூச்சி"],
    classRange: [1, 2],
  },
  {
    word: "Cat",
    word_ta: "பூனை",
    meaning: "A soft pet animal that meows",
    meaning_ta: "மியாவ் என்று கத்தும் மென்மையான செல்ல விலங்கு",
    options: ["A tall tree", "A soft pet animal that meows", "A big rock", "A red flower"],
    options_ta: ["ஒரு உயரமான மரம்", "மியாவ் என்று கத்தும் மென்மையான செல்ல விலங்கு", "ஒரு பெரிய பாறை", "ஒரு சிவப்பு பூ"],
    classRange: [1, 2],
  },
  {
    word: "Hot",
    word_ta: "சூடான",
    meaning: "Having a high temperature",
    meaning_ta: "அதிக வெப்பநிலை கொண்ட",
    options: ["Very cold", "Having a high temperature", "Very dark", "Very quiet"],
    options_ta: ["மிகவும் குளிர்ந்த", "அதிக வெப்பநிலை கொண்ட", "மிகவும் இருட்டான", "மிகவும் அமைதியான"],
    classRange: [1, 2],
  },
  {
    word: "Cold",
    word_ta: "குளிர்ந்த",
    meaning: "Having a low temperature",
    meaning_ta: "குறைந்த வெப்பநிலை கொண்ட",
    options: ["Having a low temperature", "Very bright", "Very loud", "Very fast"],
    options_ta: ["குறைந்த வெப்பநிலை கொண்ட", "மிகவும் பிரகாசமான", "மிகவும் சத்தமான", "மிகவும் வேகமான"],
    classRange: [1, 2],
  },
  {
    word: "Tall",
    word_ta: "உயரமான",
    meaning: "High in height",
    meaning_ta: "உயரம் அதிகமுள்ள",
    options: ["Very short", "High in height", "Very wide", "Very thin"],
    options_ta: ["மிகவும் குட்டையான", "உயரம் அதிகமுள்ள", "மிகவும் அகலமான", "மிகவும் மெல்லிய"],
    classRange: [1, 2],
  },
  {
    word: "Sweet",
    word_ta: "இனிப்பான",
    meaning: "Having a sugary taste",
    meaning_ta: "சர்க்கரை சுவை கொண்ட",
    options: ["Having a sugary taste", "Very sour", "Very bitter", "Very salty"],
    options_ta: ["சர்க்கரை சுவை கொண்ட", "மிகவும் புளிப்பான", "மிகவும் கசப்பான", "மிகவும் உப்பான"],
    classRange: [1, 2],
  },
  {
    word: "Wet",
    word_ta: "ஈரமான",
    meaning: "Covered with water or liquid",
    meaning_ta: "நீர் அல்லது திரவத்தால் மூடப்பட்ட",
    options: ["Very dry", "Covered with water or liquid", "Very hard", "Very soft"],
    options_ta: ["மிகவும் உலர்ந்த", "நீர் அல்லது திரவத்தால் மூடப்பட்ட", "மிகவும் கடினமான", "மிகவும் மென்மையான"],
    classRange: [1, 2],
  },
  {
    word: "Sleep",
    word_ta: "தூங்கு",
    meaning: "Rest with eyes closed",
    meaning_ta: "கண்களை மூடி ஓய்வெடுத்தல்",
    options: ["Jump high", "Sing a song", "Rest with eyes closed", "Write a letter"],
    options_ta: ["உயரமாகக் குதிப்பது", "ஒரு பாடல் பாடுவது", "கண்களை மூடி ஓய்வெடுத்தல்", "ஒரு கடிதம் எழுதுவது"],
    classRange: [1, 2],
  },
  {
    word: "Laugh",
    word_ta: "சிரி",
    meaning: "Make happy sounds when something is funny",
    meaning_ta: "வேடிக்கையாக இருக்கும்போது மகிழ்ச்சி ஒலி எழுப்புதல்",
    options: ["Cry loudly", "Make happy sounds when something is funny", "Stand still", "Feel afraid"],
    options_ta: ["சத்தமாக அழுவது", "வேடிக்கையாக இருக்கும்போது மகிழ்ச்சி ஒலி எழுப்புதல்", "அசையாமல் நிற்பது", "பயப்படுவது"],
    classRange: [1, 2],
  },
  {
    word: "Fly",
    word_ta: "பற",
    meaning: "Move through the air with wings",
    meaning_ta: "இறக்கைகளால் காற்றில் நகர்தல்",
    options: ["Swim in water", "Move through the air with wings", "Dig in the ground", "Climb a tree"],
    options_ta: ["நீரில் நீந்துவது", "இறக்கைகளால் காற்றில் நகர்தல்", "நிலத்தை தோண்டுவது", "மரத்தில் ஏறுவது"],
    classRange: [1, 2],
  },

  // ═══════════════════════════════════════════════════════════════
  // GRADE 3-4 (Intermediate) — Intermediate words with richer meanings
  // ═══════════════════════════════════════════════════════════════

  {
    word: "Enormous",
    word_ta: "மகத்தான",
    meaning: "Extremely large in size",
    meaning_ta: "மிகவும் பெரிய அளவிலான",
    options: ["Very tiny", "Extremely large in size", "Very fast", "Very colourful"],
    options_ta: ["மிகச்சிறிய", "மிகவும் பெரிய அளவிலான", "மிகவும் வேகமான", "மிகவும் வண்ணமயமான"],
    classRange: [3, 4],
  },
  {
    word: "Brave",
    word_ta: "தைரியமான",
    meaning: "Ready to face danger without fear",
    meaning_ta: "பயமின்றி ஆபத்தை எதிர்கொள்ள தயாராக இருப்பது",
    options: ["Very scared", "Ready to face danger without fear", "Very lazy", "Very hungry"],
    options_ta: ["மிகவும் பயந்த", "பயமின்றி ஆபத்தை எதிர்கொள்ள தயாராக இருப்பது", "மிகவும் சோம்பேறி", "மிகவும் பசியுள்ள"],
    classRange: [3, 4],
  },
  {
    word: "Ancient",
    word_ta: "பண்டைய",
    meaning: "Belonging to the very distant past",
    meaning_ta: "மிகவும் தொலைதூர கடந்த காலத்தைச் சேர்ந்த",
    options: ["Brand new", "Belonging to the very distant past", "Very shiny", "Very quiet"],
    options_ta: ["புத்தம்புதிய", "மிகவும் தொலைதூர கடந்த காலத்தைச் சேர்ந்த", "மிகவும் பளபளப்பான", "மிகவும் அமைதியான"],
    classRange: [3, 4],
  },
  {
    word: "Fragile",
    word_ta: "உடையக்கூடிய",
    meaning: "Easily broken or damaged",
    meaning_ta: "எளிதில் உடையக்கூடிய அல்லது சேதமடையக்கூடிய",
    options: ["Very strong", "Easily broken or damaged", "Very heavy", "Very large"],
    options_ta: ["மிகவும் வலுவான", "எளிதில் உடையக்கூடிய அல்லது சேதமடையக்கூடிய", "மிகவும் கனமான", "மிகவும் பெரிய"],
    classRange: [3, 4],
  },
  {
    word: "Curious",
    word_ta: "ஆர்வமுள்ள",
    meaning: "Eager to know or learn something",
    meaning_ta: "ஒன்றை அறிய அல்லது கற்க ஆவலாக இருப்பது",
    options: ["Bored and tired", "Eager to know or learn something", "Very angry", "Extremely sleepy"],
    options_ta: ["சலிப்பானதும் சோர்வானதும்", "ஒன்றை அறிய அல்லது கற்க ஆவலாக இருப்பது", "மிகவும் கோபமான", "மிகவும் தூக்கமான"],
    classRange: [3, 4],
  },
  {
    word: "Journey",
    word_ta: "பயணம்",
    meaning: "Travelling from one place to another",
    meaning_ta: "ஒரு இடத்திலிருந்து மற்றொரு இடத்திற்குச் செல்வது",
    options: ["Staying at home", "Travelling from one place to another", "Cooking food", "Reading a book"],
    options_ta: ["வீட்டிலேயே இருப்பது", "ஒரு இடத்திலிருந்து மற்றொரு இடத்திற்குச் செல்வது", "உணவு சமைப்பது", "புத்தகம் படிப்பது"],
    classRange: [3, 4],
  },
  {
    word: "Discover",
    word_ta: "கண்டுபிடி",
    meaning: "Find something for the first time",
    meaning_ta: "முதல் முறையாக ஒன்றைக் கண்டறிதல்",
    options: ["Lose something", "Hide something", "Find something for the first time", "Break something"],
    options_ta: ["ஒன்றை இழப்பது", "ஒன்றை மறைப்பது", "முதல் முறையாக ஒன்றைக் கண்டறிதல்", "ஒன்றை உடைப்பது"],
    classRange: [3, 4],
  },
  {
    word: "Gentle",
    word_ta: "மென்மையான",
    meaning: "Mild and kind, not rough",
    meaning_ta: "கனிவான மற்றும் அன்பான, கடுமையற்ற",
    options: ["Very rough", "Mild and kind, not rough", "Very loud", "Very fast"],
    options_ta: ["மிகவும் கடுமையான", "கனிவான மற்றும் அன்பான, கடுமையற்ற", "மிகவும் சத்தமான", "மிகவும் வேகமான"],
    classRange: [3, 4],
  },
  {
    word: "Honest",
    word_ta: "நேர்மையான",
    meaning: "Always telling the truth",
    meaning_ta: "எப்போதும் உண்மையைச் சொல்வது",
    options: ["Always telling lies", "Always telling the truth", "Always being quiet", "Always being late"],
    options_ta: ["எப்போதும் பொய் சொல்வது", "எப்போதும் உண்மையைச் சொல்வது", "எப்போதும் அமைதியாக இருப்பது", "எப்போதும் தாமதமாக வருவது"],
    classRange: [3, 4],
  },
  {
    word: "Wealthy",
    word_ta: "செல்வமுள்ள",
    meaning: "Having a lot of money or possessions",
    meaning_ta: "நிறைய பணம் அல்லது சொத்துக்கள் கொண்ட",
    options: ["Very poor", "Having a lot of money or possessions", "Very sick", "Very young"],
    options_ta: ["மிகவும் ஏழையான", "நிறைய பணம் அல்லது சொத்துக்கள் கொண்ட", "மிகவும் நோயுற்ற", "மிகவும் இளம்"],
    classRange: [3, 4],
  },
  {
    word: "Vanish",
    word_ta: "மறை",
    meaning: "Disappear suddenly",
    meaning_ta: "திடீரென மறைந்துவிடுதல்",
    options: ["Appear suddenly", "Disappear suddenly", "Grow bigger", "Make noise"],
    options_ta: ["திடீரென தோன்றுதல்", "திடீரென மறைந்துவிடுதல்", "பெரியதாக வளர்தல்", "சத்தம் எழுப்புதல்"],
    classRange: [3, 4],
  },
  {
    word: "Courage",
    word_ta: "தைரியம்",
    meaning: "The ability to face fear or danger",
    meaning_ta: "பயத்தை அல்லது ஆபத்தை எதிர்கொள்ளும் திறன்",
    options: ["Great weakness", "The ability to face fear or danger", "Extreme laziness", "Deep sadness"],
    options_ta: ["மிகுந்த பலவீனம்", "பயத்தை அல்லது ஆபத்தை எதிர்கொள்ளும் திறன்", "தீவிர சோம்பல்", "ஆழ்ந்த சோகம்"],
    classRange: [3, 4],
  },
  {
    word: "Brilliant",
    word_ta: "புத்திசாலித்தனமான",
    meaning: "Exceptionally clever or talented",
    meaning_ta: "அசாதாரணமான புத்திசாலி அல்லது திறமையான",
    options: ["Very foolish", "Very dull", "Exceptionally clever or talented", "Very slow"],
    options_ta: ["மிகவும் முட்டாள்தனமான", "மிகவும் மந்தமான", "அசாதாரணமான புத்திசாலி அல்லது திறமையான", "மிகவும் மெதுவான"],
    classRange: [3, 4],
  },
  {
    word: "Precious",
    word_ta: "விலையுயர்ந்த",
    meaning: "Of great value; very important",
    meaning_ta: "மிகுந்த மதிப்புள்ள; மிக முக்கியமான",
    options: ["Worthless and cheap", "Of great value; very important", "Very common", "Very boring"],
    options_ta: ["மதிப்பற்ற மற்றும் மலிவான", "மிகுந்த மதிப்புள்ள; மிக முக்கியமான", "மிகவும் சாதாரணமான", "மிகவும் சலிப்பான"],
    classRange: [3, 4],
  },
  {
    word: "Scatter",
    word_ta: "சிதறு",
    meaning: "Throw or spread in different directions",
    meaning_ta: "வெவ்வேறு திசைகளில் தூவுதல் அல்லது பரப்புதல்",
    options: ["Gather together", "Throw or spread in different directions", "Stand still", "Sleep quietly"],
    options_ta: ["ஒன்றாகச் சேர்ப்பது", "வெவ்வேறு திசைகளில் தூவுதல் அல்லது பரப்புதல்", "அசையாமல் நிற்பது", "அமைதியாகத் தூங்குவது"],
    classRange: [3, 4],
  },

  // ═══════════════════════════════════════════════════════════════
  // GRADE 5-6 (Advanced) — Literary and academic vocabulary
  // ═══════════════════════════════════════════════════════════════

  {
    word: "Perseverance",
    word_ta: "விடாமுயற்சி",
    meaning: "Continued effort despite difficulties",
    meaning_ta: "கஷ்டங்கள் இருந்தாலும் தொடர்ந்து முயற்சித்தல்",
    options: ["Giving up easily", "Continued effort despite difficulties", "Being lazy all day", "Avoiding hard work"],
    options_ta: ["எளிதாக விட்டுக்கொடுப்பது", "கஷ்டங்கள் இருந்தாலும் தொடர்ந்து முயற்சித்தல்", "நாள் முழுவதும் சோம்பேறியாக இருப்பது", "கடின வேலையைத் தவிர்ப்பது"],
    classRange: [5, 6],
  },
  {
    word: "Diligent",
    word_ta: "கடினமாக உழைக்கும்",
    meaning: "Showing careful and persistent effort",
    meaning_ta: "கவனமான மற்றும் நிலையான முயற்சியைக் காட்டுவது",
    options: ["Extremely lazy", "Showing careful and persistent effort", "Very careless", "Always confused"],
    options_ta: ["மிகவும் சோம்பேறி", "கவனமான மற்றும் நிலையான முயற்சியைக் காட்டுவது", "மிகவும் கவனக்குறைவான", "எப்போதும் குழப்பமான"],
    classRange: [5, 6],
  },
  {
    word: "Magnificent",
    word_ta: "பிரமாண்டமான",
    meaning: "Extremely beautiful or impressive",
    meaning_ta: "மிகவும் அழகான அல்லது ஈர்க்கக்கூடிய",
    options: ["Very ugly", "Very ordinary", "Extremely beautiful or impressive", "Very small"],
    options_ta: ["மிகவும் அசிங்கமான", "மிகவும் சாதாரணமான", "மிகவும் அழகான அல்லது ஈர்க்கக்கூடிய", "மிகவும் சிறிய"],
    classRange: [5, 6],
  },
  {
    word: "Resilient",
    word_ta: "மீள்திறன் கொண்ட",
    meaning: "Able to recover quickly from difficulties",
    meaning_ta: "கஷ்டங்களிலிருந்து விரைவாக மீள்வதற்கான திறன் கொண்ட",
    options: ["Easily broken", "Able to recover quickly from difficulties", "Always weak", "Very rigid"],
    options_ta: ["எளிதில் உடையக்கூடிய", "கஷ்டங்களிலிருந்து விரைவாக மீள்வதற்கான திறன் கொண்ட", "எப்போதும் பலவீனமான", "மிகவும் கடினமான"],
    classRange: [5, 6],
  },
  {
    word: "Contemplate",
    word_ta: "சிந்தி",
    meaning: "Think deeply about something",
    meaning_ta: "ஒன்றைப் பற்றி ஆழமாகச் சிந்திப்பது",
    options: ["Ignore completely", "Think deeply about something", "Run away quickly", "Shout loudly"],
    options_ta: ["முற்றிலும் புறக்கணிப்பது", "ஒன்றைப் பற்றி ஆழமாகச் சிந்திப்பது", "விரைவாக ஓடுவது", "சத்தமாகக் கத்துவது"],
    classRange: [5, 6],
  },
  {
    word: "Abundant",
    word_ta: "ஏராளமான",
    meaning: "Existing in large quantities; plentiful",
    meaning_ta: "அதிக அளவில் இருப்பது; நிறைவான",
    options: ["Very scarce", "Existing in large quantities; plentiful", "Completely empty", "Extremely rare"],
    options_ta: ["மிகவும் பற்றாக்குறையான", "அதிக அளவில் இருப்பது; நிறைவான", "முற்றிலும் காலியான", "மிகவும் அரிதான"],
    classRange: [5, 6],
  },
  {
    word: "Formidable",
    word_ta: "அச்சுறுத்தும்",
    meaning: "Inspiring fear or respect through strength",
    meaning_ta: "வலிமையின் மூலம் பயம் அல்லது மரியாதையை ஏற்படுத்தும்",
    options: ["Very weak and small", "Inspiring fear or respect through strength", "Extremely boring", "Very friendly"],
    options_ta: ["மிகவும் பலவீனமான மற்றும் சிறிய", "வலிமையின் மூலம் பயம் அல்லது மரியாதையை ஏற்படுத்தும்", "மிகவும் சலிப்பான", "மிகவும் நட்பான"],
    classRange: [5, 6],
  },
  {
    word: "Compassion",
    word_ta: "இரக்கம்",
    meaning: "Deep sympathy and concern for others' suffering",
    meaning_ta: "பிறர் துன்பத்தின் மீது ஆழ்ந்த அனுதாபமும் அக்கறையும்",
    options: ["Deep hatred", "Total indifference", "Deep sympathy and concern for others' suffering", "Great anger"],
    options_ta: ["ஆழ்ந்த வெறுப்பு", "முழு அலட்சியம்", "பிறர் துன்பத்தின் மீது ஆழ்ந்த அனுதாபமும் அக்கறையும்", "பெரும் கோபம்"],
    classRange: [5, 6],
  },
  {
    word: "Elaborate",
    word_ta: "விரிவான",
    meaning: "Detailed and carefully arranged",
    meaning_ta: "விரிவான மற்றும் கவனமாக ஒழுங்கமைக்கப்பட்ட",
    options: ["Very simple", "Detailed and carefully arranged", "Very short", "Completely empty"],
    options_ta: ["மிகவும் எளிமையான", "விரிவான மற்றும் கவனமாக ஒழுங்கமைக்கப்பட்ட", "மிகவும் குறுகிய", "முற்றிலும் காலியான"],
    classRange: [5, 6],
  },
  {
    word: "Flourish",
    word_ta: "செழி",
    meaning: "Grow or develop successfully",
    meaning_ta: "வெற்றிகரமாக வளர்தல் அல்லது முன்னேறுதல்",
    options: ["Wither and die", "Grow or develop successfully", "Stay the same", "Break into pieces"],
    options_ta: ["வாடி இறப்பது", "வெற்றிகரமாக வளர்தல் அல்லது முன்னேறுதல்", "அப்படியே இருப்பது", "துண்டுகளாக உடைவது"],
    classRange: [5, 6],
  },
  {
    word: "Deceive",
    word_ta: "ஏமாற்று",
    meaning: "Trick someone by telling lies",
    meaning_ta: "பொய் சொல்லி ஒருவரை ஏமாற்றுவது",
    options: ["Help someone kindly", "Trick someone by telling lies", "Praise someone greatly", "Teach someone well"],
    options_ta: ["ஒருவருக்கு அன்பாக உதவுவது", "பொய் சொல்லி ஒருவரை ஏமாற்றுவது", "ஒருவரை மிகவும் புகழ்வது", "ஒருவருக்கு நன்றாகக் கற்பிப்பது"],
    classRange: [5, 6],
  },
  {
    word: "Obscure",
    word_ta: "தெளிவற்ற",
    meaning: "Not clearly understood or well known",
    meaning_ta: "தெளிவாக புரிந்துகொள்ளப்படாத அல்லது நன்கு அறியப்படாத",
    options: ["Very famous", "Not clearly understood or well known", "Extremely bright", "Very simple"],
    options_ta: ["மிகவும் புகழ்பெற்ற", "தெளிவாக புரிந்துகொள்ளப்படாத அல்லது நன்கு அறியப்படாத", "மிகவும் பிரகாசமான", "மிகவும் எளிமையான"],
    classRange: [5, 6],
  },
  {
    word: "Adversity",
    word_ta: "துன்பம்",
    meaning: "A difficult or unpleasant situation",
    meaning_ta: "ஒரு கடினமான அல்லது விரும்பத்தகாத சூழ்நிலை",
    options: ["Great happiness", "A difficult or unpleasant situation", "Extreme wealth", "Perfect comfort"],
    options_ta: ["பெரும் மகிழ்ச்சி", "ஒரு கடினமான அல்லது விரும்பத்தகாத சூழ்நிலை", "தீவிர செல்வம்", "சரியான வசதி"],
    classRange: [5, 6],
  },
  {
    word: "Luminous",
    word_ta: "ஒளிரும்",
    meaning: "Giving off light; bright and shining",
    meaning_ta: "ஒளி வீசும்; பிரகாசமான மற்றும் ஒளிர்கின்ற",
    options: ["Completely dark", "Giving off light; bright and shining", "Very quiet", "Very heavy"],
    options_ta: ["முற்றிலும் இருட்டான", "ஒளி வீசும்; பிரகாசமான மற்றும் ஒளிர்கின்ற", "மிகவும் அமைதியான", "மிகவும் கனமான"],
    classRange: [5, 6],
  },
  {
    word: "Endeavour",
    word_ta: "முயற்சி",
    meaning: "Try hard to do or achieve something",
    meaning_ta: "ஒன்றைச் செய்ய அல்லது அடைய கடினமாக முயற்சிப்பது",
    options: ["Give up immediately", "Try hard to do or achieve something", "Ignore a problem", "Sleep all day"],
    options_ta: ["உடனடியாக விட்டுக்கொடுப்பது", "ஒன்றைச் செய்ய அல்லது அடைய கடினமாக முயற்சிப்பது", "ஒரு பிரச்சனையை புறக்கணிப்பது", "நாள் முழுவதும் தூங்குவது"],
    classRange: [5, 6],
  },
  {
    word: "Serene",
    word_ta: "அமைதியான",
    meaning: "Calm, peaceful, and untroubled",
    meaning_ta: "அமைதியான, சாந்தமான மற்றும் கலக்கமற்ற",
    options: ["Very noisy", "Calm, peaceful, and untroubled", "Extremely angry", "Very restless"],
    options_ta: ["மிகவும் சத்தமான", "அமைதியான, சாந்தமான மற்றும் கலக்கமற்ற", "மிகவும் கோபமான", "மிகவும் அமைதியின்மையான"],
    classRange: [5, 6],
  },

  // ═══════════════════════════════════════════════════════════════
  // GRADE 7-8 (Expert) — Complex definitions with nuance
  // ═══════════════════════════════════════════════════════════════

  {
    word: "Ubiquitous",
    word_ta: "எங்கும் நிறைந்த",
    meaning: "Present, appearing, or found everywhere",
    meaning_ta: "எல்லா இடங்களிலும் இருப்பது அல்லது காணப்படுவது",
    options: ["Extremely rare", "Present, appearing, or found everywhere", "Hidden from view", "Found only in one place"],
    options_ta: ["மிகவும் அரிதான", "எல்லா இடங்களிலும் இருப்பது அல்லது காணப்படுவது", "பார்வையிலிருந்து மறைக்கப்பட்ட", "ஒரே இடத்தில் மட்டும் காணப்படும்"],
    classRange: [7, 8],
  },
  {
    word: "Ephemeral",
    word_ta: "நிலையற்ற",
    meaning: "Lasting for a very short time",
    meaning_ta: "மிகக் குறுகிய காலம் மட்டுமே நீடிக்கும்",
    options: ["Lasting forever", "Lasting for a very short time", "Growing larger daily", "Staying completely still"],
    options_ta: ["என்றென்றும் நீடிக்கும்", "மிகக் குறுகிய காலம் மட்டுமே நீடிக்கும்", "தினமும் பெரியதாக வளரும்", "முற்றிலும் அசையாமல் இருக்கும்"],
    classRange: [7, 8],
  },
  {
    word: "Paradox",
    word_ta: "முரண்பாடு",
    meaning: "A statement that seems contradictory but may be true",
    meaning_ta: "முரண்படுவதாகத் தோன்றும் ஆனால் உண்மையாக இருக்கக்கூடிய கூற்று",
    options: ["A simple fact", "A statement that seems contradictory but may be true", "A mathematical formula", "A type of poem"],
    options_ta: ["ஒரு எளிய உண்மை", "முரண்படுவதாகத் தோன்றும் ஆனால் உண்மையாக இருக்கக்கூடிய கூற்று", "ஒரு கணிதச் சூத்திரம்", "ஒரு வகை கவிதை"],
    classRange: [7, 8],
  },
  {
    word: "Benevolent",
    word_ta: "கருணையுள்ள",
    meaning: "Well-meaning, kind, and generous",
    meaning_ta: "நல்ல எண்ணமுள்ள, அன்பான மற்றும் தாராளமான",
    options: ["Cruel and heartless", "Well-meaning, kind, and generous", "Extremely strict", "Completely silent"],
    options_ta: ["கொடூரமான மற்றும் இதயமற்ற", "நல்ல எண்ணமுள்ள, அன்பான மற்றும் தாராளமான", "மிகவும் கண்டிப்பான", "முற்றிலும் அமைதியான"],
    classRange: [7, 8],
  },
  {
    word: "Gregarious",
    word_ta: "கூட்டம் விரும்பும்",
    meaning: "Fond of company; sociable",
    meaning_ta: "மற்றவர்களுடன் இருப்பதை விரும்புவது; சமூகவிரும்பி",
    options: ["Preferring to be alone", "Fond of company; sociable", "Extremely shy", "Very aggressive"],
    options_ta: ["தனிமையை விரும்புவது", "மற்றவர்களுடன் இருப்பதை விரும்புவது; சமூகவிரும்பி", "மிகவும் வெட்கப்படும்", "மிகவும் ஆக்ரோஷமான"],
    classRange: [7, 8],
  },
  {
    word: "Meticulous",
    word_ta: "நுணுக்கமான",
    meaning: "Showing great attention to detail; very careful",
    meaning_ta: "விவரங்களில் மிகுந்த கவனம் செலுத்தும்; மிகவும் கவனமான",
    options: ["Extremely careless", "Showing great attention to detail; very careful", "Very forgetful", "Always in a hurry"],
    options_ta: ["மிகவும் கவனக்குறைவான", "விவரங்களில் மிகுந்த கவனம் செலுத்தும்; மிகவும் கவனமான", "மிகவும் மறதியான", "எப்போதும் அவசரமான"],
    classRange: [7, 8],
  },
  {
    word: "Tenacious",
    word_ta: "விடாப்பிடியான",
    meaning: "Holding firmly to something; very determined",
    meaning_ta: "ஒன்றை உறுதியாகப் பற்றிக்கொள்ளும்; மிகவும் உறுதியான",
    options: ["Easily giving up", "Holding firmly to something; very determined", "Extremely weak", "Very flexible"],
    options_ta: ["எளிதில் விட்டுக்கொடுக்கும்", "ஒன்றை உறுதியாகப் பற்றிக்கொள்ளும்; மிகவும் உறுதியான", "மிகவும் பலவீனமான", "மிகவும் நெகிழக்கூடிய"],
    classRange: [7, 8],
  },
  {
    word: "Eloquent",
    word_ta: "சொல்திறமிக்க",
    meaning: "Fluent and persuasive in speaking or writing",
    meaning_ta: "பேசுவதிலும் எழுதுவதிலும் சரளமான மற்றும் வற்புறுத்தக்கூடிய",
    options: ["Unable to speak clearly", "Fluent and persuasive in speaking or writing", "Speaking very softly", "Always silent"],
    options_ta: ["தெளிவாகப் பேச இயலாத", "பேசுவதிலும் எழுதுவதிலும் சரளமான மற்றும் வற்புறுத்தக்கூடிய", "மிகவும் மெதுவாகப் பேசும்", "எப்போதும் அமைதியான"],
    classRange: [7, 8],
  },
  {
    word: "Ambiguous",
    word_ta: "தெளிவற்ற",
    meaning: "Open to more than one interpretation",
    meaning_ta: "ஒன்றுக்கும் மேற்பட்ட பொருள்களைத் தரக்கூடிய",
    options: ["Perfectly clear", "Open to more than one interpretation", "Extremely detailed", "Very brief"],
    options_ta: ["முற்றிலும் தெளிவான", "ஒன்றுக்கும் மேற்பட்ட பொருள்களைத் தரக்கூடிய", "மிகவும் விரிவான", "மிகவும் சுருக்கமான"],
    classRange: [7, 8],
  },
  {
    word: "Pragmatic",
    word_ta: "நடைமுறையான",
    meaning: "Dealing with things in a practical way",
    meaning_ta: "விஷயங்களை நடைமுறை முறையில் கையாள்வது",
    options: ["Living in a fantasy world", "Dealing with things in a practical way", "Being very emotional", "Ignoring all facts"],
    options_ta: ["கற்பனை உலகில் வாழ்வது", "விஷயங்களை நடைமுறை முறையில் கையாள்வது", "மிகவும் உணர்ச்சிகரமாக இருப்பது", "அனைத்து உண்மைகளையும் புறக்கணிப்பது"],
    classRange: [7, 8],
  },
  {
    word: "Inevitable",
    word_ta: "தவிர்க்க முடியாத",
    meaning: "Certain to happen; unavoidable",
    meaning_ta: "கட்டாயம் நிகழக்கூடிய; தவிர்க்க இயலாத",
    options: ["Easily avoidable", "Certain to happen; unavoidable", "Very unlikely", "Completely optional"],
    options_ta: ["எளிதில் தவிர்க்கக்கூடிய", "கட்டாயம் நிகழக்கூடிய; தவிர்க்க இயலாத", "நிகழ வாய்ப்பில்லாத", "முற்றிலும் விருப்பத்திற்குரிய"],
    classRange: [7, 8],
  },
  {
    word: "Ostentatious",
    word_ta: "ஆடம்பரமான",
    meaning: "Designed to impress; showy display of wealth",
    meaning_ta: "ஈர்க்கும் வகையில் செய்யப்பட்ட; செல்வத்தின் பகட்டான காட்சி",
    options: ["Very modest and simple", "Designed to impress; showy display of wealth", "Extremely humble", "Completely hidden"],
    options_ta: ["மிகவும் அடக்கமான மற்றும் எளிமையான", "ஈர்க்கும் வகையில் செய்யப்பட்ட; செல்வத்தின் பகட்டான காட்சி", "மிகவும் பணிவான", "முற்றிலும் மறைக்கப்பட்ட"],
    classRange: [7, 8],
  },
  {
    word: "Sycophant",
    word_ta: "முகஸ்துதி செய்பவர்",
    meaning: "A person who flatters to gain advantage",
    meaning_ta: "நன்மை பெற புகழ்ச்சி செய்யும் நபர்",
    options: ["An honest critic", "A person who flatters to gain advantage", "A brave warrior", "A skilled teacher"],
    options_ta: ["ஒரு நேர்மையான விமர்சகர்", "நன்மை பெற புகழ்ச்சி செய்யும் நபர்", "ஒரு தைரியமான வீரர்", "ஒரு திறமையான ஆசிரியர்"],
    classRange: [7, 8],
  },
  {
    word: "Voracious",
    word_ta: "பேராவல் கொண்ட",
    meaning: "Having a very eager approach; wanting a great deal",
    meaning_ta: "மிகவும் ஆர்வமான அணுகுமுறை; அதிகம் விரும்புவது",
    options: ["Having no appetite", "Having a very eager approach; wanting a great deal", "Extremely lazy", "Very patient"],
    options_ta: ["பசியின்மை", "மிகவும் ஆர்வமான அணுகுமுறை; அதிகம் விரும்புவது", "மிகவும் சோம்பேறி", "மிகவும் பொறுமையான"],
    classRange: [7, 8],
  },
  {
    word: "Nonchalant",
    word_ta: "அலட்சியமான",
    meaning: "Feeling or appearing calm and relaxed; not worried",
    meaning_ta: "அமைதியாகவும் நிதானமாகவும் உணர்வது; கவலையற்ற",
    options: ["Extremely anxious", "Feeling or appearing calm and relaxed; not worried", "Very nervous", "Deeply concerned"],
    options_ta: ["மிகவும் பதட்டமான", "அமைதியாகவும் நிதானமாகவும் உணர்வது; கவலையற்ற", "மிகவும் பரபரப்பான", "ஆழ்ந்த அக்கறையுள்ள"],
    classRange: [7, 8],
  },
  {
    word: "Catharsis",
    word_ta: "உணர்ச்சி விடுதலை",
    meaning: "The process of releasing strong emotions for relief",
    meaning_ta: "நிவாரணத்திற்காக வலுவான உணர்ச்சிகளை வெளிப்படுத்தும் செயல்முறை",
    options: ["Holding in emotions", "The process of releasing strong emotions for relief", "A type of medicine", "A mathematical concept"],
    options_ta: ["உணர்ச்சிகளை அடக்குவது", "நிவாரணத்திற்காக வலுவான உணர்ச்சிகளை வெளிப்படுத்தும் செயல்முறை", "ஒரு வகை மருந்து", "ஒரு கணிதக் கருத்து"],
    classRange: [7, 8],
  },
  {
    word: "Juxtapose",
    word_ta: "ஒருங்கிணை",
    meaning: "Place close together for comparison or contrast",
    meaning_ta: "ஒப்பிடுவதற்கு அல்லது வேறுபடுத்துவதற்கு அருகருகே வைப்பது",
    options: ["Separate completely", "Place close together for comparison or contrast", "Destroy entirely", "Ignore differences"],
    options_ta: ["முற்றிலும் பிரிப்பது", "ஒப்பிடுவதற்கு அல்லது வேறுபடுத்துவதற்கு அருகருகே வைப்பது", "முழுவதுமாக அழிப்பது", "வேறுபாடுகளை புறக்கணிப்பது"],
    classRange: [7, 8],
  },
];
